### ISSUE TITLE
IPv6 tunnel doc - Misleading statement about failover

### ISSUE THREAD

**Issue by jamesmacwhite** [linode/docs#1018]
I was reading through the "Set Up an IPv6 Tunnel on Your Linode" guide:

https://github.com/linode/docs/blob/master/docs/networking/set-up-an-ipv6-tunnel-on-your-linode.md

One of the intro points states:

"Want to increase your IPv6 footprint for redundancy and failover in case of routing issues;"

While you can implement a IPv6 tunnel to provide IPv6 connectivity with another provider + native Linode SLAAC IPv6, the guide would not configure a failover scenario as is, so I'm not sure if that's a misleading statement here. 

All the configuration examples essentially make the he-ipv6 interface the default IPv6 gateway. Which you wouldn't necessarily want for this usage case. If anything from a failover scenario, you'd want to use Linode's native IPv6 (if deployed) and then also have something like a Hurricane Electric tunnel as a backup. This on its own would only work for actual IPv6 connectivity on the Linode server itself. To have "redundancy" on web services running on a Linode server, you'd have to have add IPv6 addresses from the routed /64 and then add the appropriate AAAA DNS record, for requests to be rotated between the different subnets.

Just my two pennies (not cents, I'm British) on having the scenario listed, against how the configuration is presented.

**Comment by leslitagordita** [comment]
linode/docs#1865
