### ISSUE TITLE
Debian 9 Extra Package

### ISSUE THREAD

**Issue by dandickson** [linode/docs#1038]
On Debian 9 I needed to add an extra package:

apt-get install libdbd-mysql-perl

To avoid the following issue:

10/11 10:06:38 WARN Longview[3429] - install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base /opt/linode/longview/Linode/../ /opt/linode/longview/Linode/../lib/perl5 /opt/linode/longview/Linode/../lib/perl5/x86_64-linux-gnu-thread-multi/ /opt/linode/longview/Linode/../usr/include) at (eval 697) line 3.
Perhaps the DBD::mysql perl module hasn't been fully installed,
or perhaps the capitalisation of 'mysql' isn't right.

**Comment by GuessWhoSamFoo** [comment]
A clean install of mysql-server on Debian 9 should include libdbd-myqsl-perl. But it's not clear what you were trying to accomplish from the original issue. Feel free to let me know if it is a continuing issue and I can reopen

```
$ sudo apt install mysql-server
[sudo] password for sfoo:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  default-mysql-server galera-3 gawk libaio1 libcgi-fast-perl libcgi-pm-perl libdbd-mysql-perl libdbi-perl libencode-locale-perl libfcgi-perl
  libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhttp-date-perl libhttp-message-perl libio-html-perl libjemalloc1 liblwp-mediatypes-perl
  libmariadbclient18 libmpfr4 libreadline5 libsigsegv2 libterm-readkey-perl libtimedate-perl liburi-perl mariadb-client-10.1 mariadb-client-core-10.1
  mariadb-common mariadb-server-10.1 mariadb-server-core-10.1 mysql-common psmisc rsync socat
```

**Comment by dandickson** [comment]
This is probably a maria vs oracle issue as the particular instance in question is running oracle mysql.

________________________________
