### ISSUE TITLE
Not recommended Docker installation method on Ubuntu

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#1052]
https://www.linode.com/docs/applications/containers/how-to-install-docker-and-pull-images-for-container-deployment

The current way of installing Docker is not recommended by the official documentation.

See: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

There is literature saying the steps below are needed on a Linode - but that's not true since testing earlier today.
```
apt install -y dmsetup
dmsetup mknodes
```

Proposed changes:

Update installation instructions to Docker CE (as opposed to EE). Release cycles are one year and adjust review as necessary.

https://blog.docker.com/2017/03/docker-enterprise-edition/

**Comment by Jskobos** [comment]
Addressed by #1080
