### ISSUE TITLE
typo in farmos guide graphic

### ISSUE THREAD

**Issue by brewn** [linode/docs#1059]
"mangement"

**Comment by brewn** [comment]
also: 

"This guide will use sudo wherever possible. Complete the sections of our Securing Your Server to create a standard user account, harden SSH access and remove unnecessary network services. Do not follow the Configure a Firewall section yet–this guide includes firewall rules specifically for an OpenVPN server."

This guide doesn't contain any steps for firewall rules and it's not about an OpenVPN server. 

also the indentation needs adjusting on a few of the code blocks.

**Comment by kcraig34** [comment]
Thanks for the sharp proofread, @brewn. We're on it.

**Comment by Guaris** [comment]
@brewn Thanks, the fix is in the pipeline.
