### ISSUE TITLE
Host a Website - PHP5 

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#1117]
https://www.linode.com/docs/websites/hosting-a-website

To do:
- [x] PHP 5 support ended back in Jan 2017. Security fixes are supported until Dec 18. Probably should move to 7.1
- [x] `mysql-secure-installation` instructions are inaccurate per #725 
- [ ] Update 14.04 to 16.04+

**Comment by kcraig34** [comment]
@GuessWhoSamFoo -- Please, if these are bugs sent in by users or our support team, please card these with red or purple labels, powerpoint, and add to backlog.
Thanks.

**Comment by cwlinode** [comment]
Updated for 18.04 and php 7.1. https://github.com/linode/docs/pull/1939
