### ISSUE TITLE
Limit total numbered of featured guides

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#1126]
The featured section seems to have become a dumping ground for misc docs.

e.g.
https://www.linode.com/docs/security

It should be used to promote new guides or pin popular guides for quick access. Limit should be 6 otherwise users will have to scroll a lot to browse sections.

**Comment by kcraig34** [comment]
@GuessWhoSamFoo -- So you're suggesting we limit the number of guides in each "featured" gray background section to no more than half a dozen?
Makes sense and an sense of helpful exclusivity.
Will put idea into list for revamping index...
Thanks.

**Comment by GuessWhoSamFoo** [comment]
Closed via #1336
