### ISSUE TITLE
[HUGO] Fixes for doctest (uptime, tool-reference, game-servers)

### ISSUE THREAD

**Issue by Jskobos** [linode/docs#1164]
test.linode.com/docs/web-servers/caddy/install-and-configure-caddy-on-centos-7/

<img width="916" alt="screen shot 2017-11-10 at 3 38 08 pm" src="https://user-images.githubusercontent.com/1624067/32677679-5f385cc0-c62d-11e7-9974-fcac6f4154ad.png">

**Comment by GuessWhoSamFoo** [comment]
`/docs/security/visualize-server-security-with-the-elk-stack/`

Remove whitespaces on notes

**Comment by Jskobos** [comment]
https://docstest.linode.com/docs/uptime/monitoring/how-to-install-graphite-and-grafana-on-ubuntu-14-04/
Syntax highlighting: probably wrong file format is specified.

<img width="842" alt="screen shot 2017-11-10 at 3 47 34 pm" src="https://user-images.githubusercontent.com/1624067/32677978-8748f566-c62e-11e7-987a-6c9e9fb5c277.png">

**Comment by Jskobos** [comment]
https://docstest.linode.com/docs/uptime/monitoring/how-to-install-graphite-and-grafana-on-ubuntu-14-04/

Same as above.

<img width="441" alt="screen shot 2017-11-10 at 3 49 14 pm" src="https://user-images.githubusercontent.com/1624067/32678036-c2375104-c62e-11e7-8649-29c8e4667423.png">

**Comment by Jskobos** [comment]
https://docstest.linode.com/docs/uptime/monitoring/monitor-systems-logwatch/

Same issue.

<img width="443" alt="screen shot 2017-11-10 at 3 50 26 pm" src="https://user-images.githubusercontent.com/1624067/32678076-e9e834b6-c62e-11e7-8536-efc0ab97828a.png">

**Comment by EdwardAngert** [comment]
not really an issue for single lines of code, but becomes one for code blocks
example: https://docstest.linode.com/docs/databases/mysql/install-mysql-on-ubuntu-14-04/

**Comment by Guaris** [comment]
https://docstest.linode.com/docs/uptime/zipkin-server-configuration-using-docker-and-mysql/

<img width="884" alt="screen shot 2017-11-10 at 3 52 08 pm" src="https://user-images.githubusercontent.com/23319190/32678138-296e34d2-c62f-11e7-9488-641a785fc29f.png">

**Comment by EdwardAngert** [comment]
L132 of https://github.com/linode/docs/edit/master/docs/databases/mysql/back-up-your-mysql-databases.md

breaks the numbering because it doesn't realize it's code

**Comment by Jskobos** [comment]
/docs/uptime/monitoring/use-cacti-to-monitor-resource-utilization-on-ubuntu-12-04/

Broken file shortcode

<img width="845" alt="screen shot 2017-11-10 at 3 54 08 pm" src="https://user-images.githubusercontent.com/1624067/32678217-773e019c-c62f-11e7-975f-e292e6c39927.png">

**Comment by GuessWhoSamFoo** [comment]
<img width="861" alt="screen shot 2017-11-10 at 3 54 04 pm" src="https://user-images.githubusercontent.com/10288252/32678230-825d2e4a-c62f-11e7-85ff-b7c1bb47cad1.png">
`/docs/platform/how-to-build-your-infrastructure-using-terraform-and-linode/`

**Comment by Jskobos** [comment]
/docs/uptime/monitoring/monitoring-servers-with-zabbix/

File shortcode indentation issue

<img width="882" alt="screen shot 2017-11-10 at 3 55 13 pm" src="https://user-images.githubusercontent.com/1624067/32678251-993cd8f4-c62f-11e7-8cf4-a8607f663d6a.png">

**Comment by GuessWhoSamFoo** [comment]
`/docs/platform/billing-and-payments/`

Last line of tables need to be removed

**Comment by EdwardAngert** [comment]
busted table
/docs/databases/set-up-a-cassandra-node-cluster-on-ubuntu-and-centos/

<img width="756" alt="set_up_a_production-ready_cassandra_node_cluster_on_ubuntu_16_04_and_centos_7" src="https://user-images.githubusercontent.com/17991901/32678366-0c48766e-c630-11e7-8e3b-c1e3feb13fc5.png">

**Comment by cwlinode** [comment]
White space adjustment for example domains in `networking/dns/using-your-systems-hosts-file/`

**Comment by GuessWhoSamFoo** [comment]
<img width="863" alt="screen shot 2017-11-10 at 3 59 10 pm" src="https://user-images.githubusercontent.com/10288252/32678395-27dc27f4-c630-11e7-9723-a9254ea23ba0.png">

`/docs/platform/billing-and-payments/`

**Comment by Jskobos** [comment]
/docs/uptime/monitoring/nagios-server-monitoring/

Review for deletion

**Comment by Jskobos** [comment]
/docs/uptime/monitoring/monitor-services-with-nagios-on-ubuntu-10-10-maverick/

Review for deletion

**Comment by GuessWhoSamFoo** [comment]
<img width="803" alt="screen shot 2017-11-10 at 4 00 59 pm" src="https://user-images.githubusercontent.com/10288252/32678464-6c6c1a32-c630-11e7-9bdb-c65d9f29f301.png">

`/docs/platform/support/`

Numbering issue

**Comment by Jskobos** [comment]
docs/uptime/monitoring/monitoring-servers-with-munin-on-ubuntu-10-04-lucid/

Escaped # in the file excerpts not rendering correctly.

![screen shot 2017-11-10 at 4 28 58 pm](https://user-images.githubusercontent.com/1624067/32679407-5b464e04-c634-11e7-9401-4185d255f2c4.png)

**Comment by Jskobos** [comment]
/docs/uptime/monitoring/monitoring-resource-utilization-with-cacti-on-ubuntu-10-04-lucid/

File shortcode not converted properly.

![screen shot 2017-11-10 at 4 30 10 pm](https://user-images.githubusercontent.com/1624067/32679454-7bd3d330-c634-11e7-9ee4-ea7e943ce604.png)

**Comment by Jskobos** [comment]
/docs/uptime/monitoring/monitoring-resource-utilization-with-cacti-on-debian-5-lenny/

Same issue as Debian guide above.

**Comment by Jskobos** [comment]
https://docstest.linode.com/docs/uptime/loadbalancing/how-to-use-haproxy-for-load-balancing/

LOW PRIORITY: Config file syntax highlighting is incorrect. (Need to add 'conf' to the shortcode.)

**Comment by Jskobos** [comment]
/docs/uptime/analytics/open-web-analytics-install-and-launch-on-your-server/

Commands are insufficiently indented.

**Comment by Jskobos** [comment]
docs/uptime/analytics/piwik-on-fedora-13/

Weird "" at the end of the snippet; incorrect?

![screen shot 2017-11-13 at 10 14 46 am](https://user-images.githubusercontent.com/1624067/32732788-8ff6c600-c85b-11e7-8530-f0d42ab128fe.png)

**Comment by Jskobos** [comment]
docs/tools-reference/linux-system-administration-basics/

Very low priority. Check file type of syntax highlighting in file excerpts.

**Comment by Jskobos** [comment]
docs/tools-reference/linux-users-and-groups/

Escaped backticks

![screen shot 2017-11-13 at 10 27 22 am](https://user-images.githubusercontent.com/1624067/32733458-4efa546c-c85d-11e7-812e-4e4e5b751153.png)

**Comment by Jskobos** [comment]
docs/tools-reference/linux-package-management/

LOW PRIORITY: Config file syntax highlighting is incorrect. (Need to add 'conf' to the shortcode.)

**Comment by Jskobos** [comment]
docs/tools-reference/custom-kernels-distros/custom-compiled-kernel-debian-ubuntu/

Note shortcode and syntax highlighting

![screen shot 2017-11-13 at 10 44 17 am](https://user-images.githubusercontent.com/1624067/32734305-abb35850-c85f-11e7-99d8-b692caa9dd30.png)

**Comment by Jskobos** [comment]
/docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/

Syntax highlighting

**Comment by Jskobos** [comment]
docs/tools-reference/custom-kernels-distros/install-alpine-linux-on-your-linode/

Syntax highlighting

**Comment by Jskobos** [comment]
docs/tools-reference/custom-kernels-distros/custom-compiled-kernel-centos-7/

syntax highlighting

**Comment by Jskobos** [comment]
docs/tools-reference/custom-kernels-distros/

syntax highlighting

**Comment by Jskobos** [comment]
docs/tools-reference/custom-kernels-distros/install-freebsd-on-linode/

syntax highlighting

**Comment by Jskobos** [comment]
docs/tools-reference/custom-kernels-distros/install-coreos-on-your-linode/

**Comment by Jskobos** [comment]
/docs/tools-reference/custom-kernels-distros/install-coreos-on-your-linode/

(very minor) syntax highlighting on a deprecated guide

**Comment by Jskobos** [comment]
docs/tools-reference/tools/introduction-to-vim-customization/

Indentation errors

![screen shot 2017-11-13 at 10 57 13 am](https://user-images.githubusercontent.com/1624067/32734972-82112aac-c861-11e7-9a1b-95db0b5ea406.png)

**Comment by Jskobos** [comment]
/docs/tools-reference/tools/find-files-in-linux-using-the-command-line/

Table formatting 

![screen shot 2017-11-13 at 11 01 02 am](https://user-images.githubusercontent.com/1624067/32735143-ff12ba8e-c861-11e7-9e3e-2aa406e39dab.png)

**Comment by Jskobos** [comment]
/docs/game-servers/install-a-half-life-2-deathmatch-dedicated-server-on-debian-or-ubuntu/

Escaping characters in excerpt no longer needed. Also the last line is a link to the Wikipedia page for GLHF, which I'm not sure fits our style guide.

![screen shot 2017-11-13 at 11 10 37 am](https://user-images.githubusercontent.com/1624067/32735702-744d80f8-c863-11e7-9dc6-6df30d84b1b4.png)

**Comment by Jskobos** [comment]
docs/game-servers/install-black-mesa-on-debian-or-ubuntu/

Escaping backslashes no longer needed.

**Comment by Jskobos** [comment]
docs/game-servers/minecraft-with-mcmyadmin-on-debian/

File shortcode formatting errors.

![screen shot 2017-11-13 at 11 15 48 am](https://user-images.githubusercontent.com/1624067/32735906-14dadb1a-c864-11e7-8121-3eaf1f02430d.png)

**Comment by Jskobos** [comment]
/docs/game-servers/multicraft-on-debian/

Note shortcode formatted incorrectly.

**Comment by Jskobos** [comment]
docs/game-servers/multicraft-on-ubuntu/

Syntax highlighting

**Comment by GuessWhoSamFoo** [comment]
Closed by 30a5f62095527404284eea8026faec9f8260d061

**Comment by cwlinode** [comment]
Table called Configuration File Breakdown not rendering in `networking/diagnostics/install-ntopng-for-network-monitoring-on-debian8/`
