### ISSUE TITLE
[HUGO] Migration issues – Applications

### ISSUE THREAD

**Issue by Jskobos** [linode/docs#1169]

**Comment by Jskobos** [comment]
docs/applications/cloud-storage/tahoe-lafs-on-debian-9/

Image is suspect.

![screen shot 2017-11-13 at 1 18 02 pm](https://user-images.githubusercontent.com/1624067/32741729-3f6fd1b2-c875-11e7-927f-574e154a9644.png)

**Comment by Jskobos** [comment]
docs/applications/cloud-storage/install-seafile-with-nginx-on-ubuntu-1604/

Syntax highlighting (substantial)

**Comment by Jskobos** [comment]
docs/applications/cloud-storage/access-your-box-account-from-your-linode/

Syntax highlighting

**Comment by Guaris** [comment]
docs/applications/containers/how-to-install-openvz-on-debian-9/

![screen shot 2017-11-13 at 1 20 12 pm](https://user-images.githubusercontent.com/23319190/32741834-94f4c822-c875-11e7-8205-16c937c413aa.png)

define filetype in shortcode

**Comment by Jskobos** [comment]
docs/applications/media-servers/how-to-install-shoutcast-dnas-server-on-linux/

Misidentified quote in file excerpt:

![screen shot 2017-11-13 at 1 24 11 pm](https://user-images.githubusercontent.com/1624067/32741984-0746ff26-c876-11e7-94e4-651d7bad5891.png)

**Comment by Guaris** [comment]
applications/project-management/jupyter-nobook-on-jekyll/

![screen shot 2017-11-13 at 1 24 28 pm](https://user-images.githubusercontent.com/23319190/32741997-1bb543c8-c876-11e7-82ea-a5b8fbb69bde.png)
![screen shot 2017-11-13 at 1 24 45 pm](https://user-images.githubusercontent.com/23319190/32741999-1bc26602-c876-11e7-8d4f-97166aab3599.png)

**Comment by Jskobos** [comment]
docs/applications/big-data/how-to-move-machine-learning-model-to-production/

Strange header

![screen shot 2017-11-13 at 1 26 13 pm](https://user-images.githubusercontent.com/1624067/32742066-47b43e84-c876-11e7-888c-4e9e65cdd224.png)

**Comment by Jskobos** [comment]
docs/applications/big-data/install-a-jupyter-notebook-server-on-a-linode-behind-an-apache-reverse-proxy/

Formatting error and syntax highlighting

![screen shot 2017-11-13 at 1 27 51 pm](https://user-images.githubusercontent.com/1624067/32742148-80f414b2-c876-11e7-9f8b-e9918a47e17d.png)

**Comment by Jskobos** [comment]
docs/applications/big-data/how-to-install-and-configure-a-redis-cluster-on-ubuntu-1604/

Table formatting error

![screen shot 2017-11-13 at 1 28 51 pm](https://user-images.githubusercontent.com/1624067/32742191-ac338ebe-c876-11e7-910a-bb1215ded0da.png)

**Comment by Guaris** [comment]
docs/applications/configuration-management/configure-and-use-salt-ssh/
![screen shot 2017-11-13 at 1 29 11 pm](https://user-images.githubusercontent.com/23319190/32742194-ad248c10-c876-11e7-8ca8-b0c74e9377ac.png)

**Comment by Guaris** [comment]
![screen shot 2017-11-13 at 1 30 42 pm](https://user-images.githubusercontent.com/23319190/32742251-df91c956-c876-11e7-8fec-b5a53a7dc79f.png)
docs/applications/configuration-management/use-puppet-modules-to-create-a-lamp-stack/

**Comment by Jskobos** [comment]
docs/applications/big-data/big-data-in-the-linode-cloud-streaming-data-processing-with-apache-storm/

File formatting error

**Comment by Guaris** [comment]
applications/configuration-management/install-and-configure-salt-master-and-minion-servers/
![screen shot 2017-11-13 at 1 31 37 pm](https://user-images.githubusercontent.com/23319190/32742294-052e5d78-c877-11e7-956f-2fb4287932cf.png)

**Comment by Jskobos** [comment]
docs/applications/messaging/using-weechat-for-irc/

Table format error.

![screen shot 2017-11-13 at 1 31 39 pm](https://user-images.githubusercontent.com/1624067/32742305-0d4c1b80-c877-11e7-9071-1d1d92a8605a.png)

**Comment by Guaris** [comment]
docs/applications/configuration-management/install-and-configure-puppet/

![screen shot 2017-11-13 at 1 32 15 pm](https://user-images.githubusercontent.com/23319190/32742329-1849c1d6-c877-11e7-962d-6d6b0c0ed02f.png)

**Comment by Jskobos** [comment]
docs/applications/messaging/instant-messaging-services-with-ejabberd-on-fedora-13/

Unclosed " causing syntax highlight error.

![screen shot 2017-11-13 at 1 34 20 pm](https://user-images.githubusercontent.com/1624067/32742431-6b9f6ebc-c877-11e7-971c-f7a831f0691e.png)

**Comment by Guaris** [comment]
docs/applications/voip/install-and-configure-mumble-on-debian/
![screen shot 2017-11-13 at 1 34 47 pm](https://user-images.githubusercontent.com/23319190/32742444-735fa590-c877-11e7-85fc-1f1e891f7990.png)

**Comment by Guaris** [comment]
docs/applications/voip/install-asterisk-on-centos-7/

![screen shot 2017-11-13 at 1 35 15 pm](https://user-images.githubusercontent.com/23319190/32742472-8cf833a0-c877-11e7-846e-0d2ebf4936af.png)

**Comment by Jskobos** [comment]
docs/applications/messaging/instant-messaging-services-with-ejabberd-on-ubuntu-9-04-jaunty/

[facepalm]

![screen shot 2017-11-13 at 1 39 21 pm](https://user-images.githubusercontent.com/1624067/32742657-1b6f044c-c878-11e7-9bb8-b22ddd5a9c33.png)

**Comment by GuessWhoSamFoo** [comment]
Fixed via f2c527b211f92160a8adb7b23a7036cf2a3f7b9b
