### ISSUE TITLE
[HUGO] Migration issues: Webservers

### ISSUE THREAD

**Issue by Jskobos** [linode/docs#1171]

**Comment by Jskobos** [comment]
docs/web-servers/caddy/install-and-configure-caddy-on-centos-7/

Minor syntax highlighting

**Comment by Jskobos** [comment]
docs/web-servers/lemp/lemp-stack-on-debian-8/

Nested shortcode formatting error

![screen shot 2017-11-13 at 1 45 03 pm](https://user-images.githubusercontent.com/1624067/32742956-ed5dc11e-c878-11e7-9722-7d316dd7991d.png)

**Comment by Jskobos** [comment]
docs/web-servers/lemp/lemp-server-on-arch-linux/

File shortcode format error
![screen shot 2017-11-13 at 1 50 59 pm](https://user-images.githubusercontent.com/1624067/32743197-bd73ec20-c879-11e7-914f-13edf12648d8.png)

**Comment by Guaris** [comment]
docs/web-servers/apache-tips-and-tricks/configure-modsecurity-on-apache/
![screen shot 2017-11-13 at 1 51 12 pm](https://user-images.githubusercontent.com/23319190/32743206-c2a9dfd8-c879-11e7-9234-905cc732f5f7.png)

**Comment by Jskobos** [comment]
docs/web-servers/apache/install-php-fpm-and-apache-on-debian-8/

Syntax highlighting

**Comment by Jskobos** [comment]
/docs/web-servers/apache/apache-web-server-debian-8/

Correct but ugly.

![screen shot 2017-11-13 at 1 55 45 pm](https://user-images.githubusercontent.com/1624067/32743447-6966e5aa-c87a-11e7-87fb-f3cd6bb4e3f8.png)

**Comment by Jskobos** [comment]
docs/web-servers/apache/apache-web-server-debian-7/

Same as above.

**Comment by Jskobos** [comment]
docs/web-servers/apache/apache-web-server-ubuntu-12-04/

Same as above.

**Comment by Jskobos** [comment]
docs/web-servers/apache/apache-2-web-server-on-debian-6-squeeze/

Same as above.

**Comment by GuessWhoSamFoo** [comment]
Not going to fix front end right now. Closed via 74a81ceff64423d1b54b98cbd0f654b55fffdfee
