### ISSUE TITLE
Migration issues – Websites

### ISSUE THREAD

**Issue by Jskobos** [linode/docs#1172]

**Comment by Jskobos** [comment]
docs/websites/host-a-website-with-high-availability/

Syntax highlighting 

![screen shot 2017-11-13 at 2 13 50 pm](https://user-images.githubusercontent.com/1624067/32744258-ed226c78-c87c-11e7-9707-9c82795864ba.png)

**Comment by Jskobos** [comment]
docs/websites/varnish/use-varnish-and-nginx-to-serve-wordpress-over-ssl-and-http-on-debian-8/

Syntax highlighting – substantial throughout guide

**Comment by Guaris** [comment]
docs/websites/cms/configure-apache-to-run-multiple-wordpress-sites-on-one-linode/

![screen shot 2017-11-13 at 2 16 04 pm](https://user-images.githubusercontent.com/23319190/32744397-55f3a640-c87d-11e7-862d-70dadc8f659c.png)

**Comment by Jskobos** [comment]
docs/websites/forums/install-and-run-askbot-on-ubuntu-16-04/

syntax highlighting (substantial)

**Comment by Guaris** [comment]
docs/websites/cms/how-to-install-ghost-cms-on-ubuntu-16-04/


spacing

**Comment by Guaris** [comment]
docs/websites/cms/install-odoo-10-on-ubuntu-16-04/

![screen shot 2017-11-13 at 2 19 23 pm](https://user-images.githubusercontent.com/23319190/32744508-b0004f80-c87d-11e7-9a17-c1918ea076c8.png)

**Comment by Guaris** [comment]
/docs/websites/cms/install-wordpress-on-ubuntu-16-04/
![screen shot 2017-11-13 at 2 21 00 pm](https://user-images.githubusercontent.com/23319190/32744630-2ca9f46e-c87e-11e7-9141-0efba61666fc.png)

**Comment by Guaris** [comment]
docs/websites/cms/install-and-configure-drupal-8/
change shortcode for file

**Comment by Guaris** [comment]
docs/websites/cms/install-and-configure-drupal-8/

Shortcode for file

**Comment by Jskobos** [comment]
docs/websites/ecommerce/install-magento-on-centos-7/

File format error

![screen shot 2017-11-13 at 2 41 53 pm](https://user-images.githubusercontent.com/1624067/32745477-dec9cfc8-c880-11e7-98ef-a9d218f4cdb5.png)

**Comment by Jskobos** [comment]
docs/websites/ecommerce/install-magento-on-ubuntu-16-04/

Nested file shortcodes swallowed.

![screen shot 2017-11-13 at 2 43 01 pm](https://user-images.githubusercontent.com/1624067/32745523-febd5d54-c880-11e7-9c15-1efa5c9d1716.png)

**Comment by Jskobos** [comment]
docs/websites/ecommerce/opencart-on-centos-6/

File shortcode formatting error

![screen shot 2017-11-13 at 2 44 17 pm](https://user-images.githubusercontent.com/1624067/32745596-2d116baa-c881-11e7-9321-7dfd528524fc.png)

**Comment by Jskobos** [comment]
docs/websites/ecommerce/opencart-on-debian-6-squeeze/

Same as above
