### ISSUE TITLE
[HUGO] Migration issues – Networking

### ISSUE THREAD

**Issue by Jskobos** [linode/docs#1174]

**Comment by Jskobos** [comment]
docs/networking/create-a-socks5-proxy-server-with-shadowsocks-on-ubuntu-and-centos7/

Indentation error

![screen shot 2017-11-13 at 2 53 23 pm](https://user-images.githubusercontent.com/1624067/32746016-72503574-c882-11e7-932a-4c317baa59fd.png)

**Comment by Jskobos** [comment]
docs/networking/an-overview-of-ipv6-on-linode/

Final line of table is a formatting glitch

![screen shot 2017-11-13 at 2 56 00 pm](https://user-images.githubusercontent.com/1624067/32746167-cfa837d0-c882-11e7-9de3-20fc6019b820.png)

**Comment by Jskobos** [comment]
/docs/networking/how-to-enable-native-ipv6-on-linux/

Same as above.

**Comment by Jskobos** [comment]
docs/networking/diagnostics/install-ntopng-for-network-monitoring-on-debian8/

Syntax highlighting

**Comment by Jskobos** [comment]
docs/networking/diagnostics/install-iperf-to-diagnose-network-speed-in-linux/

Table formatting error

![screen shot 2017-11-13 at 2 59 27 pm](https://user-images.githubusercontent.com/1624067/32746327-4e3a72c0-c883-11e7-92eb-03cb556c15d1.png)

**Comment by Jskobos** [comment]
docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-12-04-lts-precise-pangolin/

File shortcodes (2)

![screen shot 2017-11-13 at 3 02 00 pm](https://user-images.githubusercontent.com/1624067/32746458-a8ca9ab2-c883-11e7-854a-da78ead093d5.png)

**Comment by Jskobos** [comment]
/docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-ubuntu-11-04-natty/

Same as above.

**Comment by Jskobos** [comment]
docs/networking/dns/use-unbound-for-local-dns-resolution-on-fedora-15/

Same as above.

**Comment by Jskobos** [comment]
https://docstest.linode.com/docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-11-04-natty/

Same as above.

**Comment by Jskobos** [comment]
docs/networking/dns/use-unbound-for-local-dns-resolution-on-debian-6-squeeze/

Same as above.

**Comment by Jskobos** [comment]
docs/networking/dns/use-unbound-for-local-dns-resolution-on-fedora-14/

Same as above

**Comment by Jskobos** [comment]
docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-10-10-maverick/

Same as above

**Comment by Jskobos** [comment]
docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-fedora-14/

Same as above.

**Comment by Jskobos** [comment]
docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-ubuntu-10-10-maverick/

Same as above.

**Comment by Jskobos** [comment]
docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-ubuntu-10-04-lucid/

Same as above.

**Comment by Jskobos** [comment]
docs/networking/dns/use-dig-to-perform-manual-dns-queries/

Maybe not an error but the ;; is weird if it's just console output.

![screen shot 2017-11-13 at 3 06 48 pm](https://user-images.githubusercontent.com/1624067/32746669-56e619d2-c884-11e7-9be9-917246d7b5bb.png)

**Comment by Jskobos** [comment]
docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-fedora-13/

File shortcodes (3)

**Comment by Jskobos** [comment]
docs/networking/dns/use-unbound-for-local-dns-resolution-on-fedora-13/

Same as above

**Comment by Jskobos** [comment]
docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-9-10-karmic/

Same as above

**Comment by Jskobos** [comment]
docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-ubuntu-9-10-karmic/

Same as above

**Comment by Jskobos** [comment]
docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-10-04-lts-lucid/

Same as above

**Comment by Jskobos** [comment]
docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-debian-5-lenny/

Same as above. Shortcodes also mixed with section headers

**Comment by Jskobos** [comment]
docs/networking/dns/use-unbound-for-local-dns-resolution-on-debian-5-lenny/

Same as above.

**Comment by Guaris** [comment]
/docs/networking/vpn/set-up-a-hardened-openvpn-server/
Set file excerpt type.

**Comment by Jskobos** [comment]
docs/networking/ssh/setting-up-an-ssh-tunnel-with-your-linode-for-safe-browsing/

Trailing ]

![screen shot 2017-11-13 at 3 11 53 pm](https://user-images.githubusercontent.com/1624067/32746892-09a84748-c885-11e7-80eb-387493b2fcfa.png)

**Comment by Guaris** [comment]
docs/networking/vpn/secure-communications-with-openvpn-on-ubuntu-12-04-precise-and-debian-7/
![screen shot 2017-11-13 at 3 12 29 pm](https://user-images.githubusercontent.com/23319190/32746913-1bcfb474-c885-11e7-9153-2f99f6dc7045.png)
