### ISSUE TITLE
Notify router on ip swap

### ISSUE THREAD

**Issue by creativetags** [linode/docs#1188]
This is wrong - see my pull request #1190 for my attempt to fix. Please could someone check it and correct.

networking/remote-access.md

```
If the IP is unreachable after a few minutes, you may need to notify the router directly of the IP change with the arp command

arping -c5 -I eth0 -b -A -s 198.51.100.10 198.51.100.1
```

-s means Set source MAC address but then an IP address is provided so should it be uppercase? -S

**Comment by GuessWhoSamFoo** [comment]
Fixed via https://github.com/linode/docs/pull/1190
