### ISSUE TITLE
Duplicated guide (not symlinked)

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#1227]
/tools-reference/ssh/install-mosh-server-as-ssh-alternative-on-linux/

/networking/ssh/install-mosh-server-as-ssh-alternative-on-linux/

Probably should remove one otherwise it will be hard to track

**Comment by kcraig34** [comment]
In the past week, /tools-reference/ssh...mosh has gotten 891 visits while /networking/ssh...mosh has gotten 22, according to Google Analytics.
If one can be deleted, I recommend it be the networking version.
@GuessWhoSamFoo
