### ISSUE TITLE
Faulty DNS records

### ISSUE THREAD

**Issue by valuta1995** [linode/docs#1256]
In the "Email with Postfix, Dovecot, and MySQL" the following DNS records are shown
```
example.com         MX      10      example.com
example.com         MX      10      12.34.56.78
mail.example.com    MX      10      12.34.56.78
```
I believe the latter two should be A records instead of MX

**Comment by valuta1995** [comment]
Problem not resolved. The mail.example.com should also be an A record. Note that MX records cannot refer to IPs
example.com         A       10      12.34.56.78
example.com         MX      10      example.com
mail.example.com    MX      10      12.34.56.78

**Comment by Guaris** [comment]
@valuta1995 You are correct, MX records cannot refer so I believe it should be instead:
`mail.example.com MX 10 example.com`
I'll have to run this through someone else before I can put in the change. Thanks a lot for chiming in!

**Comment by Guaris** [comment]
@valuta1995 Hey! How does this look?

example.com A 10 12.34.56.78
example.com MX 10 example.com
mail.example.com MX 10 example.com

**Comment by valuta1995** [comment]
I believe this is correct.
________________________________
