### ISSUE TITLE
Add a copy button for code blocks

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#1304]
[clipboard.js](https://clipboardjs.com/) looks like a viable condidate.

Implementation probably will have some combination of:
 - on-hover
 - copy icon
 - Feedback for successful copy
 - Fallback for unsupported browsers

**Comment by kcraig34** [comment]
Is this an intended new feature for our library, @GuessWhoSamFoo? 
Just looking for a quick clarification of the why and wherefore behind adopting clipboard.js. Thanks.

**Comment by GuessWhoSamFoo** [comment]
Addressed in https://github.com/linode/hercules/pull/26

This greatly improves usability of the library. Should have been implemented years ago imo

**Comment by GuessWhoSamFoo** [comment]
Inplemented via d067bf5ac155e3c00858174996d86288f9a32b5f
