### ISSUE TITLE
More Information and See Also are ambiguous

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#1337]
Currently `More Information` is generated from external links defined in the YAML header and `See Also` is generated through Hugo's [Related content](https://gohugo.io/content-management/related/) feature.

We should try to combine them into one section and find a better way of community external/internal resources.

**Comment by kcraig34** [comment]
To what end, @GuessWhoSamFoo? Will combining them make a page load more efficiently or is this just a best practice for structure of a page? Please clarify? (Wondering about cost/benefit of pursuing this issue.) Thx.

**Comment by GuessWhoSamFoo** [comment]
Cost is roughly 30 minutes of employee time. Benefit is disambiguation of external/internal sources. Should have minimal impact on page load times.

<img width="898" alt="screen shot 2017-12-21 at 8 36 38 am" src="https://user-images.githubusercontent.com/10288252/34257987-26c07130-e62a-11e7-9f42-09d0f4c30bce.png">

**Comment by kcraig34** [comment]
Go for it, @GuessWhoSamFoo.

Please just make a card for it. Thx.
