### ISSUE TITLE
Recommended usage of headers in formatting guide

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#1363]
From #1362, there are likely headers that don't logically follow an idea in the table of contents. The writer's formatting guide needs to have guidance on this.

**Comment by kcraig34** [comment]
Sounds good and apropos of our intent to improve docs quality - especially now w/floating Toc. Let's revise formatting guide to note this and add it to the duties of copy editing - verify headers are logical, sequential, and meaningful. 
Feedback?

**Comment by leslitagordita** [comment]
[Paragraph Structure](https://www.linode.com/docs/linode-writers-formatting-guide/#paragraph-structure) in Linode Writer's Formatting Guide addresses proper usage of headers.
