### ISSUE TITLE
Update Ansible version requirements for Python 3 support

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#1421]
Link: https://linode.com/docs/applications/configuration-management/learn-how-to-install-ansible-and-run-playbooks/
## Issue
Aside from indentation, Ansible 2.2 and above offers Python 3 support.

## Suggested Fix
Clarify version requirements for Ansible wrt to Python. See https://docs.ansible.com/ansible/latest/intro_installation.html

**Comment by emilyparkes** [comment]
I would like to solve this issue, 
My Pull Request is XXXX

**Comment by GuessWhoSamFoo** [comment]
Closed via #1522
