### ISSUE TITLE
Install Alpine Linux on your Linode Proposed Changes

### ISSUE THREAD

**Issue by dizzzan** [linode/docs#1426]
Link: https://linode.com/docs/tools-reference/custom-kernels-distros/install-alpine-linux-on-your-linode/
## Issue

I found that the grub config for grsec kernel was incorrect and couldn't boot. Upon attempting to send a pull request I see that it is corrected in the git repo but is not reflected in the doc.

## Suggested Fix

Update doc with corrected grub.cfg replacing '-grsec' with '-hardened' as:
```
set root=(hd0)
set default="Alpine Linux"
set timeout=0

set root=(hd0) set default="Alpine Linux" set timeout=0

menuentry "Alpine Linux" {
    linux /vmlinuz-hardened root=/dev/sdb modules=sd-mod,usb-storage,ext4 console=ttyS0 quiet
    initrd /initramfs-hardened
}
```

**Comment by GuessWhoSamFoo** [comment]
Yeah, #1403 addressed this. Should be reflected on the live site later today. Thanks!
