### ISSUE TITLE
The way to disable  SSLv3 for dovecot 2.0.19

### ISSUE THREAD

**Issue by convissor** [linode/docs#144]
For earlier versions of dovecot, docs/security/security-patches/disabling-sslv3-for-poodle.md says one needs to patch the source code to disable SSLv3.  I'm running dovecot 2.0.19 on Ubuntu 12.04 and disabled SSLv3 by uncommenting and adjusting my 10-ssl.conf file to be:

ssl_cipher_list = ALL:!LOW:!SSLv2:!SSLv3:!EXP:!aNULL

The ssl_cipher_list line that ships with the package is commented out and lacks the !SSLv3 element.

**Comment by buhman** [comment]
:thumbsdown: `ssl_cipher_list = TLSv1` will exclude TLS 1.1 and 1.2.

[dovecot-sslv3-disable](https://launchpadlibrarian.net/187434706/dovecot-sslv3-disable.diff) is sufficient.

**Comment by PeopleInside** [comment]
Hi @buhman , How to apply the patch to dovecot 2.0.9? Thanks
