### ISSUE TITLE
Migrating a Server to Your Linode Proposed Changes

### ISSUE THREAD

**Issue by unikitty37** [linode/docs#1452]
Link: https://linode.com/docs/platform/disk-images/migrating-a-server-to-your-linode/
## Issue

Guide has been deprecated.

## Suggested Fix

Link to current, maintained guide is added at the top of the guide. Currently, the only maintained guide seems to assume that the "migrating from shared hosting" guide, which does not cover migrating email servers, mailman lists and so on. There's more to the Internet than just websites!

**Comment by GuessWhoSamFoo** [comment]
@unikitty37 Thanks for your input! Keep on the lookout as well continue to expand the library in the future and touch upon more migration documentation.
