### ISSUE TITLE
Install Subsonic Media Server on Ubuntu or Debian to Stream Music Through Your Linode Proposed Changes

### ISSUE THREAD

**Issue by caseyanderson** [linode/docs#1507]
Link: https://linode.com/docs/applications/media-servers/install-subsonic-media-server-on-ubuntu-or-debian/
## Issue
openjdk-7-jre-headless is not available from aptitude under Ubuntu 16.04

## Suggested Fix
confirm which version of java under ubuntu 16.04 allows for one to actually connect to the subsonic control panel (cannot do so under 16.04 currently). after spending an entire day going through message board posts and guessing my way through this, i can confidently say that openjdk 9 does not work and though some other people have gotten openjdk 8 to work i was not able to.

**Comment by caseyanderson** [comment]
Followed the steps described [here](https://www.linuxbabe.com/ubuntu/install-subsonic-media-server-ubuntu-16-04), which directs one to install `openjdk-8-jre` and then download and install `subsonic-6.1.1.deb` and can connect to the control panel as expected. For whatever reason I was unable to get `openjdk-8-jre` and `subsonic-6.1.3.deb` to play nicely but that might have been programmer error on my part. y'all should:

1. update your doc to reflect this info
2. HT or link out to Xiao Guo-An at `LinuxBabe.Com` as her procedure is the one that you will be able to reference to fix the broken procedure described in this doc. You can read her article above.

Huzzah and Thanks Xiao Guo-An!

**Comment by Jskobos** [comment]
@caseyanderson Thanks for the tip. We've updated the Java version and confirmed that the installation works on a fresh Linode. (XR #1721)
