### ISSUE TITLE
How to use a YubiKey for Two-Factor Secure Shell Authentication Proposed Changes

### ISSUE THREAD

**Issue by MateuszKoguc** [linode/docs#1515]
Link: https://linode.com/docs/security/authentication/how-to-use-yubikey-for-two-factor-ssh-authentication/
## Issue
In description there are two different paths used to the same file
1) **/etc/ssh/yubikeys**
2) **/etc/ssh/authorized_yubikeys**

---

In point 7 of **Install the Authentication SoftwarePermalink** machine reboot is not required. Sshd daemon restart is enough: **sudo service sshd restart**.

## Suggested Fix
Please unify file path to use either 1) or 2) only and also put extra information about restarting sshd daemon.

**Comment by GuessWhoSamFoo** [comment]
@Guaris

**Comment by Jskobos** [comment]
Addressed by #1533
