### ISSUE TITLE
Install Let's Encrypt to Create SSL Certificates Proposed Changes

### ISSUE THREAD

**Issue by Guaris** [linode/docs#1520]
Link: https://linode.com/docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates/
## Issue
 each domain has its own directory in /etc/letsencrypt/live. There will be only one directory . You can verify that all of the domains are under the one certificate by running  "./certbot-auto certificates". If you need/want separate directories, you would need to run the command separately for each domain.

-From Disqus Comments

**Comment by splendidbits** [comment]
Would love to see some movement on this.

For more information, here is the certbot landing-page with completed plugins from most of the other major vps/dns providers:

https://certbot.eff.org/docs/using.html#renewing-certificates

**Comment by Jskobos** [comment]
Hey @splendidbits, thanks for the suggestion...we'll see if we can get something going. This particular issue is about copy edits to our Let's Encrypt guide that were taken in back in February, so I'm going to go ahead and close it.
