### ISSUE TITLE
Install a LEMP Stack on CentOS 7 with FastCGI Proposed Changes

### ISSUE THREAD

**Issue by maheoasic** [linode/docs#1532]
Link: https://linode.com/docs/web-servers/lemp/lemp-stack-on-centos-7-with-fastcgi/

**Comment by Guaris** [comment]
@maheoasic Hey! Thanks for noticing that, this guide is actually due to be reworked starting next week. We will incorporate your change during the update!

**Comment by cwlinode** [comment]
The guide has been updated and the procedure given is reliable enough that creating an index.html file just to check NGINX is unnecessary. When followed from start to finish, the test.php file at the end of the document will reveal that NGINX is working.
