### ISSUE TITLE
Virtual Cloud Desktop Using Apache Guacamole Proposed Changes

### ISSUE THREAD

**Issue by alexfornuto** [linode/docs#1614]
Link: https://linode.com/docs/applications/remote-desktop/remote-desktop-using-apache-guacamole-on-docker/
## Issue
This doc uses `apt` commands, but doesn't reference what distro(s) it's intended for.

## Suggested Fix
Clarify if this guide is for Debian, Ubuntu, both, or other. If other, include non-apt commands.

**Comment by Guaris** [comment]
Hi @alexfornuto ! Thanks for submitting an issue to our documentation repo! The section you are referring to uses `apt`, which implies a Debian based operating system. The rest of the guide however uses Docker, and is distro-agnostic. We will take your issue into consideration when we choose to update this doc! In the meantime, please feel free to submit a PR with your change.

-Angel
