### ISSUE TITLE
Update WP-CLI doc to reflect new version of Ubuntu

### ISSUE THREAD

**Issue by JohnBlood** [linode/docs#1618]
I was looking for information on how to install WordPress and discovered the doc on how to use WP-CLI. However, the article (the title at least) is for Ubuntu 14.04. Since the older version of Ubuntu you support is 16.04, I would recommend updating the title. Thanks.

**Comment by JohnBlood** [comment]
Since I have experience with Hugo, I could make the changes, but I would like to get permission before I do something like that.

**Comment by GuessWhoSamFoo** [comment]
@JohnBlood You're more than welcome to make changes. There should be minimal involvement with Hugo other than running the binaries to see the changes locally (although that's not even necessary since chances are now visible via Netlify)

**Comment by leslitagordita** [comment]
@JohnBlood we've added to our doc queue a guide for WP-CLI on Ubuntu 16.04 and Ubuntu 18.04.
