### ISSUE TITLE
Getting Started with Linode Proposed Changes

### ISSUE THREAD

**Issue by dmitriz** [linode/docs#1704]
Link: https://linode.com/docs/getting-started/
## Issue
The Section "Set the Hostname" starts with "Your system’s hostname should be something unique..."
## Suggested Fix
Since this is a section for beginners who may not know what "hostname" is, it might be helpful to begin by outlining the reasons to make this change, explaining what is the hostname and how else it might be useful.

**Comment by GuessWhoSamFoo** [comment]
Thanks for the feedback. Greater care should definitely be taken to introducing terminology for documentation geared towards beginners.

**Comment by leslitagordita** [comment]
linode/docs#1867
