### ISSUE TITLE
Using < or > in shortcodes breaks HTML minification

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#1712]
Current offending files have either `<` or `>` in output shortcodes which fails with on HTML minification.

`docs/tools-reference/tools/how-to-install-midnight-commander.md`

https://github.com/linode/docs/blame/master/docs/tools-reference/tools/how-to-install-midnight-commander.md#L129

`docs/tools-reference/tools/view-the-beginning-of-text-files-with-head.md`

https://github.com/linode/docs/blame/master/docs/tools-reference/tools/view-the-beginning-of-text-files-with-head.md#L48

`docs/tools-reference/tools/view-and-follow-the-end-of-text-files-with-tail.md`

https://github.com/linode/docs/blame/master/docs/tools-reference/tools/view-and-follow-the-end-of-text-files-with-tail.md#L36

#1709 attempts to address this

**Comment by hyshka** [comment]
This doesn't seem to be an issue now when running `hugo` with `minify` flag.

```hugo --minify
                                |  EN
+-----------------------+------+
  Pages                    | 1145
  Paginator pages    |    0
  Non-page files       | 2623
  Static files              |   24
  Processed images |    0
  Aliases                   | 1307
  Sitemaps               |    1
  Cleaned                 |    0

Total in 4237 ms
```
