### ISSUE TITLE
Introduction to Nextcloud Talk Proposed Changes

### ISSUE THREAD

**Issue by mario** [linode/docs#1738]
Link: https://linode.com/docs/applications/cloud-storage/install-nextcloud-talk/
## Issue
- video calls won't work in a lot of situations if you don't have TURN server installed thus giving users a bad experience of the platform
- the article says Nextcloud Talk is built on "Spreed". Spreed is actually the old name, new one is Nextcloud Talk.

## Suggested Fix
- suggest using coTurn, along with its setup (proxied, so it'd use 80/443 ports)
- the fix for the second thing is simply not to mention Spreed :D It's just a name of the Github repository atm.

**Comment by leslitagordita** [comment]
@mario thanks for the suggestion.  I have submitted a PR (linode/docs#1868) that removes the mention of spreed.  I have also added your suggestion to enhance the guide with information on installing TURN server.

**Comment by mario** [comment]
@leslitagordita thanks for the feedback. 

Some information regarding TURN server install & config can be found here: https://github.com/nextcloud/talk-android/blob/master/docs/TURN.md

**Comment by Guaris** [comment]
We've added this!
