### ISSUE TITLE
How to Install and Set Up a 3-Node Hadoop Cluster Proposed Changes

### ISSUE THREAD

**Issue by coldhack** [linode/docs#1740]
Link: https://linode.com/docs/databases/hadoop/how-to-install-and-set-up-hadoop-cluster/
## Issue
After installing Hadoop and get "everything" right, i can't see live nodes (i.e., datanodes) on the report.

I've confirmed, and the "DataNode" is runnig on both hosts (datanode hosts).

Any ideia?

**Comment by leslitagordita** [comment]
Hello @coldhack, please forward your question to the [guide's](https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794) comments section at the bottom of the page or to the [Linode Community Questions page](https://www.linode.com/community/questions/).  The Issues section for this project is reserved primarily to report errors in the guides or suggest enhancements.
