### ISSUE TITLE
Running a Mail Server Proposed Changes

### ISSUE THREAD

**Issue by rmcaninch** [linode/docs#1764]
Link: https://linode.com/docs/email/running-a-mail-server/
## Issue
Port 465 should only be used for legacy compatibility. It has been reassigned another use by IANA.
## Suggested Fix
Port 587 is for SMTP submission and using STARTTLS for encryption.

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt
http://blog.mailgun.com/25-465-587-what-port-should-i-use/

**Comment by leslitagordita** [comment]
@rmcaninch Thank you for submitting this issue. A PR https://github.com/linode/docs/pull/2209 has been submitted with an update. This update will be available in the next release.
