### ISSUE TITLE
Creating Your First Chef Cookbook Proposed Changes

### ISSUE THREAD

**Issue by renderbox** [linode/docs#1800]
Link: https://linode.com/docs/applications/configuration-management/creating-your-first-chef-cookbook/
## Issue
FATAL: knife cookbook create has been removed.

## Suggested Fix
Please use `chef generate cookbook` from the ChefDK

**Comment by leslitagordita** [comment]
@renderbox thank you for this information.  We have queued this guide to be reviewed and updated with your suggestion.

**Comment by leslitagordita** [comment]
Hello @renderbox this guide was updated on August 6th. Thank you for your feedback.

**Comment by renderbox** [comment]
Thanks!
