### ISSUE TITLE
Securing your server - SSH Daemon Options (Point 3)

### ISSUE THREAD

**Issue by jamesmacwhite** [linode/docs#1801]
https://www.linode.com/docs/security/securing-your-server/

I'm intrigued as to what the benefit of restricting SSH to IPv4 or IPv6 does in terms of security? To me this seems a little misleading and is more security by obscurity. 

Right now you could argue that having SSH on IPv6 only would significantly cut down on the port scan attempts, given the majority will still come from IPv4, but it doesn't really provide any security and is only due to the lack of IPv6 adoption, which will _eventually_ supersede IPv4.

Perhaps the better approach is to mention using a firewall to restrict the SSH port to a specific list of hosts or IP ranges, rather than have it open to any host.

**Comment by nixy** [comment]
It's 100% security through obscurity, but that doesn't mean it doesn't have value.

If you know for a fact that you'll only access your machine over IPv4 or IPv6 then doing this lets you cut out a huge swath of addresses that could be trying to login. That said, as you point out, this is pretty much a weaker version of a whitelist for trusted hosts.

A whitelist of trusted hosts is far more secure, but is also incredibly cumbersome. IMO this security guide isn't for experts, but is for people who are just starting out with servers and need to know how to protect themselves from brute force attacks. For that purpose I think this is fine.

Mentioning that a whitelist can be used to further restrict it is probably worthwhile, but it doesn't seem like a good idea to actually walk through that process in this guide. Though Linode may not want to mention something without expanding on it, as that ends up with questions to their support team.

**Comment by jamesmacwhite** [comment]
@nixy. I understand what you're saying and can appreciate the guide is aimed at more novice users, but my concern is it a false sense of security the statement gives off. A port scan is absolute, doesn't really matter if its v4 or v6, same endpoint, just different IP version to get there. If a service is listening and visible on the public interface its a target. I mean, if this is a more novice guide, would some novices enough know what IPv4 and IPv6 is? Genuine question, not trying to be facetious.

My view on this remains that it should be tweaked or at least de-emphasise any real security benefit from it. Its in the same category as changing the SSH port to something like `54253`. That would cut down port scans, but it doesn't mean you've improved "security". In fact you've probably made it harder to connect on networks that restrict TCP access. Sometimes SSH 22 might be blocked, but you've got more of a chance of a standard TCP port, rather than some random higher unregistered one!

You mention more advanced SSH topics, I think if they exist, or would need to be written, references to such advanced topics from the novice guide isn't a bad idea.

In my view SSH security should be around the following:

* Firewalling SSH TCP 22 - With a good firewall, there's no reason why you can't keep SSH on the default port and/or on IPv4/IPv6. The best security is to block all SSH connections by default and whitelist select hosts. The added bonus with Linode is you have a further console method outside of SSH if you aren't at a whitelisted host, IP rotated, lock out etc.

* Ban SSH port scans with something like `fail2ban` or `csf/lfd` - Its quite trivial to have some automated tool scanning logs for port scans and automatically ban IPs after `x` times for a period of time. I personally have used CSF/LFD for a number of years and it works fine.

* Enable verbose SSH logging and have an auditing tool regularly monitor connections to the SSH daemon - Tools like `lynis` and others can do this, but again we are now going into advanced stuff.

Clearly, this potentially creates a few new SSH advanced guides, but worth considering for the future maybe?

**Comment by nixy** [comment]
I agree with most of the points you've made, my only reservations are about how the information is presented. Security has this problem of being really complicated. So complicated in fact that if you present newcomers with wholly accurate information and threat models you often overwhelm them and they end up doing nothing.

I think the best path forward would probably be some advanced security/ssh guides that are briefly linked to in the securing your server guide. That is, if Linode is interested in having such guides.

@Jskobos (or anyone from Linode really) If someone were to write such content on advanced SSH security and more sophisticated whitelist based firewalling would Linode be interested?

**Comment by leslitagordita** [comment]
@nixy and @jamesmacwhite thank you for these suggestions.  I have queued this guide to be updated to link to more advanced security topics that already exist in our guides and for a review of more advanced topics we could generate that would address some of the points you've brought up.

**Comment by leslitagordita** [comment]
@nixy I've added PR: linode/docs#1876 which links this guide to our Advanced OpenSSH features guide.
