### ISSUE TITLE
File lunr.json cannot be generated

### ISSUE THREAD

**Issue by sk23** [linode/docs#1806]
It seems ` /docs/themes/docsmith/static/build/lunr.js`  is pre-building with the theme.

And the file generated by `/docs/themes/docsmith/layouts/index.json` has the wrong format.

How can re-build the lunr.js when the docs updated?

Hope to give me some help. Thanks.

**Comment by GuessWhoSamFoo** [comment]
@sk23 Short answer is that lunr.js is internally generated and theme builds are done by maintainers. See 8e601f1dd9e9c40b0ab61ae50d6b51f288ecf15e or 8feddb9a0b67d590f69c6bbac1e718aefb7a42d6

Best way to have this up-to-date is pulling latest commits.

**Comment by sk23** [comment]
@GuessWhoSamFoo What a pity. I would have liked to imitate the Linode docs as a personal website for saving my notes. But I can't solve the search problem because I don't understand javascript.

Thank you for your reply.

**Comment by Jskobos** [comment]
I'd recommend finding a Hugo theme that suits your needs. They have a page for easy search setup, including a Hugo plugin for Lunr.js: https://gohugo.io/tools/search/

**Comment by sk23** [comment]
@Jskobos Maybe this is the simplest way. Thx.
