### ISSUE TITLE
Getting Started with NGINX - Part 1: Installation and Basic Setup Proposed Changes

### ISSUE THREAD

**Issue by ccfreak2k** [linode/docs#1807]
Link: https://linode.com/docs/web-servers/nginx/nginx-installation-and-basic-setup/
## Issue
The page states:
> Changes we want NGINX to apply universally are in the `html` block of `/etc/nginx/nginx.conf`.

## Suggested Fix
> Changes we want NGINX to apply universally are in the `http` block of `/etc/nginx/nginx.conf`.

**Comment by Jskobos** [comment]
@ccfreak2k thanks for the catch.
