### ISSUE TITLE
Is the theme build process documented somewhere?

### ISSUE THREAD

**Issue by kasuboski** [linode/docs#1808]
Is the build process documented somewhere for example, how the static assets are produced?

**Comment by Jskobos** [comment]
We maintain the build pipeline internally, along with our custom Hugo theme. The documentation for these is also kept internal. We make the /docs/ repo, along with the current theme build, publicly available for open-source contributions. This is sufficient to allow anyone to clone the repo, install Hugo, and run a local version of our site.
