### ISSUE TITLE
What is the maximum connection limit for NodeBalancers?

### ISSUE THREAD

**Issue by zengming00** [linode/docs#1815]
![image](https://user-images.githubusercontent.com/5255081/40834174-b4bbcb3e-65c2-11e8-9c40-6b4545feb058.png)
My server connection can no longer be increased. Is it limited to 10k?
And from the figure I don't know why there is a sudden interruption

**Comment by Jskobos** [comment]
Hi, yes the limit for concurrent connections is 10K. Please open a support ticket if you are having any issues, they will be better able to help.
