### ISSUE TITLE
Install NGINX on Ubuntu 18.04 Proposed Changes

### ISSUE THREAD

**Issue by Mustard5** [linode/docs#1823]
Link: https://linode.com/docs/web-servers/nginx/install-nginx-ubuntu/
## Issue

I ran into a problem very early in the process.  I ran `apt install nginx`.  It installed without any errors being reported.  When I went to copy the default configuration file, there were no files at all in `/etc/nginx/conf.d/`
Without a default configuration file, I did not attempt to go any further.

I attempted to join the nginx forum to look for some answers, but they identified my vpn connection with some spam activity, which is unfortunate.  Again, I didn't go any further with jumping through nginx forums hoops to sign up an account.

## Suggested Fix

I would suggest an update the tutorial to reflect any changes that have occurred that would change the location of the default configuration file.  Or identify what might be causing the install process to not include a default configuration file.

**Comment by Guaris** [comment]
Hey -- thanks for pointing this out. We are working on this issue now!

**Comment by Jskobos** [comment]
Addressed by #1824, will update as NGINX mainline support is added. Thanks again!
