### ISSUE TITLE
Update Email with Postfix, Dovecot, and MySQL

### ISSUE THREAD

**Issue by leslitagordita** [linode/docs#1848]

**Comment by FuketsuBaka** [comment]
**7. Create a table for all of the email addresses and passwords:**
If you're going to use something like Rainloop as a front for your mail-server, you may need a non-unique field with username. Rainloop can be set to default domain or even 'guess domain', where you input only username. And here you need a field that will match that username - email without @domain.com.
So we mod query like this:
```
CREATE TABLE `virtual_users` (
  `id` int(11) NOT NULL auto_increment,
  `domain_id` int(11) NOT NULL,
  `password` varchar(106) NOT NULL,
  `email` varchar(100) NOT NULL,
  `user` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
Also, some triggers will be useful on that table. To autofill email field by `domain_id` and `user`.
ON INSERT
```
CREATE TRIGGER `VU_INSERT` BEFORE INSERT ON `virtual_users`
 FOR EACH ROW BEGIN
	DECLARE dom_name VARCHAR(50);
	IF NEW.user <> '' AND NEW.domain_id > 0 THEN
		SELECT vd.name 
			INTO dom_name 
			FROM virtual_domains vd 
        	WHERE NEW.domain_id = vd.id;
		SET NEW.email = CONCAT(NEW.user, '@', dom_name);
   ELSE
   		SET NEW.email = '';
    END IF;
END
```
ON UPDATE
```
CREATE TRIGGER `VU_UPDATE` BEFORE UPDATE ON `virtual_users`
 FOR EACH ROW BEGIN
	DECLARE dom_name VARCHAR(50);
	DECLARE new_email VARCHAR(100);
	IF NEW.user <> '' AND NEW.domain_id > 0 THEN
		SELECT vd.name 
			INTO dom_name 
			FROM virtual_domains vd 
        	WHERE NEW.domain_id = vd.id;
		SET new_email = CONCAT(NEW.user, '@', dom_name);
        IF new_email <> OLD.email THEN
        	SET NEW.email = new_email;
        END IF;
    END IF;
END
```
Yes, email, domain and user cant be NULL, also email is unique, but i prefer to check anyway.
In other way you may just hope for InnoDB to do all the work and just
`SET new_email = CONCAT(NEW.user, '@', (SELECT vd.name FROM virtual_domains vd WHERE  NEW.domain_id = vd.id;));`
-----------------
**2. Edit the**` /etc/postfix/main.cf`
Considering this is a copy-paste guide, better fill smtp-part with more secured options.
```
#
# Authentication
#
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
# Might be useful
smtpd_sasl_security_options = noanonymous
```
Restrictions part
```
#
# Restrictions
#
header_checks = pcre:/vmail/config/header_checks
smtpd_relay_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        defer_unauth_destination
smtpd_helo_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_invalid_helo_hostname,
        reject_non_fqdn_helo_hostname
smtpd_recipient_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_non_fqdn_recipient,
        reject_unknown_recipient_domain,
        reject_unlisted_recipient,
        reject_unauth_destination,
        check_recipient_access hash:/vmail/config/postmap/recipient_access
smtpd_sender_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_non_fqdn_sender,
        reject_unknown_sender_domain,
        check_sender_access hash:/vmail/config/postmap/sender_access
```
For Header-checks.
`apt-get install postfix-pcre`
This is my part, it's optional. As well as the hash:/ parts. 
Example of **recipient_access**.
`root@domain.com REJECT`

And some more options
```
#
# Even more Restrictions and MTA params
#
disable_vrfy_command = yes
strict_rfc821_envelopes = yes
#smtpd_etrn_restrictions = reject
#smtpd_reject_unlisted_sender = yes
#smtpd_reject_unlisted_recipient = yes
smtpd_delay_reject = yes
smtpd_helo_required = yes
smtp_always_send_ehlo = yes
#smtpd_hard_error_limit = 1
smtpd_timeout = 30s
smtp_helo_timeout = 15s
smtp_rcpt_timeout = 15s
smtpd_recipient_limit = 40
minimal_backoff_time = 180s
maximal_backoff_time = 3h
```
Timeout, limit and backoff_time options need to be set as they are too big or too low by default.
VRFY should be disabled to prevent spam-bots check on valid emails.

And finally, some error handling
```
#
# REPLIES
#
invalid_hostname_reject_code = 550
non_fqdn_reject_code = 550
unknown_address_reject_code = 550
unknown_client_reject_code = 550
unknown_hostname_reject_code = 550
unverified_recipient_reject_code = 550
unverified_sender_reject_code = 550
```
-----------------
**12.** `/etc/postfix/master.cf`
chroot is now No by default.
So you should set a `y` for at least a `submisson inet n`.
-----------------
**11. Edit the** `/etc/dovecot/conf.d/auth-sql.conf.ext`
This pasrt should also say to comment default userdb query.
```
#userdb {
#  driver = sql
#  args = /etc/dovecot/dovecot-sql.conf.ext
#}
```
If not commented, you will get an error in your dovecot auth log, cause dovecot will try this query first, fails and only then  will do a static.
-----------------
**12. Update the** `/etc/dovecot/dovecot-sql.conf.ext`
`password_query = SELECT email as user, password FROM virtual_users WHERE (email='%u' OR user='%u');`
As we alter virtual_users  table with user field, we should also check password with just a username provided. This is neccessary then using rainloop's default domain option. Without it authorization won't go.
-----------------
I've repeated the whole guide process and all the rest worked just fine for me.

**Comment by leslitagordita** [comment]
@FuketsuBaka this guide is currently queued to be updated.  Thank you for your suggestions.

**Comment by brentclark** [comment]
Did you test catchalls?
I keep getting:
[private/dovecot-lmtp] said: 550
    5.1.1 <test@DOMAIN> User doesn't exist: test@DOMAIN

**Comment by FuketsuBaka** [comment]
Have you tested SQL-query in dovecot-sql-conf for that user?

**Comment by brentclark** [comment]
Thanks for replying
This is my dovecots query:
password_query = SELECT email as user, password FROM virtual_users WHERE email=(SELECT destination FROM virtual_aliases WHERE source = '%u');

**Comment by brentclark** [comment]
The weird thing is, if I:
root@mail ~ # postmap -q test@REMOVEDDOMAIN mysql:/etc/postfix/mysql-virtual-alias-maps.cf
catchall@REMOVEDDOMAIN

**Comment by FuketsuBaka** [comment]
It is wierd indeed, cause reject on unknown user should be invoked by **postfix/smtp/smtpd**
With the line like:
`Recipient address rejected: User unknown in virtual mailbox table;`
Why it goes to dovecot?

**Comment by brentclark** [comment]
Could I ask if you could please peer review my postfix config?

root@mail ~ # postconf -n
alias_database = hash:/etc/aliases
alias_maps = hash:/etc/aliases
append_dot_mydomain = no
biff = no
bounce_notice_recipient = bounce@REMOVED
compatibility_level = 2
content_filter = scan:127.0.0.1:10026
disable_vrfy_command = yes
header_checks = regexp:/etc/postfix/header_checks
inet_interfaces = all
inet_protocols = ipv4
mailbox_size_limit = 0
maximal_backoff_time = 3h
maximal_queue_lifetime = 7d
mime_header_checks = regexp:/etc/postfix/mime_header_checks
minimal_backoff_time = 180s
mydestination = $myhostname, mail.REMOVED, localhost.localdomain, localhost
myhostname = mail.REMOVED
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
myorigin = /etc/mailname
notify_classes = bounce
readme_directory = no
receive_override_options = no_address_mappings
recipient_delimiter = +
relayhost =
smtp_helo_timeout = 15s
smtp_rcpt_timeout = 15s
smtp_tls_mandatory_protocols = !SSLv2,!SSLv3
smtp_tls_protocols = !SSLv2,!SSLv3
smtp_tls_security_level = may
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
smtpd_delay_reject = yes
smtpd_helo_required = yes
smtpd_helo_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_invalid_hostname, reject_unknown_helo_hostname, reject_invalid_helo_hostname,
smtpd_recipient_limit = 40
smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_invalid_hostname, reject_non_fqdn_hostname, reject_non_fqdn_sender, reject_non_fqdn_recipient, reject_unauth_destination reject_unknown_sender_domain, reject_unknown_recipient_domain, check_policy_service inet:127.0.0.1:10023, permit
smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
smtpd_sasl_auth_enable = yes
smtpd_sasl_path = private/auth
smtpd_sasl_security_options = noanonymous
smtpd_sasl_type = dovecot
smtpd_timeout = 30s
smtpd_tls_CAfile = REMOVED
smtpd_tls_auth_only = no
smtpd_tls_cert_file = REMOVED
smtpd_tls_key_file = REMOVED
smtpd_tls_loglevel = 1
smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3
smtpd_tls_protocols = !SSLv2,!SSLv3
smtpd_tls_received_header = yes
smtpd_tls_security_level = may
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtpd_use_tls = yes
tls_random_source = dev:/dev/urandom
virtual_alias_maps = mysql:/etc/postfix/mysql-virtual-alias-maps.cf, mysql:/etc/postfix/mysql-virtual-email2email.cf
virtual_mailbox_domains = mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
virtual_mailbox_maps = mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
virtual_transport = lmtp:unix:private/dovecot-lmtp

**Comment by FuketsuBaka** [comment]
Are you trying to send from localhost to localhost?
Cause **permit_mynetworks** will skip your recipient checks, it will be allowed by default.
Not sure if **smtpd_reject_unlisted_recipient** will pass this, but anyway - try to get rid of  **permit_mynetworks** in your restrictions. It's unsafe anyway and valid only then you have local net with lazy users who dont want to authenticate.

Here is my example on the subject, which is single-hosted (vps).
```
#
# Restrictions
#
# -------- > 220 mail.example.com ESMTP Postfix
smtpd_client_restrictions =
        check_client_access cidr:/vmail/config/blacklist
#       permit_sasl_authenticated,
#       reject
# -------- > HELO mail.example.com
# -------- > 250 mail.example.com
smtpd_helo_restrictions =
        reject_unknown_hostname,
        reject_non_fqdn_helo_hostname,
        reject_invalid_helo_hostname
# -------- > MAIL FROM:<ned@example.com>
# -------- > 250 2.1.0 Ok
smtpd_sender_restrictions =
        permit_sasl_authenticated,
        reject_unlisted_sender,
        reject_non_fqdn_sender,
        reject_unknown_sender_domain
# -------- > RCPT TO:<ned@example.com>
# -------- > 250 2.1.5 Ok
smtpd_recipient_restrictions =
        reject_non_fqdn_recipient,
        reject_unknown_recipient_domain,
        reject_multi_recipient_bounce,
        sleep 1,
        reject_unauth_pipelining,
        reject_unauth_destination,
        reject_invalid_hostname,
        permit_sasl_authenticated,
        check_sender_access hash:/vmail/config/postmap/sender_access,
        check_recipient_access hash:/vmail/config/postmap/recipient_access,
# -------- > DATA
# -------- > 354 End data with <CR><LF>.<CR><LF>
smtpd_data_restrictions =
        #permit_mynetworks,
        #permit_sasl_authenticated,
        reject_unauth_pipelining,
        reject_multi_recipient_bounce,
#smtpd_end_of_data_restrictions =
#       permit
# -------- > To:<ned@example.com>
# -------- > From:<ned@example.com>
# -------- > Subject:SMTP Test
header_checks = pcre:/vmail/config/header_checks
# -------- > This is a test message
# -------- > .
#body_checks =

#

```

**Comment by brentclark** [comment]
Thanks for replying

No Im not trying to send from localhost to localhost.
I removed permit_mynetworks.
Still not working. I.e I get 
<test@REMOVED>: host mail.REMOVED[private/dovecot-lmtp] said: 550
    5.1.1 <test@REMOVED> User doesn't exist: test@REMOVED (in reply
    to RCPT TO command)

Should I not be commenting out to get catchall working:
alias_database = hash:/etc/aliases
alias_maps = hash:/etc/aliases

root@mail ~ # postconf -n
alias_database = hash:/etc/aliases
alias_maps = hash:/etc/aliases
append_dot_mydomain = no
biff = no
bounce_notice_recipient = bounce@REMOVED
compatibility_level = 2
content_filter = scan:127.0.0.1:10026
disable_vrfy_command = yes
header_checks = regexp:/etc/postfix/header_checks
inet_interfaces = all
inet_protocols = ipv4
mailbox_size_limit = 0
maximal_backoff_time = 3h
maximal_queue_lifetime = 7d
mime_header_checks = regexp:/etc/postfix/mime_header_checks
minimal_backoff_time = 180s
mydestination = $myhostname, mail.REMOVED, localhost.localdomain, localhost
myhostname = mail.REMOVED
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
myorigin = /etc/mailname
notify_classes = bounce
readme_directory = no
receive_override_options = no_address_mappings
recipient_delimiter = +
relayhost =
smtp_helo_timeout = 15s
smtp_rcpt_timeout = 15s
smtp_tls_mandatory_protocols = !SSLv2,!SSLv3
smtp_tls_protocols = !SSLv2,!SSLv3
smtp_tls_security_level = may
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
smtpd_delay_reject = yes
smtpd_helo_required = yes
smtpd_helo_restrictions = permit_sasl_authenticated, reject_invalid_hostname, reject_unknown_helo_hostname, reject_non_fqdn_helo_hostname, reject_invalid_helo_hostname,
smtpd_recipient_limit = 40
smtpd_recipient_restrictions = permit_sasl_authenticated, reject_invalid_hostname, reject_non_fqdn_hostname, reject_non_fqdn_sender, reject_non_fqdn_recipient, reject_unauth_destination reject_unknown_sender_domain, reject_unknown_recipient_domain, check_policy_service inet:127.0.0.1:10023, permit
smtpd_relay_restrictions = permit_sasl_authenticated, defer_unauth_destination
smtpd_sasl_auth_enable = yes
smtpd_sasl_path = private/auth
smtpd_sasl_security_options = noanonymous
smtpd_sasl_type = dovecot
smtpd_timeout = 30s
smtpd_tls_CAfile = /opt/intermediate.crt
smtpd_tls_auth_only = no
smtpd_tls_cert_file = /opt/public.crt
smtpd_tls_key_file = /opt/private.key
smtpd_tls_loglevel = 1
smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3
smtpd_tls_protocols = !SSLv2,!SSLv3
smtpd_tls_received_header = yes
smtpd_tls_security_level = may
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtpd_use_tls = yes
tls_random_source = dev:/dev/urandom
virtual_alias_maps = mysql:/etc/postfix/mysql-virtual-alias-maps.cf, mysql:/etc/postfix/mysql-virtual-email2email.cf
virtual_mailbox_domains = mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
virtual_mailbox_maps = mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
virtual_transport = lmtp:unix:private/dovecot-lmtp

**Comment by brentclark** [comment]
I figured it out
Its the clamscan options of

content_filter = scan:127.0.0.1:10026
receive_override_options = no_address_mappings

**Comment by brentclark** [comment]
I googled "postfix receive_override_options catchall"

And I came across this page, to confirm my suspicion:
 https://serverfault.com/questions/536656/postfix-dovecot-catchall-doesnt-work-any-more

**Comment by FuketsuBaka** [comment]
Noted. Thx for feedback.

**Comment by andystevensname** [comment]
@FuketsuBaka, I'm in the process of trying to test your suggestions for this guide, but I'm having an issue with the triggers you suggested. I keep running into an error:

    mysql> CREATE TRIGGER `VU_INSERT` BEFORE INSERT ON `virtual_users`
        -> FOR EACH ROW BEGIN
        -> DECLARE dom_name VARCHAR(50);
    ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

Do you have any insight into why this might be happening? I am using MySQL version 5.7.24.

**Comment by FuketsuBaka** [comment]
Hello, You started a cycle but never end it.

OR EACH ROW BEGIN
   DECLARE dom_name VARCHAR(50);

END


чт, 3 янв. 2019 г. в 20:38, Andy Stevens <notifications@github.com>:

**Comment by andystevensname** [comment]
@FuketsuBake,

Thank you for your suggestions and your help with the delimiter problem. We have accepted most of your suggestions and will incorporate them in the next release. However, we have chosen not to include the suggestions pertaining to user fields and RainLoop support, thinking that those suggestions would be worthy of their own guide. Would you be interested in writing a guide for us on using Postfix/Dovecot and RainLoop? We would pay you for such a guide. If you're interested, please contact me here or at astevens@linode.com.
