### ISSUE TITLE
Install and Configure OSSEC on Debian 7 Proposed Changes

### ISSUE THREAD

**Issue by lzkelley** [linode/docs#1856]
Link: https://linode.com/docs/uptime/monitoring/ossec-ids-debian-7/

## Issue
- the `wget -U <URL>` syntax fails with a `wget: missing URL`
- Using `wget -O <FILENAME> <URL>` The checksums and the downloaded files don't match up:

```
$ md5sum -c ossec-vm-2.8.3-checksum.txt
md5sum: ossec-vm-2.8.3.ova: No such file or directory
ossec-vm-2.8.3.ova: FAILED open or read
md5sum: WARNING: 1 line is improperly formatted
md5sum: WARNING: 1 listed file could not be read
```

**Comment by leslitagordita** [comment]
@lzkelley Thank you for this information.  We have this guide queued to be updated for Debian 9 and will address this issue within that work.
