### ISSUE TITLE
Add CAA Records in the Linode Manager Proposed Changes

### ISSUE THREAD

**Issue by alexfornuto** [linode/docs#1857]
Link: https://linode.com/docs/quick-answers/linode-platform/add-caa-dns-records/
## Issue
>The Default selection’s TTL is 300 seconds, which is fine for most cases.

I just tested and confirmed that the default TTL is 24 hours:

```
 $ dig @ns1.linode.com +answer dummytest.party

...

;; ANSWER SECTION:
dummytest.party.	86400	IN	A	198.74.62.182

...
```

You can look at my account to verify that I left the values at **Default** for the zone `dummytest.party`.

## Suggested Fix

Update the value of default listed in this and any other doc.

**Comment by leslitagordita** [comment]
Tested this issue and can confirm that default TTL is 300 seconds.
