### ISSUE TITLE
Set Up DNS Services on cPanel Proposed Changes

### ISSUE THREAD

**Issue by broros** [linode/docs#1924]
Link: https://linode.com/docs/websites/cms/set-up-dns-services-on-cpanel/
## Issue

DNS servers responded 
ERROR: One or more of your nameservers did not respond:The ones that did not respond are:162.159.27.72 162.159.26.99 162.159.24.25 162.159.24.39 162.159.25.129

**Comment by Guaris** [comment]
Hey! We are going to assess this issue and update the guide! Thanks for bringing this up to us!

**Comment by andystevensname** [comment]
Hi @broros, if you could please give us more information about the error we might have a better chance of helping you. Did this error occur when you ran `named-checkconf /etc/named.conf`? What OS are you using?
