### ISSUE TITLE
Use Public Key Authentication with SSH Proposed Changes

### ISSUE THREAD

**Issue by abaggerman** [linode/docs#1925]
Link: https://linode.com/docs/security/authentication/use-public-key-authentication-with-ssh/
## Suggested Fix
What is missing from this tutorial is that the following permissions need to be set:
chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys
on both sides.
Without it the connection will just ask for a password instead of the passphrase.

**Comment by Guaris** [comment]
Hey thanks! We are going to add this change next week. Feel free to add the change in and make a PR.

**Comment by cwlinode** [comment]
Added in https://github.com/linode/docs/pull/1978
