### ISSUE TITLE
Install Let's Encrypt to Create SSL Certificates Proposed Changes

### ISSUE THREAD

**Issue by SarahGran** [linode/docs#1932]
Link: https://linode.com/docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates/
## Issue
Let's Encrypt does provide wildcard certificates 
https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by andystevensname** [comment]
@SarahGran Thank you for pointing this out to us. We have updated the guide and will include it in our next release.
