### ISSUE TITLE
SSH Connections Using PuTTY on Windows Proposed Changes

### ISSUE THREAD

**Issue by infoseek1** [linode/docs#1938]
Link: https://linode.com/docs/networking/ssh/ssh-connections-using-putty-on-windows/
## Issue
Blank server name
## Suggested Fix
Should have example ip in there  or cool video like you do for the Mac version

**Comment by Guaris** [comment]
Hey that's a good idea. I don't really know when we can get to it, we don't have any access to Windows machines here. But I just wanted to let you know that we haven't forgotten.

**Comment by cwlinode** [comment]
Added in: https://github.com/linode/docs/pull/1978

**Comment by cwlinode** [comment]
Added in https://github.com/linode/docs/pull/1978
