### ISSUE TITLE
Email with Postfix, Dovecot, and MySQL Proposed Changes

### ISSUE THREAD

**Issue by samuelgunawan** [linode/docs#1989]
Link: https://linode.com/docs/email/postfix/email-with-postfix-dovecot-and-mysql/
## Issue
ENCRYPT() deprecated in MySQL 8.0
## Suggested Fix
https://stackoverflow.com/questions/51420805/dovecot-password-hashing-with-mysql-8-sha2

**Comment by Guaris** [comment]
XR: https://github.com/linode/docs/pull/2076
