### ISSUE TITLE
Documentation isn't using standard example IP addresses.

### ISSUE THREAD

**Issue by alexfornuto** [linode/docs#2003]
For example, in the Getting Started doc:

>To reconnect via SSH, revoke the key for that IP address.
>
>For Linux and Mac OS X:
>
> `ssh-keygen -R 123.45.67.89`
>

**Resolution**

See [RFC 5737](https://tools.ietf.org/html/rfc5737) for the IP ranges and domains reserved for documentation.

**Comment by Guaris** [comment]
Leaving this open while we work on standardizing IP addresses across our guides.

**Comment by hyshka** [comment]
@Guaris Has there been a consensus on the IP address formatting? Are you going with the `198.51.100.4` format everywhere?

I can put together a PR for this to get something changed across the board.

**Comment by Guaris** [comment]
@hyshka Is this something you are still interested in doing. It seems like a huge task.

**Comment by hyshka** [comment]
Hey @Guaris I'm definitely interested in contributing but I think I'd need some guidance. The RFC is pretty straight forward in it's recommendations, I would suggest using these three in the priority they are stated if multiple IPs are needed in a single example.

```
The blocks 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2), and 203.0.113.0/24 (TEST-NET-3) are provided for use in documentation.
```

There are also RFCs related to IPv6 addresses ([RFC3849](https://tools.ietf.org/html/rfc3849)) and domain names ([RFC2606](https://tools.ietf.org/html/rfc2606)). Do you think these are something we'd need to address as well?

There are a tonne of pages in the Linode docs so this would be a large task. My first step would be identifying the numbers of pages that would need to be modified and then automate as much as possible, although I may need to recruit some help.

**Comment by alexfornuto** [comment]
`(.+?).(.+?).(.+?).(.+?) ` for all IP addresses. You can modify to look for public/private addresses, or specific examples to be excluded. All in all, this shouldn't take more than an hour.

**Comment by Guaris** [comment]
> `(.+?).(.+?).(.+?).(.+?) ` for all IP addresses. You can modify to look for public/private addresses, or specific examples to be excluded. All in all, this shouldn't take more than an hour.

I think it would take that long as well. We can review internally or even work together to do it. I think it may be interesting to enforce this through Vale, or Blueberry (our testing suite). What do you think @alexfornuto

**Comment by hyshka** [comment]
Thanks for your comments. I'll take a look at this and get started with IPv4 addresses.

**Comment by wildmanonline** [comment]
We've added guidance within our writer's formatting guide and are updating IP addresses when guides are updated. https://www.linode.com/docs/guides/linode-writers-formatting-guide/#example-ip-addresses
