### ISSUE TITLE
Getting Started with NGINX - Part 2: (Slightly More) Advanced Configurations Proposed Changes

### ISSUE THREAD

**Issue by yufengchen02** [linode/docs#2008]
Link: https://linode.com/docs/web-servers/nginx/slightly-more-advanced-configurations-for-nginx/
## Issue
 **"Before You Begin" section:**

> You may want to make another backup of your nginx.conf so you have a snapshot of the work you’ve done up to this point:
> 
> cp etc/nginx/nginx.conf etc/nginx/nginx.conf.backup-pt2

I think there are two forward-slashes missing in the two paths before "etc".

## Suggested Fix

The command should be
> cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup-pt2

**Comment by cwlinode** [comment]
Thanks for the heads up. Fixed in https://github.com/linode/docs/pull/2039.
