### ISSUE TITLE
404 error when viewing apache status on lynx

### ISSUE THREAD

**Issue by jcgallaher** [linode/docs#201]
I followed along in the article to setup the Apache server status. https://www.linode.com/docs/websites/apache-tips-and-tricks/tuning-your-apache-server

When I run the command ```lynx http://localhost/server-status``` I get a 404 not found error

Below is a copy of conf file that I edited. (FYI, I've omitted sensitive information with my-website)
```
# domain: my-website.com
# public: /var/www/my-website.com/public_html/

<VirtualHost *:80>
  # Admin email, Server Name (domain name), and any aliases
  ServerAdmin admin@email.com
  ServerName  www.my-website.com
  ServerAlias my-website.com

  # Index file and Document Root (where the public files are located)
  DirectoryIndex index.html index.php
  DocumentRoot /var/www/my-website.com/public_html
  # Log file locations
  LogLevel warn
  ErrorLog  /var/www/my-website.com/log/error.log
  CustomLog /var/www/my-website/log/access.log combined

<Location /server-status>
SetHandler server-status
Order Deny,Allow
Deny from all
Allow from localhost
</Location>
</VirtualHost>

**Comment by ravenx99** [comment]
Is mod_status enabled?  'a2enmod mod_status'

I'm pretty sure that when I've used mod_status, the Location directive wasn't inside a virtual host block, but at a higher level.  On Debian, that'd be in /etc/apache2/httpd.conf.  That works in my configuration (which I tested just now).

"localhost" doesn't match the defined ServerName / ServerAlias in your virtual block.  You could probably create a virtual block for "localhost", or add "localhost" as another alias.  Not sure which is the "right" way.

**Comment by jcgallaher** [comment]
Hi ravenx99, I don't see a httpd.conf file, but I do have apache2.conf which I used when I first setup the server. I searched in there for mod_status but nothing came up. I'm not sure if I have to add in?

**Comment by FelicianoTech** [comment]
You can run `sudo a2enmod status` to ensure that mod_status is enabled.

If you're running multiple vhost, this is likely causing the problem. Typically on my personal machines I make a separate vhost just for localhost that I use to serve internal pages for various purposes. If you were to do that and place the Location block in there, restarting Apache should do the trick.

**Comment by jcgallaher** [comment]
Thanks FelicianoTech, Mod status is enabled. Do you make a separate vhost just like you would add another website to your server? I'm in the learning phase lol

**Comment by FelicianoTech** [comment]
Yes. On my Ubuntu server I have /etc/apache2/sites-available/000-localhost.conf This is where I keep stuff like this and then enable it via `sudo a2ensite 000-localhost`.

**Comment by jcgallaher** [comment]
Thanks FelicianoTech!

**Comment by alexfornuto** [comment]
@jcgallaher does this solve the issue?

**Comment by jcgallaher** [comment]
I haven't tried it, but I believe it will so I'll close the issue. Thanks! :-)
