### ISSUE TITLE
How to Install Mastodon on Ubuntu 16.04 Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#2024]
Link: https://linode.com/docs/applications/messaging/install-mastodon-on-ubuntu-1604/
## Issue

```
Check that the installation was successful by running the built-in “Hello World” program:
*docker run hello-world*
```
I got a permission denied message when trying to run this:

```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'. 
```

## Suggested Fix

I reran it with sudo and it worked out just fine.

**Comment by Guaris** [comment]
Did you restart the shell instance?

That's a very common docker permissions error that usually means you haven't added your user to the Docker group. Running Docker w/ Sudo is not recommended. Closing this for now, but let me know if it is still an issue.
