### ISSUE TITLE
Interest in a discourse setup documentation?

### ISSUE THREAD

**Issue by josefnpat** [linode/docs#205]
I do not have any experience setting up [discourse](http://www.discourse.org/), but I do have a great interest and a lot of experience setting up and working on linux servers.

A lot of time time, I enjoy writing documentation as I perform setup.

I noticed that linode was willing to pay folks to write documentation [here](https://blog.linode.com/2014/01/16/write-for-linode-get-paid/).

Would linode like me to write documentation on how to set up a node for discourse?

**Comment by alexfornuto** [comment]
Hello @josefnpat,

Thanks for your interest. Discourse seems like a fine enough subject to write a guide about, but we can't accept an article until we can see it and determine if it meets our requirements. 

If you're going to be installing it anyway, I say you write down the steps as you go, and then turn it into a tutorial and submit it as a PR. 

Thanks!

**Comment by josefnpat** [comment]
Ok, neat. I just want to make sure that someone hasn't done it already :)
