### ISSUE TITLE
Updates for: How to Set Up a Minecraft Server on Ubuntu or Debian guide

### ISSUE THREAD

**Issue by jcgallaher** [linode/docs#2050]
Good morning, Minecraft was recently updated to version 1.13.1. Also they made a change to their file naming convention. Now instead of downloading a file named `minecraft_server.1.13.1.jar` you just get `server.jar`.

Lastly as a suggestion, the run.sh could be cleaned up to be:
```
#!/bin/bash

java -Xms1024M -Xmx2048M -jar minecraft_server.1.13.jar -o true
```

**Comment by andystevensname** [comment]
Thank you for the update! This was addressed in PR #2094.
