### ISSUE TITLE
How to Secure Your Server Proposed Changes

### ISSUE THREAD

**Issue by ghost** [linode/docs#2051]
Link: https://linode.com/docs/security/securing-your-server/
## Issue
Video is great by why does the text have to be so super small?  Or what does the terminal size have to so big and wide.  There is a lot of unused space that could be wisely used up by a bigger font. 

## Suggested Fix
Shoot all videos with large fonts so that the commands can be seen by users (me) and so the commands take up most of the terminal window.  Thank you.

**Comment by Guaris** [comment]
Hey Ghost, we are currently working on some videos and will keep your comment in the forefront of our minds!
