### ISSUE TITLE
Getting Started with Linode Proposed Changes

### ISSUE THREAD

**Issue by kodumbeats** [linode/docs#2062]
Link: https://linode.com/docs/getting-started/
## Issue

Guide outlines Fedora setup but does not include the command to set the timezone in Fedora.

## Suggested Fix

Fedora uses timedatectl like Arch and CentOS, so update the title to Arch Linux/CentOS 7/Fedora

**Comment by cwlinode** [comment]
Thank you. Fixed in https://github.com/linode/docs/pull/2088.
