### ISSUE TITLE
Running a Mail Server Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#2063]
Link: https://www.linode.com/docs/email/running-a-mail-server/#reverse-dns
## Issue

The link for Reverse DNS is incorrect

## Suggested Fix

It should be: https://www.linode.com/docs/networking/dns/configure-your-linode-for-reverse-dns/

**Comment by cwlinode** [comment]
Thank you. Fixed in https://github.com/linode/docs/pull/2088
