### ISSUE TITLE
Install a LEMP Stack on Ubuntu 18.04 Proposed Changes

### ISSUE THREAD

**Issue by greyblocus** [linode/docs#2066]
Link: https://linode.com/docs/web-servers/lemp/how-to-install-a-lemp-server-on-ubuntu-18-04/
## Issue
 
Typo In

`sudo ln -s /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/`

## Suggested Fix

should be:

`sudo ln -s /etc/nginx/sites-available/example.com.conf /etc/nginx/sites-enabled/`

**Comment by mevrouwdevries** [comment]
I'll fix that up.

**Comment by cwlinode** [comment]
Thank you. Fixed in https://github.com/linode/docs/pull/2088
