### ISSUE TITLE
Dovecot with MySQL

### ISSUE THREAD

**Issue by nsteinmetz** [linode/docs#209]
Hello,

In the dovecot/mysql tutorial (https://www.linode.com/docs/email/postfix/email-with-postfix-dovecot-and-mysql), I may be wrong but I have an issue.

In the dovecot section, it is said at step 11, that permissions are to be root:mail

    11. Verify that the permissions for */var/mail* are as follows:
    drwxrwsr-x 2 root mail 4096 Mar  6 15:08 /var/mail

But on step 14, it changes to vmail:vmail 

    14. Change the owner of the */var/mail/* folder and its contents to belong to `vmail` by entering the  following command:
    chown -R vmail:vmail /var/mail

So either step 11 is not required and should be only step 14 but if this is the case, shouldnt the value of mail_priviledged_group be "vmail" instead of "mail" at step 8 ?

    mail_privileged_group = mail

So far, I only report it as is ; when going further and making my own tests, I will review it and if needed do some PR.

Thanks,
Nicolas

**Comment by thetechstewart** [comment]
@nsteinmetz Thanks for bringing this to our attention.  The guide in question is actually undergoing a rather significant overhaul to address some issues, I'll be sure to add this to the list for further testing.

**Comment by nsteinmetz** [comment]
If you need me to test the new tutorial, let me know as I'm on the way to set my mail server ; right now, only testing one, once I'm done with ansible, it will be on production too ;-)

**Comment by nsteinmetz** [comment]
On same way, seems a little bit weird to add vmail as owner but to remove rights for step 30 & 31

    chown -R vmail:dovecot /etc/dovecot
    [...]
    chmod -R o-rwx /etc/dovecot

**Comment by Alexhha** [comment]
> The version of Postfix included in the main CentOS repository does not include support for MariaDB

it's incorrect

```
# ldd /usr/libexec/postfix/smtpd | grep sql
        libmysqlclient.so.18 => /usr/lib64/mysql/libmysqlclient.so.18 (0x00007ff2a345f000)

# rpm -qf /usr/lib64/mysql/libmysqlclient.so.18
mariadb-libs-5.5.44-2.el7.centos.x86_64

# postconf -m | grep mysql
mysql
```

OS info
```
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core)
Release:        7.2.1511
Codename:       Core

# yum list installed | grep postfix
postfix.x86_64                       2:2.10.1-6.el7                    @base
```

**Comment by alexfornuto** [comment]
I believe both issues here were resolved when these guides were updated. If not, let us know.
