### ISSUE TITLE
How to Install a LAMP Stack on Ubuntu 16.04 Proposed Changes

### ISSUE THREAD

**Issue by abalarin** [linode/docs#2127]
Link: https://www.linode.com/docs/web-servers/lamp/install-lamp-stack-on-ubuntu-16-04/#php-7-0# Issue: PHP 7.0 possibly outdated
When running cmd:
```sudo apt install php7.0 libapache2-mod-php7.0 php7.0-mysql```
E: Couldnt find any packages

## Suggested Fix
Update to PHP 7.2:
```sudo apt install php7.2 libapache2-mod-php7.2 php7.2-mysql```

**Comment by Guaris** [comment]
Thanks for reporting this! I'll be sure to add it to the guide!

**Comment by andystevensname** [comment]
@abalarin I was not able to replicate the error you posted using Ubuntu 16.04 and PHP 7.0. Is there a chance that you were using Ubuntu 18.04?

**Comment by abalarin** [comment]
@andystevensname Yeah I think I may have been using another version of Ubuntu. Just tried to replicate the error using Ubuntu 16.04 and couldn't.
