### ISSUE TITLE
Use Terraform to Provision Linode Environments Proposed Changes

### ISSUE THREAD

**Issue by boxed** [linode/docs#2135]
Link: https://linode.com/docs/applications/configuration-management/how-to-build-your-infrastructure-using-terraform-and-linode/
## Issue
Installation description on mac should suggest homebrew.

## Suggested Fix
"Or if you're on macOS, use homebrew: `brew install terraform`" and skip to #building-with-the-linode-provider"

**Comment by andystevensname** [comment]
Thanks for the suggestion, we'll include the changes in our next release.
