### ISSUE TITLE
How to Use Block Storage with Your Linode Proposed Changes

### ISSUE THREAD

**Issue by aaronraimist** [linode/docs#2139]
Link: https://linode.com/docs/platform/block-storage/how-to-use-block-storage-with-your-linode-new-manager/
## Issue

When you detach a block storage volume, don't you also need to manually remove the line you added to `/etc/fstab`? Otherwise the server will boot into emergency mode.

**Comment by Guaris** [comment]
Hey! Thanks for pointing this out. The PR is staged to be merged: #2146
