### ISSUE TITLE
Manage OpenVPN with OpenVPN Access Server Proposed Changes

### ISSUE THREAD

**Issue by cole8888** [linode/docs#2179]
Link: https://linode.com/docs/networking/vpn/install-openvpn-access-server-on-linux/
## Issue
IP address is still legible in Windows client software installation screenshots (especially in the last photo of that section). My friend was even able to ping it.
## Suggested Fix
Properly block out the address and avoid using blurring in that manner.

**Comment by Guaris** [comment]
Hey thanks! We are going to fix this in our next release cycle.

**Comment by leslitagordita** [comment]
Hello @cole8888 https://github.com/linode/docs/pull/2207 has been submitted to address this issue and will be merged in the next release. Thanks!
