### ISSUE TITLE
How to Configure NGINX Proposed Changes

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [linode/docs#2181]
Link: https://linode.com/docs/web-servers/nginx/how-to-configure-nginx/
## Issue
In the "Directives, Blocks, and Contexts" section -> in 4th paragraph, it says

The file starts with 5 directives: user, worker_processes, error_log, and pid. 

However, the above list only contains 4 directives. Is there a directive missing or should it say

The file starts with 4 directives: user, worker_processes, error_log, and pid. 

## Suggested Fix
Make the number of directives consistent.

**Comment by cwlinode** [comment]
Fixed. Thank you.
