### ISSUE TITLE
Dovecot error

### ISSUE THREAD

**Issue by mametz** [linode/docs#220]
I'm getting the following error following your guide:
auth: Error: Can't open configuration file uid=vmail gid=vmail home=/var/mail/vhosts/%d/%n: No such file or directory

What could be the issue?

**Comment by thetechstewart** [comment]
@mametz: Could you confirm at which step of the guide you are encountering this error message?

**Comment by mametz** [comment]
At the very end.

**Comment by alexfornuto** [comment]
Please post the exact command you're running, and the exact output. More specifics makes it easier to help. Ambiguity leads nowhere.

**Comment by tknarr** [comment]
Looks like it's the "args = " line in the static userdb section of auth-sql.conf.ext. I'll bet from the error he didn't set "driver = static" and whatever driver he's using is looking for a filename instead of static's uid/gid/home settines.

**Comment by doomsbuster** [comment]
@tknarr Thank, you saved my day. I faced similar error, i had a misconfiguration during my migrating my mail server. Changing driver = static fixed this error.

**Comment by diprajpatra** [comment]
@tknarr  you won the bet!! Thank, you saved my day.

**Comment by ccc-daniel** [comment]
@tknarr Oh my god! really appreciate!. thanks a lot man
