### ISSUE TITLE
An Overview of IPv6 on Linode Proposed Changes

### ISSUE THREAD

**Issue by abalarin** [linode/docs#2208]
Link: https://linode.com/docs/networking/an-overview-of-ipv6-on-linode/
## Issue
At [more-information](https://www.linode.com/docs/networking/an-overview-of-ipv6-on-linode/#more-information) this [IPv6 Cheat Sheet Link](http://www.ipv6ve.info/project-definition/ipv6-subnet-cheat-sheet-and-ipv6-cheat-sheet-reference) seems to be broken.

## Suggested Fix
You might be referring to [this IPv6 chart](https://www.ripe.net/support/training/material/lir-training-course/LIR-Training-Handbook-Appendices/IPv6Chart_2015.pdf)  located in this [HE IP guide](https://www.ripe.net/about-us/press-centre/understanding-ip-addressing)

But it could also be that HE just deprecated the cheat sheet altogether.

**Comment by nmelehan** [comment]
Hello -

Thank you for noticing this issue. I'm not sure what the original cheat sheet linked to was, so I replaced the link with the IPv6 chart:

https://github.com/linode/docs/pull/2219

This PR should be merged soon, and I'll close this issue now. Thanks again!
