### ISSUE TITLE
Pritunl VPN Server and Management Panel on Ubuntu 14.04 Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#2213]
Link: https://linode.com/docs/networking/vpn/pritunl-vpn-ubuntu/
## Issue
When I run this command:

`sudo apt-get install python-software-properties pritunl mongodb-org`

I'm receiving an error message that reads:

```root@ubuntu:~# sudo apt-get install python-software-properties pritunl mongodb-org
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pritunl```

I searched for this package on Ubuntu's website and not seeing anything related to `pritunl`


## Suggested Fix

I found instructions on Pritunl's website for Ubuntu 16.04 & 18.04: https://docs.pritunl.com/docs/installation

**Comment by Wat-Poods** [comment]
Digging into this more, I found an error a couple steps prior. To replicate:

I ran these steps:
- `echo "deb http://repo.pritunl.com/stable/apt trusty main" > /etc/apt/sources.list.d/pritunl.list`
- ...
- apt-get-update
- found these errors:

```Err:6 http://repo.pritunl.com/stable/apt/pool/main/p trusty Release
  404  Not Found [IP: 2606:4700:30::681c:1205 80]```
...
```Reading package lists... Done
E: The repository 'http://repo.pritunl.com/stable/apt/pool/main/p trusty Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.```

I think it's not an issue with the doc, but more with the location of the package itself

**Comment by Wat-Poods** [comment]
further investigation: there's no `trusty` package anymore. Only `bionic` & `xenial`: https://docs.pritunl.com/docs/installation

**Comment by nmelehan** [comment]
Hi @Wat-Poods -

Thank you for doing this research; it looks like we need to deprecate this guide, which I have done in #2218. I'm not sure if we will publish a new version targeting the currently supported versions of Ubuntu, but I'll add a to-do item to our work list to discuss that, and I'll close this issue for now. Thanks again!
