### ISSUE TITLE
Install cPanel on CentOS Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#2227]
Link: https://linode.com/docs/websites/cms/install-cpanel-on-centos/
## Issue

```Before proceeding, make sure you’ve purchased a cPanel license. You may obtain a license from the cPanel Store.```

This links to a page that returns a 403 error

## Suggested Fix

Link to [https://www.cpanel.net/pricing/](https://www.cpanel.net/pricing/)

**Comment by Guaris** [comment]
@Wat-Poods https://github.com/linode/docs/pull/2228

Thanks for catching this!
