### ISSUE TITLE
Docker guides do not mention custom kernel

### ISSUE THREAD

**Issue by gandalfar** [linode/docs#224]
If you try to install docker on Debian 8, you get a warning and no clear way how to fix this:

		root@debian:~# wget -qO- https://get.docker.com/ | sh
		modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.0.2-x86_64-linode56/modules.dep.bin'
		Warning: current kernel is not supported by the linux-image-extra-virtual
		 package.  We have no AUFS support.  Consider installing the packages
		 linux-image-virtual kernel and linux-image-extra-virtual for AUFS support.
		+ sleep 10

The solution is to use pv-grub and non-linode, but it took me a while to google that in random places. It would be nice if official tutorial mentioned this somewhere.

The one I'm looking is https://www.linode.com/docs/applications/containers/linode-lamp-container-docker and that command is step 1 and it says it should work with Debian.

**Comment by thetechstewart** [comment]
@gandalfar:  Linode kernels don't have AUFS support enabled, however after halting on that warning for 10 seconds, it should install using devicemapper.  If you prefer to utilize AUFS, using a distribution supplied or custom kernel is the best route.  It looks like this warning was recently added to Docker's configuration script.

I'll add a note to the relevant guides with a similar explanation.
