### ISSUE TITLE
Set Up WireGuard VPN on Ubuntu Proposed Changes

### ISSUE THREAD

**Issue by UltraBob** [linode/docs#2247]
Link: https://linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/
## Issue
No Reasoning is given for changing the Kernel.  This is a big and disruptive change, if the node is already in use.
## Suggested Fix
Provide reasoning for why this is necessary, and a better link for setting up after the change is made to take into account more than the case of a brand new node.

**Comment by Rajakavitha1** [comment]
@UltraBob 

There is a note about why the change and the links to relevant guides.
Note
The GRUB 2 kernel is required for this guide. All distributions for all new Linodes now boot with the GRUB 2 kernel by default. However, if you are running an older distribution, you will need to check to see which kernel you are running. You can use the Update Kernel Guide to check your kernel version and change it using the Cloud Manager. Select GRUB 2 from the Boot Settings: Select a Kernel dropdown menu in Step 4 of Update Your Linode Kernel with Linode’s Cloud Manager.

Hence, marking this a closed. Please feel free to reopen if any other changes need to be made.
