### ISSUE TITLE
Back Up Your PostgreSQL Database gives invalid advice

### ISSUE THREAD

**Issue by aaronraimist** [linode/docs#2253]
#2130 was supposed to fix the info but didn't actually address the problem. Doesn't that whole note about `-1` need to be removed?
https://github.com/linode/docs/pull/2130/files#diff-84460e5b5f27a2945013c8d1ebe332b1R62

**Comment by Guaris** [comment]
Hey @aaronraimist what do you think about #2266 ?

**Comment by aaronraimist** [comment]
👍 I’m not a Postgres expert but as far as I know that is correct

**Comment by Guaris** [comment]
Thanks!
