### ISSUE TITLE
DNS Manager Proposed Changes

### ISSUE THREAD

**Issue by CoreyMSchafer** [linode/docs#2257]
Link: https://linode.com/docs/platform/manager/dns-manager-new-manager/
## Suggested Fix
Hi There,
Your documentation for the new Cloud Linode manager is great; however, on step number 4 of the DNS Set-Up Checklist, you are linking to a page "Set Reverse DNS". This links to documentation for your old Linode Manager. It doesn't show you how to set the reverse DNS with the new Cloud Linode Manager. I figured it out myself by doing the following:
Linodes > Clicking on your Linode > Networking > Clicking the additional settings beside the IP > Edit RDNS

If there is documentation that exists for how to set the reverse DNS on the new Cloud manager then I would set that link to step number 4 in this documentation.

Cheers.

**Comment by Guaris** [comment]
Hey Corey, we are actually set to update the doc. We noticed that in your video! Thanks for submitting the issue, i'll update you when it's fixed!

**Comment by Rajakavitha1** [comment]
Thanks @CoreyMSchaferr!!! The step 4 now inks to: https://www.linode.com/docs/networking/dns/configure-your-linode-for-reverse-dns/
