### ISSUE TITLE
Linode CLI showing JSON-only output for 'linode-cli linodes ips-list ..'

### ISSUE THREAD

**Issue by erco77** [linode/docs#2297]
Link: https://linode.com/docs/platform/api/using-the-linode-cli/
## Issue

The command:
    linode-cli linodes ips-list $linode_id
..seems to show json only output. A 'nice' header is printed, but the content is JSON.
Even with the --text flag, the content is JSON-only.

## Suggested Fix
Not sure, just reporting the problem.

**Comment by Guaris** [comment]
Thank you!
