### ISSUE TITLE
Install SquirrelMail on Ubuntu 16.04 or Debian 8 Proposed Changes

### ISSUE THREAD

**Issue by neekfenwick** [linode/docs#2300]
Link: https://linode.com/docs/email/clients/install-squirrelmail-on-ubuntu-16-04-or-debian-8/
## Issue
Going through this guide on Centos 7 today I found details of the current squirrelmail to be different and the selinux config needed updating.  Perhaps the selinux issue would not happen on latest Ubuntu.

## Suggested Fix
Squirrelmail configure script was:
/usr/share/squirrelmail/config/conf.pl

I also had to set:
setsebool -P httpd_can_network_connect=1

Without this, squirrelmail shows "13: Permission Denied" when trying to log on.

Thank you for the great guides :)

**Comment by fianbiasa** [comment]
never answered by Linode ?

**Comment by Rajakavitha1** [comment]
Hi @neekfenwick ,
Thank you for the feedback. I tried the guide on ubuntu 16.04 and there were no issues.
Closing this issue for now. However, please feel free to reopen if there are any other issues.
