### ISSUE TITLE
mention that Linode images don't work with raw disks

### ISSUE THREAD

**Issue by nabrewer** [linode/docs#2324]
the Linode image service cannot capture raw disks, as it needs to be able to mount the disk. I noticed Images were added as a suggestion to the custom distro guide - it could possibly be added to the list of EXT-specific functionality [here](https://www.linode.com/docs/tools-reference/custom-kernels-distros/install-a-custom-distribution-on-a-linode/#linode-manager-compatibility), but it might also be useful to explain this caveat on the Images overview as well.

**Comment by nabrewer** [comment]
err, I used the wrong account to open this @brewn

**Comment by wildmanonline** [comment]
This has been open a while! The [Images](https://www.linode.com/docs/products/tools/images/) product doc page now includes this limitation. Going to mark this as closed.
