### ISSUE TITLE
Disks and Configuration Profiles Proposed Changes

### ISSUE THREAD

**Issue by jonathanendersby** [linode/docs#2328]
Link: https://linode.com/docs/platform/disk-images/disk-images-and-configuration-profiles/
## Issue
With the new UI, I am unable to find my disks (or how to resize them etc)

## Suggested Fix
Update your documentation before you push users to your new UI.

**Comment by Guaris** [comment]
Hey! Try this doc out! https://www.linode.com/docs/quick-answers/linode-platform/resize-a-linode-disk-new-manager/

We will work on updating that specific guide!
