### ISSUE TITLE
How to Install Apache on CentOS 7 Proposed Changes

### ISSUE THREAD

**Issue by vincent-digicert** [linode/docs#2347]
Link: https://linode.com/docs/web-servers/apache/install-and-configure-apache-on-centos-7/
## Suggested Fix

There is a broken anchor link in Step 1. It reads:

"Ensure that you have followed the Getting Started and Securing Your Server guides, and the Linode’s [hostname is set](https://www.linode.com/docs/getting-started#setting-the-hostname)."

The proper anchor is https://www.linode.com/docs/getting-started/#set-the-hostname

**Comment by Guaris** [comment]
This is fixed thank you!
