### ISSUE TITLE
How to Scan for Vulnerabilties with ClamAV Proposed Changes

### ISSUE THREAD

**Issue by hjpx** [linode/docs#2385]
Link: https://linode.com/docs/security/vulnerabilities/scanning-your-linode-for-malware/
## Issue
Guide is written for the FINNIX distribution used in Rescue Mode so Debian/CentOS specific instructions are confusing at best.

## Suggested Fix
 - Remove Debian/Ubuntu heading
 - Remove CentOS specific heading and instructions

**Comment by Guaris** [comment]
Fixed!
