### ISSUE TITLE
Getting Started with the Linode API Proposed Changes

### ISSUE THREAD

**Issue by mfleming** [linode/docs#2457]
Link: https://linode.com/docs/platform/api/getting-started-with-the-linode-api/
## Issue
All links to the API documentation are broken and result in a 404.

## Suggested Fix

Change https://developers.linode.com/v4/introduction to https://developers.linode.com/api/v4/

**Comment by andystevensname** [comment]
Hi @mfleming ,

Thanks for pointing this out to us. We've updated the guide with PR #2462 and the changes will go out in our next release.
