### ISSUE TITLE
Self-signed certificates and GMail

### ISSUE THREAD

**Issue by vanderlee** [linode/docs#247]
It should probably be noted that GMail only accept non-self-signed SSL certificates for secure POP3/IMAP connections. Self-signed won't work.

**Comment by vanderlee** [comment]
If you MUST have GMail support without a valid SSL certificate and disregarding all the security problems, change the following:

**Comment by thetechstewart** [comment]
@vanderlee - Rather than changing the guide to make the resulting email server less secure, I'm drafting a note that elaborates on the requirement for a commercial SSL cert, along with a link to our relevant guides.  Thanks for bringing this to our attention!

**Comment by vanderlee** [comment]
I agree, insecure setups should not be promoted, even though it may have some (temporary) uses.
But at the very least it should be noted that self-signed certs have these limits. I doubt Gmail is the only service that has this requirement.
