### ISSUE TITLE
DNS Records: An Introduction - a noob confused

### ISSUE THREAD

**Issue by donbright** [linode/docs#2476]
Link: https://linode.com/docs/networking/dns/dns-records-an-introduction/
## Issue

im confused about whether I need to manually add an A record. This document, "DNS Records, an Introduction", says

>  If you decide to use Linode’s name servers, our DNS Manager will help you create a default zone file. 

```
; example.com [448369]
$TTL 86400
@   IN  SOA ns1.linode.com. admin.example.com. 2013062147 14400 14400 1209600 86400
@       NS  ns1.linode.com.
@       NS  ns2.linode.com.
@       NS  ns3.linode.com.
@       NS  ns4.linode.com.
@       NS  ns5.linode.com.
@           MX  10  mail.example.com.
@           A   12.34.56.78
mail        A   12.34.56.78
www         A   12.34.56.78

```

This appears to show A records already set up "by default" to a linode's ip address.

However this page: https://www.linode.com/docs/platform/manager/dns-manager/
says that i need to add some DNS records myself. 

And this page: https://www.linode.com/docs/networking/dns/common-dns-configurations/
says that I need to create the A/AAAA records myself.

This seems to contradict the idea that a "default" was set up for me for the most common case.

## Suggested Fix

I am not actually sure, I know almost nothing about DNS or domains. It has been about 20 hours since my first attempt at "setup" and I'm not really even sure how to do a "sanity check" on the settings I have used. 

I have just now added three "A" records myself, to match the "blah.com, mail.blah.com, www.blah.com"., kind of per https://www.linode.com/docs/platform/manager/dns-manager/

I also tried to see if there was a way to "dump" the "zone file" it built for me to check it against the example shown on this page, "DNS Records, an Introduction",  but i couldnt find anything. There is a 'check zone' button but it is grayed out.

Thank you for reading and, patience with helping a noob.

**Comment by leslitagordita** [comment]
Hello @donbright, thank you for logging this issue. Apologies for the delay in addressing it. I have submitted a PR which should clarify the process of creating a domain with and without default domain records. This update will be live in our upcoming docs release next week. In the meantime, you can see a preview of the changes with [this link](https://deploy-preview-3040--nostalgic-ptolemy-b01ab8.netlify.com/platform/manager/dns-manager/#add-a-domain).
