### ISSUE TITLE
Add CAA Records in the Linode Manager Proposed Changes - TLD is stripped from name

### ISSUE THREAD

**Issue by davidhbrown** [linode/docs#2504]
Link: https://linode.com/docs/quick-answers/linode-platform/add-caa-dns-records/
## Issue
The TLD is stripped from the entered name, at least in the new(ish) Linode Manager. So, if this were really a screenshot of the DNS Records for example.com, you would not see "example.com" in those name records. Also, your text reads `shop.example.com` but you show "store.example.com" in the screen capture.
## Suggested Fix
Make a new screen capture showing the current behavior of the Linode Manager CAA records and correcting the typo. I believe I have attached something suitable. 
<img width="575" alt="CAA records" src="https://user-images.githubusercontent.com/749520/58278536-44747900-7d6a-11e9-8fda-34bb7dde6bb0.png">
Or you could photoshop out the `.example.com` from the Name column in the existing screen capture and change the text.

**Comment by Rajakavitha1** [comment]
Thanks for raising the issue @davidhbrown !!!! This issue has been addressed in https://github.com/linode/docs/pull/2619
