### ISSUE TITLE
Use systemd to Start a Linux Service at Boot Proposed Changes

### ISSUE THREAD

**Issue by robin-a-meade** [linode/docs#2511]
Link: https://linode.com/docs/quick-answers/linux/start-service-at-boot/
## Issue

For me, the "Example service started at ..." line didn't show up in the output of the status command.

Possible explanation:

> The reason for this is a race condition, because the logger/systemd-cat process dies before journald can get the information it needs.
-- September 2013 https://bbs.archlinux.org/viewtopic.php?pid=1326954#p1326954

## Suggested Fix

Until the underlying problem with `systemd-cat` is fixed, here is a workaround:

File: `/usr/bin/test_service.sh`:
```bash
info=/tmp/myservice-systemd-cat-pipe-info
mkfifo "$info"
trap "exec 3>&-; rm $info" EXIT
systemd-cat -p info < "$info" &
exec 3>"$info"

DATE=`date '+%Y-%m-%d %H:%M:%S'`
echo "Example service started at ${DATE}" > "$info"

while :
do
  echo "Looping...";
  sleep 30;
done
EOF
```

## Bug filed
I filed a bug at bugzilla.redhat.com

https://bugzilla.redhat.com/show_bug.cgi?id=1714373

**Comment by Guaris** [comment]
Has this been resolved?

**Comment by robin-a-meade** [comment]
The bug I filed at redhat (https://bugzilla.redhat.com/show_bug.cgi?id=1714373) was acknowledged, but they said "not much we can do unless the kernel helps us." 

The linode tutorial should either acknowledge that systemd-cat output is not reliable due to a race condition, or use the work around identified in the arch linux forum: https://bbs.archlinux.org/viewtopic.php?pid=1326954#p1326954 .

**Comment by Rajakavitha1** [comment]
Thanks for the update and fix @robin-a-meade. 
The information is now updated in https://github.com/linode/docs/pull/2700

**Comment by kyegupov** [comment]
@Rajakavitha1 uh oh I think you have fixed this incorrectly.

At the page https://www.linode.com/docs/guides/start-service-at-boot/ the code is only partially correct, you forgot to change the line

```
echo "Example service started at ${DATE}" | systemd-cat -p info
```

to

```
echo "Example service started at ${DATE}" > "$info"
```

**Comment by robin-a-meade** [comment]
I found a better way. I'd completely remove the use of `systemd-cat`. And remove the *Troubleshooting* section. A simple `echo` is sufficient to output a message at the *info* priority level. Other priority levels can be attained like `echo <4> This is a warning`, as explained here: https://www.freedesktop.org/software/systemd/man/systemd-cat.html#--level-prefix= 

I offer the following example. You may use this to replace the current example.

```bash
# You'll see the following status message in the output of:
#
#    systemctl status myservice
#
# It will look like:
#
#    Status: "Trying to start ..."
#
systemd-notify --status="Trying to start ..."
sleep 5 # simulate taking 5 seconds to start up

# We can easily send messages at various priority levels
# https://www.freedesktop.org/software/systemd/man/systemd-cat.html#--level-prefix=
#systemd-cat --level-prefix=yes # Interpretation of level prefixes is enabled by default
echo "<0> Just testing emerg"
echo "<1> Just testing alert"
echo "<2> Just testing crit"
echo "<3> Just testing err"
echo "<4> Just testing warning"
echo "<5> Just testing notice"
echo "<6> Just testing info"
echo "<7> Just testing debug"

# The default priority level is info
echo "Example service started at $(DATE)"

# Variation to try: Simulating an error during start up
#   echo "<3> error: Encountered a fake error"
#   systemd-notify --status="Encountered a fake error"
#   exit 1

systemd-notify --ready --status="Started and ready"

while :
do
  echo "Looping...";
  sleep 30;
done
```
