### ISSUE TITLE
Create Physical Backups of your MariaDB or MySQL Databases Proposed Changes

### ISSUE THREAD

**Issue by Albrecht-S** [linode/docs#2573]
Link: https://linode.com/docs/databases/mysql/create-physical-backups-of-your-mariadb-or-mysql-databases/
## Issue
Typo or minor inaccuracy.

## Suggested Fix
The text says:
`Create a directory to store your backups. This guide will use /opt/backups ...`

However, the following example code uses `/opt/db-backups`. The text (above) should read

"This guide will use /opt/db-backups ..."

**Comment by Guaris** [comment]
https://github.com/linode/docs/pull/2578


Thank you! I staged a PR!
