### ISSUE TITLE
Set Up WireGuard VPN on Ubuntu Proposed Changes

### ISSUE THREAD

**Issue by bbayer** [linode/docs#2577]
Link: https://linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/
## Issue
Installing Wireguard section has missing apt update step.
## Suggested Fix

add apt update between step 1 and 2.

**Comment by Guaris** [comment]
Does this PR: #2568 fix this?

**Comment by Guaris** [comment]
Reopen this if it doesn't. Thanks for reporting this!
