### ISSUE TITLE
Running mod_fastcgi and PHP-FPM on Debian 7 (Wheezy) with Apache

### ISSUE THREAD

**Issue by LongDono** [linode/docs#258]
The text in this guide for creating the info.php file is not escaped and does not display properly in Chrome or IE, causing the displayed information to be incorrect.

HTML: `<p>sudo echo “<?php phpinfo(); ?>” &gt; /var/www/info.php</p>`

Line of code that displays in the browser: sudo echo “” > /var/www/info.php

**Comment by alexfornuto** [comment]
Thanks for pointing this out! The fix should be published by tomorrow.
