### ISSUE TITLE
Install MongoDB on Ubuntu 16.04 (Xenial) Proposed Changes

### ISSUE THREAD

**Issue by timfrietas** [linode/docs#2581]
Link: https://linode.com/docs/databases/mongodb/install-mongodb-on-ubuntu-16-04/
## Suggested Fix

This document (and many other MongoDB docs if you have them incorrectly state the latest version as 3.2.  It is now 4.0.

**Comment by Rajakavitha1** [comment]
This issue has been addressed in: https://github.com/linode/docs/pull/2623
