### ISSUE TITLE
Longview App for MySQL Proposed Changes

### ISSUE THREAD

**Issue by SiddiqueAhmad** [linode/docs#2597]
Link: https://linode.com/docs/platform/longview/longview-app-for-mysql/
## Issue
if we have socket in non default location it says can not connect on socket
## Suggested Fix
socket parameter should be in added config

**Comment by Rajakavitha1** [comment]
Hi, @SiddiqueAhmad  Thank you for the suggestion.
This is a known issue. Please see https://github.com/linode/longview/issues/17
We have now added a note that reads: You cannot configure the location of a socket for Longview client.
