### ISSUE TITLE
Secure HTTP Traffic with Certbot Proposed Changes

### ISSUE THREAD

**Issue by tojtoj** [linode/docs#2617]
Link: https://linode.com/docs/quick-answers/websites/secure-http-traffic-certbot/
## Issue
typo in the link to the Certbot official documentation: "Certbot Official Dcomentation"
## Suggested Fix
fix the link text to "Certbot Official Documentation"

**Comment by Rajakavitha1** [comment]
Thanks for raising the issue @tojtoj !!! Fixed in https://github.com/linode/docs/pull/2618!!!
