### ISSUE TITLE
Getting Started with Linode - Gentoo - Broken Update Command

### ISSUE THREAD

**Issue by philtyl** [linode/docs#2629]
Link: https://linode.com/docs/getting-started/
## Issue
emerge update command in [Getting Started Guide for Gentoo](https://www.linode.com/docs/getting-started/#gentoo) does not work
`emerge --uDN @world`

## Suggested Fix
Should be replaced with correct emerge update command from [Gentoo Wiki](https://wiki.gentoo.org/wiki/Gentoo_Cheat_Sheet#Package_upgrades):
`emerge -uDU --keep-going --with-bdeps=y @world`

**Comment by Rajakavitha1** [comment]
Thanks @philtyl for raising the issue. This is now addressed in https://github.com/linode/docs/pull/2637
