### ISSUE TITLE
Deploy VoIP Services with Asterisk and Freepbx on Ubuntu 12.04 Proposed Changes

### ISSUE THREAD

**Issue by Rjs1** [linode/docs#2640]
Link: https://linode.com/docs/applications/voip/deploy-voip-services-with-asterisk-and-freepbx-on-ubuntu-12-04-precise/
## Issue
am getting this message when use make command, idk why am gettting this error, someone please  tell what's gone wrong in my proess.
make -C linux all
make[1]: Entering directory '/usr/src/dahdi-linux-complete-3.0.0+3.0.0/linux'
make -C drivers/dahdi/firmware firmware-loaders
make[2]: Entering directory '/usr/src/dahdi-linux-complete-3.0.0+3.0.0/linux/drivers/dahdi/firmware'
make[2]: Leaving directory '/usr/src/dahdi-linux-complete-3.0.0+3.0.0/linux/drivers/dahdi/firmware'
make -C /lib/modules/4.15.0-50-generic/build SUBDIRS=/usr/src/dahdi-linux-complete-3.0.0+3.0.0/linux/drivers/dahdi DAHDI_INCLUDE=/usr/src/dahdi-linux-complete-3.0.0+3.0.0/linux/include DAHDI_MODULES_EXTRA=" " HOTPLUG_FIRMWARE=yes modules DAHDI_BUILD_ALL=m
make[2]: Entering directory '/usr/src/linux-headers-4.15.0-50-generic'
Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  Building modules, stage 2.
  MODPOST 28 modules
WARNING: could not find /usr/src/dahdi-linux-complete-3.0.0+3.0.0/linux/drivers/dahdi/vpmadt032_loader/.vpmadt032_x86_64.o.cmd for /usr/src/dahdi-linux-complete-3.0.0+3.0.0/linux/drivers/dahdi/vpmadt032_loader/vpmadt032_x86_64.o
make[2]: Leaving directory '/usr/src/linux-headers-4.15.0-50-generic'
make[1]: Leaving directory '/usr/src/dahdi-linux-complete-3.0.0+3.0.0/linux'
(cd tools && autoreconf -i && [ -f config.status ] || ./configure --with-dahdi=../linux)
/bin/sh: 1: autoreconf: not found
/bin/sh: 1: ./configure: not found
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 127

**Comment by Rajakavitha1** [comment]
Hi,
This would be a good question to post on Linode community questions board: https://www.linode.com/community/questions/
On the Linode community, you have access to a much larger audience who can answer and give advice regarding your specific use case.
Please do not hesitate to open up a support ticket if you need further guidance. https://manager.linode.com/support/ticket/new.

Closing this issue for now.
