### ISSUE TITLE
Icu is not installed failed to run script

### ISSUE THREAD

**Issue by Rjs1** [linode/docs#2643]
While installing ucp am getting this error i tried to run that code and also get error in my ubuntu that unable to locate icu  or libicu, someone help me with that i installed freepbx on ubuntu 18 and on freepbx everything is working fine except ucp.
Help me to resolve this error
Error!!1
Installing ucp
Updating tables ucp_sessions...Done
icu is not installed. You need to run: yum install icu libicu-devel
Error(s) installing ucp:
Failed to run installation scripts
Updating Hooks...Done

**Comment by Guaris** [comment]
Hey Rjs1, it may be a good idea to ask this question on the Linode Community page. https://www.linode.com/community/questions/
