### ISSUE TITLE
Getting Started With Ansible - Basic Installation and Setup Proposed Changes

### ISSUE THREAD

**Issue by flaugher** [linode/docs#2688]
Link: https://linode.com/docs/applications/configuration-management/getting-started-with-ansible/
## Issue
The title of the link mentioned in this text string on the page is incorrect: "Our Using Ansible Playbooks for Configuration Management guide..."
## Suggested Fix
Change the title to the title on the page it links to which is "Automate Server Configuration with Ansible Playbooks"

**Comment by Rajakavitha1** [comment]
Thanks for the update. This is fixed in https://github.com/linode/docs/pull/2701
