### ISSUE TITLE
Getting Started with Linode Proposed Changes

### ISSUE THREAD

**Issue by flaugher** [linode/docs#2689]
Link: https://linode.com/docs/getting-started/
## Issue
In this [section](https://www.linode.com/docs/getting-started/#debian-7-slackware-ubuntu-14-04) of the page, when I ran the command, `hostname -F /etc/hostname`, I received the error "hostname: the specified hostname is invalid".  I was running the command on Debian 9.
## Suggested Fix
Update the command?  Also, this section references Debian 7.  Debian 9 or 10 is the current version, I believe.

**Comment by Rajakavitha1** [comment]
Hi @flaugher ,

The command to check the hostname in /etc/hostname even in Debian 9 is "
hostname -F /etc/hostname "
When adding an entry to the /etc/hostname the hostname should be unique and should not be www or anything too generic. Some people name their servers after planets, philosophers, or animals. After you’ve made the change below, you’ll need to log out and back in again to see the terminal prompt change from localhost to your new hostname. The command hostname should also show it correctly.

For more information please see: https://www.linode.com/docs/networking/dns/using-your-systems-hosts-file/
Also, valid hostnames contain only 1-9, a-z (case insensitive), and -. Everything else, including |, is invalid.
The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9' and the hyphen-minus character ('-').

**Comment by Rajakavitha1** [comment]
Hi @flaugher ,
Closing this issue for now. If you need further assistance please do not hesitate to log a ticket https://manager.linode.com/support/ticket/new
