### ISSUE TITLE
Specify order of SSL certificates in NodeBalancer guides

### ISSUE THREAD

**Issue by felicianotech** [linode/docs#269]
In the two guides below it is mentioned that if you have chained certificates, you can add them all. This does not explain what that means nor the order in which you need to add them. Took me a little bit to figure it out. This is something that can be explained better.

https://github.com/linode/docs/blob/master/docs/platform/nodebalancer/nodebalancer-reference-guide.md
https://github.com/linode/docs/blob/master/docs/platform/nodebalancer/getting-started-with-nodebalancers.md

**Comment by Joeltrane** [comment]
I agree, that is why I made a point to list an example of using chained certificates in my NodeBalancer/SSL guide, which could probably be better explained still.

**Comment by FelicianoTech** [comment]
We should probably explain it once somewhere. Then in the other guides simply link to it.

**Comment by Joeltrane** [comment]
I agree with that as well, it would make other guides cleaner and better focused. I would be happy to edit this guide to better explain chained certificates:

    --  https://github.com/linode/docs/blob/master/docs/platform/nodebalancer/nodebalancer-reference-guide.md

If the docs team agrees, I will get started on this. I already have a working example here:

    --  https://github.com/linode/docs/pull/237/files

**Comment by alexfornuto** [comment]
https://github.com/linode/docs/pull/237 was merged.
