### ISSUE TITLE
Deploy MERN with One-Click Apps Proposed Changes

### ISSUE THREAD

**Issue by jackbabs** [linode/docs#2704]
Link: https://linode.com/docs/platform/one-click/deploy-mern-with-one-click-apps/
## Issue
MERN.io has been deprecated, so MERN cli is no longer available. 
## Suggested Fix
Reproduction of the document without reliance on MERN.io

**Comment by Rajakavitha1** [comment]
Thanks for the update.

This has now been addressed in https://github.com/linode/docs/pull/2715
