### ISSUE TITLE
How to Set Up a Streisand Gateway Proposed Changes

### ISSUE THREAD

**Issue by kodumbeats** [linode/docs#2724]
Link: https://linode.com/docs/networking/vpn/set-up-a-streisand-gateway/
## Issue
When deploying Streisand from a build node, the Streisand script prompts for a Linode API token. Using the APIv3 token from Classic Manager returns an OAuth error in the deployment script. An APIv4 token from the Cloud Manager works.
## Suggested Fix
Include step-by-step instructions in the Streisand guide to generate an APIv4 token in Cloud Manager, or cross-posting https://www.linode.com/docs/platform/api/getting-started-with-the-linode-api/#get-an-access-token.

**Comment by Rajakavitha1** [comment]
Thank you for the feedback @kodumbeats !!! The guide is updated in https://github.com/linode/docs/pull/2759
