### ISSUE TITLE
Introduction To Vim Customization Proposed Changes

### ISSUE THREAD

**Issue by flaugher** [linode/docs#2736]
Link: https://linode.com/docs/tools-reference/tools/introduction-to-vim-customization/
## Issue

In the "Create .vimrc" section, the comment above "set paste toggle" misspells "outside."  It's spelled "outsdie".

## Suggested Fix

Change to "outside".

**Comment by Rajakavitha1** [comment]
Hi @flaugher, Thanks for the suggestion!!!!
This has now been addressed in https://github.com/linode/docs/pull/2738
