### ISSUE TITLE
Installing McMyAdmin for Minecraft on Debian Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#2737]
Link: https://linode.com/docs/game-servers/minecraft-with-mcmyadmin-on-debian/
## Issue

As mentioned in this tweet: https://twitter.com/boyetronic/status/1174831190261555200

This guide still has the Java instructions set to using java 7, when it should be 8+. 

This was updated in our other guide, which has a date for its last update as the same day: https://www.linode.com/docs/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian/#prerequisites

## Suggested Fix

Using the following command from the other guide _(`openjdk-8-jre-headless screen`)_ as a .... guide, maybe it's as simple as updating this to be:

`openjdk-8-jre`

**Comment by Rajakavitha1** [comment]
Thanks @Wat-Poods !!! This has now been addressed in https://github.com/linode/docs/pull/2742
- Added the steps to install Mono as root user in the before you begin section as suggested in Linux 64-bit install instructions at : https://github.com/linode/docs/pull/2742
- added a note about EULA
- Added instructions to set the iptable rules

Here's the https://deploy-preview-2742--nostalgic-ptolemy-b01ab8.netlify.com/game-servers/minecraft-with-mcmyadmin-on-debian/ for your review.
