### ISSUE TITLE
How to use the Linode Ansible Module to Deploy Linodes Proposed Changes

### ISSUE THREAD

**Issue by flaugher** [linode/docs#2741]
Link: https://linode.com/docs/applications/configuration-management/deploy-linodes-using-ansible/
## Issue
Section "Create the Variables File" says you can pass both a public SSH key and a path to a public key in the ssh_keys variable.  When I tried doing this, I got the following error when I tried passing in either a key and a path to a key file or if I passed paths to two different key files:

    Unable to query the Linode API.  Saw: authorized_keys must either be paths to the key files or a list of raw public key of one of these types...

The only way I could get this to work was to populate the variable with two raw public key strings.

## Suggested Fix

Try to replicate my error and update the documentation if necessary.

**Comment by Rajakavitha1** [comment]
Hi @flaugher ! Thank you for the issue.  I tried the steps and I was not able to replicate the issue. Here's the sample Var file that I have:
```ssh_keys: >
        ['ssh-rsa AAAA##################################################################################################################################################################################################################################################################################################################################################################################################################################################7fvFuw== rajie@ubuntu1804ansible', '~/.ssh/id_rsa.pub']
label: simple-linode- ```

**Comment by Rajakavitha1** [comment]
Closing this issue for now. However, please feel free to reopen if you the issue persists.
