### ISSUE TITLE
Compile options in install-asterisk-on-centos-7 may lead to installation breaking if Linode is migrated

### ISSUE THREAD

**Issue by hjpx** [linode/docs#2744]
In https://www.linode.com/docs/applications/voip/install-asterisk-on-centos-7/, In section "Install Asterisk" / "Configure and Build Asterisk" / Step 2) it says:

> Start the build process. After a short while, you should see a menu on screen allowing you to configure the features you want to build.

```
make menuselect
```

It may be important according to this doc: https://wiki.asterisk.org/wiki/display/AST/Building+and+Installing+Asterisk

to use:

``` 
make menuselect --disable BUILD_NATIVE menuselect.makeopts
```

Otherwise the compile may try to use processor features specific to the current host's processor which may be different if the host is migrated.

**Comment by Rajakavitha1** [comment]
This is now fixed by one of our doc contributors here: https://github.com/linode/docs/pull/2951
