### ISSUE TITLE
Guide "How to Install Asterisk on CentOS 7" does not mention enabling the service

### ISSUE THREAD

**Issue by hjpx** [linode/docs#2745]
In https://www.linode.com/docs/applications/voip/install-asterisk-on-centos-7/ the guide does not instruct the user to enable the Asterisk service after starting the service. This will lead to the service failing to start after a reboot.

**Comment by bagasme** [comment]
This can be fixed by `# systemctl enable asterisk`.

**Comment by Rajakavitha1** [comment]
Hi @hjpx !!!

This has now been fixed in https://github.com/linode/docs/pull/2948. Please see the preview of the updated fix here: https://deploy-preview-2948--nostalgic-ptolemy-b01ab8.netlify.com/applications/voip/install-asterisk-on-centos-7/#test-connection
