### ISSUE TITLE
How to Configure a Firewall with UFW Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#2751]
Link: https://linode.com/docs/security/firewalls/configure-firewall-with-ufw/
## Issue

This was reported by DrJ on IRC: 

`To farther fine-tune your rules, you can also allow packets based on TCP or UDP. The following will allow TCP packets on port 80:`

## Suggested Fix

To ***further*** fine-tune your rules, you can also allow packets based on TCP or UDP. The following will allow TCP packets on port 80:

**Comment by Rajakavitha1** [comment]
@Wat-Poods  Thank you for noticing the typo.
This has now been addressed in https://github.com/linode/docs/pull/2756
You can see the updated changes here: https://deploy-preview-2756--nostalgic-ptolemy-b01ab8.netlify.com/security/firewalls/configure-firewall-with-ufw/#add-rules
