### ISSUE TITLE
Install GitLab on Ubuntu 18.04 Issue

### ISSUE THREAD

**Issue by navjotjsingh** [linode/docs#2753]
In the article ( https://www.linode.com/docs/development/version-control/install-gitlab-on-ubuntu-18-04/ ), the link to **GitLab’s NGINX Configurations** points to a random pull request here. This needs to be fixed.

**Comment by bagasme** [comment]
The (unrelated) PR link is #2231 (Theme Rebuild). Proper link should be [NGINX Settings for Omnibus GitLab](https://docs.gitlab.com/omnibus/settings/nginx.html)

**Comment by Rajakavitha1** [comment]
@navjotjsingh Thank you for noticing the issue.
@bagasme  Thank you for suggesting the fix.

This has now been addressed in https://github.com/linode/docs/pull/2755.
You can see the updated changes here: https://deploy-preview-2755--nostalgic-ptolemy-b01ab8.netlify.com/development/version-control/install-gitlab-on-ubuntu-18-04/
