### ISSUE TITLE
Inconsistent Site Configuration Location on How to Configure NGINX

### ISSUE THREAD

**Issue by bagasme** [linode/docs#2754]
## Guides Affected by the Issue
[How to Configure NGINX](https://linode.com/docs/web-servers/nginx/how-to-configure-nginx/)

## Issue
There is inconsistency regarding site configuration location. From `Server Blocks` to `Name-Based Virtual Host` sections, the path used is `/etc/nginx/conf.d/example.com.conf`. However, from `Location Block` section to the rest of the guide, the path is `/etc/nginx/sites-available/example.com.conf`. 

## Suggested Fix
This guide should use `/etc/nginx/conf.d` to store site configuration. Thus, the wording on `Server Blocks` section should be added to:
```
In this guide, we will use NGINX installed from NGINX Inc's repository, with each site configurations are stored in `/etc/nginx/conf.d`. Substitute with your own paths throughout this guide.
```

**Comment by Rajakavitha1** [comment]
Hi @bagasme ,

Thanks for your feedback. We do have a bullet point in the Servers Block section that reads:

Depending on your installation source, you’ll find an example configuration file at /etc/nginx/conf.d/default.conf or etc/nginx/sites-enabled/default.

Hence, marking this issue as closed. Please feel free to reopen, if there are any other blocking issues.
