### ISSUE TITLE
The Linode Backup Service

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#2761]
Hi,
Based on the comment in Disqus: http://disq.us/p/24ntopb

Issue:
Could you add some discussion about what filesystems and OS combinations are and are not supported and why?  In particular, I want to know why FreeBSD is not supported by Linode's backup service (see https://www.linode.com/docs/tools-reference/custom-kernels-distros/install-freebsd-on-linode/)

Fix:
Review and update the guide

**Comment by Guaris** [comment]
@Rajakavitha1 this is possibly because we do not actively support BSD as an OS for your Linode.

**Comment by Rajakavitha1** [comment]
The list of supported OS is here: https://www.linode.com/distributions
Hence closing the issue.
