### ISSUE TITLE
Serve PHP with PHP-FPM and NGINX Issue: Configure Unix User/Group of Process

### ISSUE THREAD

**Issue by bagasme** [linode/docs#2765]
## Guides Affected
- Serve PHP with PHP-FPM

## Issue
On the guide, only user and group for PHP-FPM socket is set. Although user and group for the socket is `nginx`, access to PHP files may still denied (because PHP-FPM still run as `www-data` user).

This issue proposed to also add edits to PHP-FPM pool configuration (typically `www.conf`) to also change Unix user and group of process to NGINX user (`nginx`). That is, the edit should be:
```ini
; Unix user/group of processes
; Note: The user is mandatory. If the group is not set, the default user's group
;       will be used.
user = nginx
group = nginx
```

**Comment by Rajakavitha1** [comment]
Hi @bagasme,  Thank you for the feedback. Our team will review the issue and update the guide accordingly.

**Comment by Rajakavitha1** [comment]
Closing this issue because you have a PR with the fix. Thanks for the PR @bagasme !!!
