### ISSUE TITLE
SSL Certificates with Apache on Debian & Ubuntu

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#2767]
Issue:
Based on the Disqus comment: http://disq.us/p/24oap8i

Fix:
Update the guide accordingly.

Reference: 
https://www.namecheap.com/support/knowledgebase/article.aspx/9821/38/apache-redirect-to-https

**Comment by gopalraha** [comment]
This issues has been fixed. 

https://github.com/linode/docs/pull/2805

**Comment by Rajakavitha1** [comment]
Closing this PR for now!!!  Here is the preview of the update that was made:https://deploy-preview-2805--nostalgic-ptolemy-b01ab8.netlify.com/security/ssl/ssl-apache2-debian-ubuntu/
