### ISSUE TITLE
Set Up WireGuard VPN on Ubuntu Proposed Changes

### ISSUE THREAD

**Issue by neurosys-zero** [linode/docs#2768]
Link: https://linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/
## Issue
"Currently, WireGuard is only available on Linux." is not accurate. See:  https://www.wireguard.com/install/ 

If this is accurate within Linode, it should be noted.

**Comment by Rajakavitha1** [comment]
Thanks for the update @neurosys-zero !!!!
We just updated the guide and here's the preview: https://deploy-preview-2770--nostalgic-ptolemy-b01ab8.netlify.com/networking/vpn/set-up-wireguard-vpn-on-ubuntu/
