### ISSUE TITLE
Old (v2.2) Access Control on Apache Config on Use NGINX as Front-end Proxy 

### ISSUE THREAD

**Issue by bagasme** [linode/docs#2769]
## Guides Affected
Use NGINX as Front-end Proxy and Software Load Balancer

## Issue Description
Apache site configuration on affected guide contain access control syntax from Apache HTTPD v2.2:
```ini
  ...
 <Directory /var/www/html/example.com>
   Options Indexes FollowSymLinks MultiViews
   AllowOverride None
   Order allow,deny
   allow from all
 </Directory>
  ...
```

On systems with Apache HTTPD v2.4, the access control should be (as per [upstream upgrading documentation](http://httpd.apache.org/docs/2.4/upgrading.html)):
```ini
  ...
 <Directory /var/www/html/example.com>
    Option Indexes FollowSymlinks Multiviews
    AllowOverride None
    Require all granted
 </Directory>
  ...
```

**Comment by Rajakavitha1** [comment]
Thanks for the issue @bagasme .
Just updated the guide in the Pull Request https://github.com/linode/docs/pull/2804.
After the team reviews the changes it will be published.
Closing this issue for now. Please feel free to reopen if any other updates need to be made.
