### ISSUE TITLE
Pflogsumm for Postfix Monitoring on CentOS 6

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#2774]
Based on the comment in Disqus: 

Issue: please stop launching sudo every command, spawn a root shell instead with sudo -i, also cd is not a command! sudo cd will always fail, how embarrassing!

Fix: review and update the guide

**Comment by gopalraha** [comment]
This issues has been fixed https://github.com/linode/docs/pull/2814

**Comment by Rajakavitha1** [comment]
This has now been fixed in https://github.com/linode/docs/pull/2814.
