### ISSUE TITLE
Install Oracle Java SE Development Kit 11 on Ubuntu

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#2781]
Based on Disqus comment: http://disq.us/p/24u04z1

Issue: Currently no package "oracle-java11-installer"

Fix: update the guide

**Comment by bagasme** [comment]
@Rajakavitha1 What are the details of this fix?

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1 What are the details of this fix?

Hi @bagasme We will have to validate the guide and Since Oracle Java 11 can't be directly downloaded from Oracle anymore, the installer no longer works, so we need to create a new installer that requires the user to create an Oracle account, download the Oracle Java 11 .tar.gz archive (the same version as the installer), and place the archive in /var/cache/oracle-jdk11-installer-local/. After this, you can install the oracle-java11-installer-local package, and it will set up Oracle Java 11.

**Comment by Rajakavitha1** [comment]
Hi @bagasme !!! Just wanted to let you know that I assigned this issue to myself because this issue was unassigned and no PR from anyone for more than 5 days now.

**Comment by Rajakavitha1** [comment]
Fixed with the PR : https://github.com/linode/docs/pull/2878
