### ISSUE TITLE
Install and Configure MySQL Workbench on Ubuntu 16.04 Proposed Changes

### ISSUE THREAD

**Issue by ccortijo** [linode/docs#2783]
Link: https://linode.com/docs/databases/mysql/install-and-configure-mysql-workbench-on-ubuntu/
## Issue
HEY TEAM!!!

I ran the commands as stated in the guide, but got this error
  15  sudo apt update && sudo apt upgrade
   16  sudo apt install mysql-workbench
   17  mysql-workbench
   18  history
d_admin@triplebeat:~$ mysql-workbench

_(mysql-workbench-bin:18109): Gtk-WARNING **: 07:17:19.661: cannot open display:_

## Suggested Fix
Add a pre-requisite that would have a user install a VNC desktop and run the 'mysql-workbench' command from the VNC desktop. 

**Install VNC Guide**
https://www.linode.com/docs/applications/remote-desktop/install-vnc-on-ubuntu-18-04/#connect-to-vnc-from-your-desktop

This guide could be linked in the 'Before you get started' section.

After going through this guide and installing the VNC desktop, I was able to successfully open the MySQL via the mysql-workbench command.

I hope this helps! Please let me know if you have any follow questions or if there's anything I can do to help.

Dante Cortijo
ccortijo@linode.com
slack: @dcortijo

**Comment by Rajakavitha1** [comment]
Updated the guide in the PR https://github.com/linode/docs/pull/2803.
@ccortijo  closing this issue for now. However, please feel free to reopen if any other updates need to be made.
