### ISSUE TITLE
How to Use Linode Object Storage Proposed Changes

### ISSUE THREAD

**Issue by bennettnw2** [linode/docs#2790]
Link: https://linode.com/docs/platform/object-storage/how-to-use-object-storage/
## Suggested Fix
1.) We are now able to upload objects to the obj storage buckets.
https://www.linode.com/docs/platform/object-storage/how-to-use-object-storage/#object-storage-tools

2.) I would add another subsection that has instructions to upload objects
https://www.linode.com/docs/platform/object-storage/how-to-use-object-storage/#cloud-manager

I'll work on this tomorrow!

**Comment by Rajakavitha1** [comment]
Hi @bennettnw2 Please let us know if you are still interested in raising a PR for this issue. Because this issue is unassigned for over 6 days now.

**Comment by leslitagordita** [comment]
Hey @bennettnw2 thanks for logging this issue. I submitted a [PR](https://github.com/linode/docs/pull/2796) to add those updates to the doc. It is being reviewed today and will likely be published next week. Thanks!

**Comment by Rajakavitha1** [comment]
Hi @bennettnw2 !!! Closing this issue for now because the PR https://github.com/linode/docs/pull/2796 is now merged. However, please feel free to reopen if there are any other fixes that need to be made.
