### ISSUE TITLE
Apache Guacamole no longer in incubation

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#2807]
Link: https://linode.com/docs/applications/remote-desktop/remote-desktop-using-apache-guacamole-on-docker/
## Issue

The project is no longer in incubation and users should be recommended to use the 1.0 release.

## Suggested Fix

Figure out what setup is used for someone reading an abridged version of the docs and highlight features accordingly.

**Comment by Rajakavitha1** [comment]
@GuessWhoSamFoo We tried the installation of Apache Guacamole using docker and the command "docker pull guacamole/guacamole" pulls the latest image.  All the steps seem to work fine for Debian 9. We will validate this for Ubuntu as well.
Reference:  Guacamole can be deployed using Docker, removing the need to build guacamole-server from source or configure the web application manually. The Guacamole project provides officially-supported Docker images for both Guacamole and guacd which are kept up-to-date with each release.

Closing this issue for now. Please feel to reopen if any changes need to be made.
