### ISSUE TITLE
Troubleshooting Problems with Postfix, Dovecot, and MySQL Proposed Changes

### ISSUE THREAD

**Issue by wumo** [linode/docs#2815]
Link: https://linode.com/docs/email/postfix/troubleshooting-problems-with-postfix-dovecot-and-mysql/
## Issue
In section [Virtual Domains and Users](https://www.linode.com/docs/email/postfix/troubleshooting-problems-with-postfix-dovecot-and-mysql/#virtual-domains-and-users), step 14

> Next up is Dovecot. First, update the mail_location in /etc/dovecot/conf.d/10-mail.conf:

But the code following there doesn't update `mail_location ` and this results in step 18 not successful.
## Suggested Fix
add `mail_location = maildir:~` to the code block as following:
```
mail_location = maildir:~ #update mail_location 
passdb {
  driver = passwd-file
  args = username_format=%u /etc/dovecot/users
}
userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/vhosts/%d/%n
}
```

**Comment by Rajakavitha1** [comment]
@wumo  Thank you for filing the issue and suggesting the fix. Our team will review the issue and update the guide.
