### ISSUE TITLE
Brackets causing confusion in Longview Apache guide

### ISSUE THREAD

**Issue by FelicianoTech** [linode/docs#282]
A user on the forums had trouble with the troubleshooting section of the Longview Apache guide. He misinterpreted that he needed to have the less-than & greater-than brackets in his config. I agree with the confusion source.

We either can remove them or better explain it.

The line in question: https://github.com/linode/docs/blame/master/docs/platform/longview/longview-app-for-apache.md#L225

Re: https://forum.linode.com/viewtopic.php?f=10&t=12223&e=1&

**Comment by alexfornuto** [comment]
Fixed
