### ISSUE TITLE
Object storage: imprecisions on documentation of hosting static websites and custom domains

### ISSUE THREAD

**Issue by vmmello** [linode/docs#2842]
Hi,

I think there are a few imprecisions on section [(Optional) Next Steps](https://www.linode.com/docs/platform/object-storage/host-static-site-object-storage/#optional-next-steps):

1) It misses the mention that for custom domains to work, the name of the bucket needs to be equal to the name of the custom domain (e.g. for **www.my-domain.com** the name of the bucket needs to be "**www.my-domain.com**", otherwise it won't work).

2) there's a mention to adding a CNAME to the bucket "URL". But the correct is to say to point the CNAME do the hostname of the bucket (e.g. CNAME www.my-bucket.com pointing to www.my-bucket.com.website-us-east-1.linodeobjects.com ). And explain it better with an example because it's not obvious to figure out the string to which the CNAME should point to.

3) It misses the mention that when using a custom domain the SSL functionality doesn't work for that domain, at the moment (i.e. will display a certificate warning).

**Comment by bagasme** [comment]
@vmmello for SSL issue did you mean the actual domain (`www.my-domain.com`) or  Linode Objects domain (`*.website-*.linodeobjects.com`)?

**Comment by vmmello** [comment]
@bagasme the actual domain
