### ISSUE TITLE
A Beginner's Guide to Chef Proposed Changes

### ISSUE THREAD

**Issue by DaveJarvis** [linode/docs#2866]
Link: https://linode.com/docs/applications/configuration-management/beginners-guide-chef/
## Issue

`:debug:`

## Suggested Fix

`:debug`

**Comment by bagasme** [comment]
Sorry, please post actual issue and your suggested fix

**Comment by DaveJarvis** [comment]
> log_level: The amount of logging that will be stored in the log file. The default value, :info, notes that any informational messages will be logged. Other values include **:debug:**, :warn, :error, and :fatal.

Fix:

> log_level: The amount of logging that will be stored in the log file. The default value, :info, notes that any informational messages will be logged. Other values include **:debug**, :warn, :error, and :fatal.

**Comment by Rajakavitha1** [comment]
Thanks for logging the issue @DaveJarvis . This has now been addressed in https://github.com/linode/docs/pull/2947.  Here's the link to the preview of the fix:https://deploy-preview-2947--nostalgic-ptolemy-b01ab8.netlify.com/applications/configuration-management/beginners-guide-chef/#knife
