### ISSUE TITLE
Email with Postfix, Dovecot and MariaDB on CentOS 7 Proposed Changes

### ISSUE THREAD

**Issue by damageddolphin** [linode/docs#2877]
Link: https://linode.com/docs/email/postfix/email-with-postfix-dovecot-and-mariadb-on-centos-7/
## Issue
At step to test by sending email I compose an email to the email on the system and the logs show the following:

Nov 11 23:01:05 ***myserver*** postfix/pickup[18001]: 27B62406D4: uid=0 from=<root>
Nov 11 23:01:05 ***myserver*** postfix/cleanup[18051]: 27B62406D4: message-id=<20191112070105.27B62406D4@***myserver***.net>
Nov 11 23:01:05 ***myserver*** postfix/qmgr[18002]: 27B62406D4: from=<root@***myserver***.net>, size=436, nrcpt=1 (queue active)
Nov 11 23:01:05 ***myserver*** dovecot: lmtp(18055): Connect from local
Nov 11 23:01:05 ***myserver*** dovecot: auth-worker(18059): Warning: mysql: Query failed, retrying: Table 'mailserver.users' doesn't exist
Nov 11 23:01:05 ***myserver*** dovecot: auth-worker(18059): Error: sql(testemail@***myserver***.net): User query failed: Table 'mailserver.users' doesn't exist (using built-in default user_query: SELECT home, uid, gid FROM users WHERE username = '%n' AND domain = '%d')
Nov 11 23:01:05 ***myserver*** dovecot: lmtp(testemail@***myserver***.net): msgid=<20191112070105.27B62406D4@***myserver***.net>: saved mail to INBOX
Nov 11 23:01:05 ***myserver*** dovecot: lmtp(18055): Disconnect from local: Successful quit
Nov 11 23:01:05 ***myserver*** postfix/lmtp[18008]: 27B62406D4: to=<testemail@***myserver***.net>, relay=***myserver***.net[private/dovecot-lmtp], delay=0.09, delays=0.02/0/0.01/0.05, dsn=2.0.0, status=sent (250 2.0.0 <testemail@***myserver***.net> 0J/4CrFYyl2HRgAAsx7D1Q Saved)
Nov 11 23:01:05 ***myserver*** postfix/qmgr[18002]: 27B62406D4: removed

I re-read the steps and I can't seem to find the step to add a table users to the database mailserver.

**Comment by bagasme** [comment]
@damageddolphin What are your proposed changes?

**Comment by wildmanonline** [comment]
Closing this issue out.
