### ISSUE TITLE
How to Install Apps on Kubernetes with Helm Proposed Changes

### ISSUE THREAD

**Issue by AKluger** [linode/docs#2886]
Link: https://linode.com/docs/applications/containers/kubernetes/how-to-install-apps-on-kubernetes-with-helm/
## Issue
https://helm.sh/docs/developing_charts/#the-chart-repository-guide 404s
## Suggested Fix
I am not certain where you intend to have the hyperlink point to, but https://helm.sh/docs/topics/charts/ could be a suitable option.  Happy to help with a PR if I can.

**Comment by Rajakavitha1** [comment]
Hi @AKluger !!!
Thank you for logging the issue.
Linode appreciates your contributions in making the documents better. Yes, please feel free to rise a PR with the fix.

**Comment by hzoppetti** [comment]
Hello - thank you! We are working on an update to this guide (moving it to a Helm 2 guide and a new Helm 3 guide) where we update all the links. Helm moved the docs for Helm 2 and all the links needed to be updated. I can link the pr later. https://v2.helm.sh/docs/developing_charts/

**Comment by hzoppetti** [comment]
Hi! Here's the link to that PR: https://github.com/linode/docs/pull/2957

**Comment by Rajakavitha1** [comment]
This is now addressed in https://github.com/linode/docs/pull/2957
