### ISSUE TITLE
StackScripts view pages

### ISSUE THREAD

**Issue by mtilson** [linode/docs#2899]
Link: https://www.linode.com/docs/platform/stackscripts/

---

### Issue

Both links of [StackScript Bash Library](https://www.linode.com/stackscripts/view/1) return 404 - Page Not Found

<img width="495" alt="Screen Shot 2019-11-15 at 22 55 36" src="https://user-images.githubusercontent.com/22861639/68971775-56a41100-07fb-11ea-915f-0fd8f4443e10.png">

**Comment by Rajakavitha1** [comment]
Thanks for logging the issue @mtilson . This is now fixed in https://github.com/linode/docs/pull/2946 you can view the preview here: https://deploy-preview-2946--nostalgic-ptolemy-b01ab8.netlify.com/platform/stackscripts/
