### ISSUE TITLE
How to Install Apps on Kubernetes with Helm Error: unknown flag: --service-account

### ISSUE THREAD

**Issue by AKluger** [linode/docs#2904]
Link: https://linode.com/docs/applications/containers/kubernetes/how-to-install-apps-on-kubernetes-with-helm/
## Issue
running: `helm init --service-account tiller --history-max 200`
results in error `Error: unknown flag: --service-account`

**Comment by hzoppetti** [comment]
Hello - thank you! Yes -Tiller has been removed from Helm 3. This guide is being renamed Helm2 and we are working on Helm 3 guide. A new pr will be added soon. I can link when it's available.

**Comment by hzoppetti** [comment]
Here's the link to that PR: https://github.com/linode/docs/pull/2957

**Comment by Rajakavitha1** [comment]
This issue is now addressed in https://github.com/linode/docs/pull/2957
