### ISSUE TITLE
Build Database Clusters with MongoDB Proposed Changes

### ISSUE THREAD

**Issue by ustcsy** [linode/docs#2916]
Once you’ve added your key file, uncomment the Security section of the /etc/mongod.conf file on each of your Linodes, and add the following value:

security:
keyFile: /opt/mongo/mongodb-keyfile
To apply the change, restart mongod:

sudo systemctl restart mongod

But I can not restart it, as shown:

# sudo systemctl restart mongod
Job for mongod.service failed because the control process exited with error code. See "systemctl status mongod.service" and "journalctl -xe" for details.

I have checked that if i remove the keyFile in conf file, it can be restart correctly.

Link: https://linode.com/docs/databases/mongodb/build-database-clusters-with-mongodb/

**Comment by Rajakavitha1** [comment]
Hi @ustcsy !!!

There is a note that reads: Note that key file authentication automatically enables role-based access control, so you will need to create users and assign them the necessary privileges to access databases.

Could you please confirm if you were unable to restart mongod even after creating the users with necessary privileges.
