### ISSUE TITLE
WordPress Guide Permission Settings Are Off

### ISSUE THREAD

**Issue by felicianotech** [linode/docs#292]
The suggested file permissions to allow WordPress to automatically update it's plugins and themes are fine. They aren't working however to allow WordPress to update itself.

The containing folder, usually `public_html` needs to be owned by www-data as well. This was originally reported via the Linode Forums.

https://forum.linode.com/viewtopic.php?f=23&t=12286

**Comment by ellekrout** [comment]
Running the publish to fix this now!
