### ISSUE TITLE
Object Storage Pricing and Limitations Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#2929]
Link: https://linode.com/docs/platform/object-storage/pricing-and-limitations/
## Issue
Typo in the `Transfer Quotas` section:

> uploading a object

## Suggested Fix

uploading an object

**Comment by Rajakavitha1** [comment]
Hi @Wat-Poods !!!
This is now addressed in the latest guide here: https://www.linode.com/docs/platform/object-storage/pricing-and-limitations/#transfer-quotas. Hence, closing the issue.
