### ISSUE TITLE
Less permissions on API tokens in WireGuard guide

### ISSUE THREAD

**Issue by catleeball** [linode/docs#2959]
Links:
- https://linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/
- https://linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-debian/

## Issue

The guide suggests you create an API token will full r/w permissions on all services. Streisand doesn't need this level of permission to successfully run, though. When setting up my own linode, I was able to run the script only having r/w permission on linodes, IPs, images, events, and domains. Now that I'm a little more familiar with Linode, I bet it could run with only r/w on linodes and IPs, though.

## Suggested Fix

Test the least level of permission needed to successfully set up a Streisand server with everything running, and update the guide letting users know to only give their API token those permissions. This is helpful for security of those reading this guide in the event their token is compromised.

**Comment by Rajakavitha1** [comment]
Thank you @catleeball for the suggestion we did test that and you can create a Streisand server with the r/w access for just Linodes and IPs for API token. We updated the guide accordingly. Here's  the preview of the updated guide: https://deploy-preview-3088--nostalgic-ptolemy-b01ab8.netlify.com/networking/vpn/set-up-a-streisand-gateway/
