### ISSUE TITLE
Database settings does not work with 5.6

### ISSUE THREAD

**Issue by ThomasMoeller** [linode/docs#296]
Ubuntu 15.xx has some issues with the sample config

If you use 'table_cache=x* in MySQL 5.6 it wont start. You have to use table_open_cache instead.

Key_Buffer gives a warning , "[Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead."

**Comment by alexfornuto** [comment]
Which file is this in reference to? This issue is on the repo in general, not a specific file.

**Comment by ThomasMoeller** [comment]
My apologies - Don't know why it posted on the repo itself.

https://github.com/linode/docs/blob/master/docs/websites/hosting-a-website.md

 I know the guide is for Debian 7 and Ubuntu 14 LTS but I thought if someone picked Ubuntu 15.xx they shouldn't have to traverse the internet to find out what's wrong. Could maybe save your support some support tickets.

**Comment by cwlinode** [comment]
Thank you for bringing this to our attention. It should be fixed with commit:
cb0ef1db351d7caa59ca9218ec989726261bfd32
