### ISSUE TITLE
Troubleshooting Problems with Postfix, Dovecot, and MySQL Proposed Changes

### ISSUE THREAD

**Issue by philfrei** [linode/docs#2975]
Link: https://linode.com/docs/email/postfix/troubleshooting-problems-with-postfix-dovecot-and-mysql/
## Issue
Minor typo
In section https://www.linode.com/docs/email/postfix/troubleshooting-problems-with-postfix-dovecot-and-mysql/#ssl-encryption
Step 4
simple formatting problem: backslashes appearing shouldn't be there

    1 disable\_plaintext\_auth = yes

## Suggested Fix
Whatever is needed to get rid of the two "\\" chars. The line should read

    1 disable_plaintext_auth = yes

**Comment by Rajakavitha1** [comment]
This has been addressed in https://github.com/linode/docs/pull/2987
