### ISSUE TITLE
How to Install SELinux on Ubuntu

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#3014]
Validate and update the guide:don't follow this guide:
https://www.linode.com/docs...

Refer this to fix your pc:

https://askubuntu.com/quest...

https://wiki.ubuntu.com/Ker...

https://coderwall.com/p/1qp...

you can press f2 on boot, root shell access , mount -o remount,rw /
remove these two params security=selinux selinux=1 from

/etc/default/grub and then perform do update-grub

**Comment by leslitagordita** [comment]
* We were unable to reproduce the issue reported by the user. 
* The guide has been updated for Ubuntu 18.04 and will be available in our next release. You can view a preview of the updated guide with [this link](https://deploy-preview-3210--nostalgic-ptolemy-b01ab8.netlify.com/quick-answers/linux/how-to-install-selinux-on-ubuntu-18-04/).
