### ISSUE TITLE
Set Up WireGuard VPN on Ubuntu Proposed Changes

### ISSUE THREAD

**Issue by nmelehan** [linode/docs#3074]
Link: https://linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/
## Issue

This guide inappropriately uses 203.0.113.X addresses in some places. This range is from RFC 5737 and is used for documentation examples of public IPs. The issue here is that we are using it to represent examples of private IPs that Wireguard expects.

## Suggested Fix

To fix, review Wireguard's documentation and double-check where private IPs are expected. Then, replace any 203.0.113.X addresses that appear in those places with 192. private IP examples

Here's another suggestion based on the comments on DisQus:

Not OP, but it would be more clear if you specified that you must have the interface down in order to add peers. That got me stuck. Since the upper sections have you actually running the interface, if this is done in order, you will not be able to add peers.

**Comment by Rajakavitha1** [comment]
This issue has now been fixed in https://github.com/linode/docs/pull/3123
