### ISSUE TITLE
Resize a Linode Disk Proposed Changes

### ISSUE THREAD

**Issue by fullbr** [linode/docs#3147]
Link: https://linode.com/docs/quick-answers/linode-platform/resize-a-linode-disk/
## Issue
Step 4 is no longer accurate since the Disks/Configs tab was added to Cloud Manager.  (actually it was previously the Advanced tab, so this may have been outdated for awhile)
## Suggested Fix
Change steps to reflect the current Disks/Configs tab and create a new image.

**Comment by wildmanonline** [comment]
Thanks for the issue report and apologies for the delay in response! This issue was noted and fixed quite a while back. Appreciate it. Closing this out.
