### ISSUE TITLE
Hugo server fails to build the docs repository.

### ISSUE THREAD

**Issue by stickbear2015** [linode/docs#3156]
The following happens when I run hugo server from tthe root of the docs repository.
---begin data copy---
hugo server
Building sites … WARN 2020/02/25 12:02:18 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
ERROR 2020/02/25 12:02:21 How to Install Mastodon on Ubuntu 16.04: Content shortcode is empty.
ERROR 2020/02/25 12:02:27 How to Unbundle nginx from Omnibus GitLab for Serving Multiple Websites: Content shortcode is empty.
ERROR 2020/02/25 12:02:27 Install GitLab on Ubuntu 18.04: Content shortcode is empty.
ERROR 2020/02/25 12:02:27 Install Roundcube on Ubuntu 16.04: Content shortcode is empty.
ERROR 2020/02/25 12:02:28 Install SquirrelMail on Ubuntu 16.04 or Debian 8: Content shortcode is empty.
ERROR 2020/02/25 12:02:28 Configure SPF and DKIM With Postfix on Debian 8: Content shortcode is empty.
ERROR 2020/02/25 12:02:28 Configure SPF and DKIM With Postfix on Debian 9: Content shortcode is empty.
ERROR 2020/02/25 12:02:28 Configure Postfix to Send Mail Using Gmail and Google Apps on Debian or Ubuntu: Content shortcode is empty.
ERROR 2020/02/25 12:02:29 Email with Postfix, Dovecot, and MySQL on CentOS 6: Content shortcode is empty.
ERROR 2020/02/25 12:02:29 Email with Postfix, Dovecot and MariaDB on CentOS 7: Content shortcode is empty.
ERROR 2020/02/25 12:02:29 Email with Postfix, Dovecot, and MySQL: Content shortcode is empty.
ERROR 2020/02/25 12:02:29 Install iRedmail, Open-Source Mail Server, on Ubuntu: Content shortcode is empty.
ERROR 2020/02/25 12:02:29 Pflogsumm for Postfix Monitoring on CentOS 6: Content shortcode is empty.
ERROR 2020/02/25 12:02:29 Troubleshooting Problems with Postfix, Dovecot, and MySQL: Content shortcode is empty.
ERROR 2020/02/25 12:02:29 Configure Postfix to Send Mail Using an External SMTP Server: Content shortcode is empty.
ERROR 2020/02/25 12:02:29 How to Create an Email Server with Mail-in-a-Box: Content shortcode is empty.
ERROR 2020/02/25 12:02:29 Install Zimbra Open Source Edition on Ubuntu 14.04: Content shortcode is empty.
ERROR 2020/02/25 12:02:32 Kubernetes Reference Guide: Content shortcode is empty.
ERROR 2020/02/25 12:02:35 Linode Beginner's Guide: Content shortcode is empty.
ERROR 2020/02/25 12:02:39 Deploy GitLab with One-Click Apps: Content shortcode is empty.
ERROR 2020/02/25 12:02:39 Deploy WordPress with One-Click Apps: Content shortcode is empty.
ERROR 2020/02/25 12:02:39 Deploy WooCommerce with One-Click Apps: Content shortcode is empty.
ERROR 2020/02/25 12:02:41 Using Fail2ban to Secure Your Server - A Tutorial: Content shortcode is empty.
ERROR 2020/02/25 12:02:43 Linux System Administration Basics: Content shortcode is empty.
ERROR 2020/02/25 12:02:43 How to Use logrotate to Manage Log Files: Content shortcode is empty.
ERROR 2020/02/25 12:02:43 Install Icinga 2 Monitoring on Debian 9: Content shortcode is empty.
ERROR 2020/02/25 12:02:45 How to Install PrestaShop on Ubuntu 16.04: Content shortcode is empty.
Built in 49328 ms
Error: Error building site: logged 27 error(s)
---end data copy---
I don't know what's broken, or am I missing something in my Hugo install?

**Comment by stickbear2015** [comment]
I haven't seen anyone comment on this, does anyone know what might be wrong?

**Comment by Rajakavitha1** [comment]
@stickbear2015 !!! looks like the name of the short guides (short-codes) in the guides listed have been changed/update or removed.

**Comment by jmacdotorg** [comment]
For what it's worth, I have the same problem, with identical error output.

Here is my Hugo version information:
```
Ashrind:docs jmac$ hugo env
Hugo Static Site Generator v0.67.0/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.14"
```

I am new to Hugo, so I feel a little lost as to what I can do here.

**Comment by stickbear2015** [comment]
hm, my env is different
Hugo Static Site Generator v0.65.3-211BA42A windows/amd64 BuildDate: 2020-02-23T09:58:40Z
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.13.7"

**Comment by stickbear2015** [comment]
@Rajakavitha1 how might we go about fixing this so hugo builds it again?
What kind of pull requests need to be submitted to fix this.
It can't just be me and jmacdotorg with these local issues.

**Comment by jasonwee** [comment]
having problem too.

```
$ hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z

$ hugo server
Building sites … WARN 2020/03/31 19:31:59 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
ERROR 2020/03/31 19:31:59 How to Install Mastodon on Ubuntu 16.04: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 How to Unbundle nginx from Omnibus GitLab for Serving Multiple Websites: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Install GitLab on Ubuntu 18.04: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Install Roundcube on Ubuntu 16.04: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Install SquirrelMail on Ubuntu 16.04 or Debian 8: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Install iRedmail, Open-Source Mail Server, on Ubuntu: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Configure Postfix to Send Mail Using Gmail and Google Apps on Debian or Ubuntu: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Configure SPF and DKIM With Postfix on Debian 8: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Configure SPF and DKIM With Postfix on Debian 9: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Email with Postfix, Dovecot, and MySQL on CentOS 6: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Email with Postfix, Dovecot and MariaDB on CentOS 7: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Email with Postfix, Dovecot, and MySQL: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Troubleshooting Problems with Postfix, Dovecot, and MySQL: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Pflogsumm for Postfix Monitoring on CentOS 6: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Configure Postfix to Send Mail Using an External SMTP Server: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Install Zimbra Open Source Edition on Ubuntu 14.04: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 How to Create an Email Server with Mail-in-a-Box: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Kubernetes Reference Guide: Content shortcode is empty.
ERROR 2020/03/31 19:32:00 Linode Beginner's Guide: Content shortcode is empty.
ERROR 2020/03/31 19:32:01 Deploy GitLab with One-Click Apps: Content shortcode is empty.
ERROR 2020/03/31 19:32:01 Deploy WordPress with One-Click Apps: Content shortcode is empty.
ERROR 2020/03/31 19:32:01 Deploy WooCommerce with One-Click Apps: Content shortcode is empty.
ERROR 2020/03/31 19:32:01 Using Fail2ban to Secure Your Server - A Tutorial: Content shortcode is empty.
ERROR 2020/03/31 19:32:01 Linux System Administration Basics: Content shortcode is empty.
ERROR 2020/03/31 19:32:01 How to Use logrotate to Manage Log Files: Content shortcode is empty.
ERROR 2020/03/31 19:32:01 Install Icinga 2 Monitoring on Debian 9: Content shortcode is empty.
ERROR 2020/03/31 19:32:02 How to Install PrestaShop on Ubuntu 16.04: Content shortcode is empty.
Built in 4327 ms

```

**Comment by leslitagordita** [comment]
* This issue is likely related to the Hugo version that you are running locally. On the docs team we use Hugo version 0.52 for all our builds.
* If you are using a macOS system and installed Hugo using brew, you can get back to v0.52 with the following commands:
`brew remove hugo`
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/d2c35e3938f6b71d97a54f6b6573345b0f6b0b9f/Formula/hugo.rb`

**Comment by nmelehan** [comment]
I also want to add two more installation methods:

- Downloading a binary from [the Hugo releases page for version 0.52](https://github.com/gohugoio/hugo/releases/tag/v0.52)
- If you're using Chocolatey on Windows, running `choco install hugo --version 0.52`

**Comment by jmacdotorg** [comment]
I can confirm that downgrading my installed Hugo version to 0.52 resolves this issue.

**Comment by jasonwee** [comment]
I had to remove hugo which installed from apt repository and install version 0.52, which can be found at https://github.com/gohugoio/hugo/releases?after=v0.53 

You might want to update the documentation at https://github.com/linode/docs

**Comment by wildmanonline** [comment]
This issue is quite old and it looks like most folks in this thread have resolved their issues. Going to mark this as closed.
