### ISSUE TITLE
Typo Cancel-your-account-shortguide "Accounts link" should read "Account Link"

### ISSUE THREAD

**Issue by AKluger** [linode/docs#3162]
cancel-your-account-shortguide

Typo Cancel-your-account-shortguide "Accounts link" should read "Account Link"

Accounts is pluralized but viewing in Cloud Manager displays only singular.

Originally discovered when viewing this page: https://www.linode.com/docs/platform/billing-and-support/manage-billing-in-cloud-manager/#cancelling-your-account

**Comment by Rajakavitha1** [comment]
Thanks for the suggestion. This is now fixed in https://github.com/linode/docs/pull/3200.
Here's the preview of the updated guide: https://deploy-preview-3200--nostalgic-ptolemy-b01ab8.netlify.com/quick-answers/linode-platform/how-to-cancel-your-account/

**Comment by Rajakavitha1** [comment]
Closing this issue for now. Please feel free to reopen if anything else needs to be updated.
