### ISSUE TITLE
Using the Linode Shell (Lish)

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#3184]
DisQus Comment:

1. You could publish this entire list in ssh_known_hosts(5) format and eliminate a lot of human error.

2. It would drive adoption to link to this article from the web interface Networking tab. I had to search for it.

Update the guide based on the suggestions.

**Comment by wildmanonline** [comment]
This guide has been reworked. There's currently no logical place to put this doc near the Launch LISH Console button in Cloud Manager but will keep this in mind!
