### ISSUE TITLE
How to Use Linode Object Storage Proposed Changes

### ISSUE THREAD

**Issue by jeremiah** [linode/docs#3195]
Link: https://linode.com/docs/platform/object-storage/how-to-use-object-storage/
## Issue
s3cmd is not found by apt on Debian 10
## Suggested Fix
It may be worth noting somewhere that newer versions of Debian have s4cmd that replaces s3cmd. Ubuntu appears to be moving in that direction as well, Ubuntu 20.04 has both s3cmd and s4cmd.

**Comment by wildmanonline** [comment]
This issue has been addressed with the linked pull request. The s3cmd and s4cmd installation instructions now outline how to install through pip. Marking this as done. Thanks @jeremiah
