### ISSUE TITLE
How to Install FarmOS - a Farm Recordkeeping Application Proposed Changes

### ISSUE THREAD

**Issue by rl0nergan** [linode/docs#3209]
Link: https://linode.com/docs/applications/project-management/install-farmos/
## Issue
The guide doesn't specify a which version of Drupal is needed to run FarmOS, so when I installed Drupal it used 7 which is the current version but Drupal 7 does not work with FarmOS.
## Suggested Fix
Specify that Drupal 5.6 is needed to run FarmOS

**Comment by Rajakavitha1** [comment]
Thank you for the feedback. This guide provides instructions to install do a fresh installation of FarmOS on a LAMP stack in Ubuntu 20.04. Closing this issue for now. Please feel free to reopen if any other changes need to be made.
