### ISSUE TITLE
iptables examples failing

### ISSUE THREAD

**Issue by alessioalex** [linode/docs#323]
```
alessio@scw-272444:~$ sudo iptables-restore < /tmp/v4
iptables-restore: line 36 failed
```

**Comment by cwlinode** [comment]
@alessioalex Sometimes iptables gives a reason for the error. Is there any shown? If not, it's probably a matter of something not being translated correctly from website to clipboard to terminal. Also be sure to have *filter as the first line, and COMMIT as the last. It works on all of our testing on various platforms, so let us know if you're still running into an issue.
