### ISSUE TITLE
Secure HTTP Traffic with Certbot

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#3235]
Please review the DisQus comment and update the guide accordingly:

Please either completely deprecate this or include instructions for:

<code>$ certbot certonly -a dns-linode --dns-linode-propagation-seconds 1200 --dns-linode-credentials .linode_api/certbot </code>

**Comment by rsyracuse** [comment]
Just for reference https://certbot-dns-linode.readthedocs.io/en/stable/

**Comment by wildmanonline** [comment]
This guide has since been rewritten and I don't believe this feedback is actionable anymore.
