### ISSUE TITLE
Install and Configure NixOS on a Linode Proposed Changes

### ISSUE THREAD

**Issue by horkhork** [linode/docs#3236]
Link: https://linode.com/docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/
## Issue

Fetching the Installer ISO via curl fails unless following links is enabled: -L argument.

## Suggested Fix

Change

```bash
curl $iso | dd of=/dev/sda
```

to

```bash
curl -L $iso | dd of=/dev/sda
```

**Comment by hzoppetti** [comment]
Thank you, this issue has been addressed in https://github.com/linode/docs/pull/3249
