### ISSUE TITLE
Install and Configure NixOS on a Linode Proposed Changes

### ISSUE THREAD

**Issue by horkhork** [linode/docs#3237]
Link: https://linode.com/docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/
## Issue

Missing network interface for DHCP.

Following the directions as I currently see them I think they are missing an entry for `eth0`:
> We will also need to change the name of the interface that DHCP is used on. We will need to replace contents of the existing block around networking.useDHCP with the following.
> 
> > networking.useDHCP = false; # Disable DHCP globally as we will not need it.
> > # Disable DHCP at the interface level as the interface will not exist
> > # networking.interfaces.enp0s5.useDHCP = true;

## Suggested Fix

Add the following for `eth0` to the config snippet:
```
networking.interfaces.eth0.useDHCP = true;
```

**Comment by hzoppetti** [comment]
This issue has been addressed in https://github.com/linode/docs/pull/3249
