### ISSUE TITLE
Error: You Forgot to Enable HTTPS in Firewalld

### ISSUE THREAD

**Issue by bdkjones** [linode/docs#3238]
Link: https://linode.com/docs/web-servers/lamp/how-to-install-a-lamp-stack-on-centos-8/
## Suggested Fix

This guide instructs people to enable the `httpd` service to receive outside connections by running these commands:

    sudo firewall-cmd --zone=public --add-service=http --permanent
    sudo firewall-cmd --zone=public --add-service=http

However, it's 2020 and every web server should be using TLS. Your guide should advise people to open `https` as well:

    sudo firewall-cmd --zone=public --add-service=https --permanent
    sudo firewall-cmd --zone=public --add-service=https

I wasted a good hour trying to figure out why my new CentOS8 server was refusing connections on port 443. I was led astray because this server is backed by Cloudflare and I thought the issue might be related to that. You should update your guide to inform people that they need to explicitly open BOTH http and https for a modern webserver.

**Comment by Rajakavitha1** [comment]
@bdkjones Thanks for reporting the issue and the possible update that needs to be made. Our team will review the suggestion and update the guide shortly.

**Comment by Rajakavitha1** [comment]
This has now been fixed in the PR: https://github.com/linode/docs/pull/3240. Here's the preview of the update that were made: https://deploy-preview-3240--nostalgic-ptolemy-b01ab8.netlify.com/web-servers/lamp/how-to-install-a-lamp-stack-on-centos-8/#configure-firewalld-to-allow-http-and-https-connections

**Comment by Rajakavitha1** [comment]
Closing this issue now. Please feel free to reopen if any other updates need to be made.
