### ISSUE TITLE
Distribution kernel notes

### ISSUE THREAD

**Issue by rvl** [linode/docs#324]
In the file docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm.md, I think 2 things should be clarified:
1. There are two options for running a distribution supplied kernel.
   The "GRUB 2" boot option. Using this requires the root image to have a filesystem but no partitions. The grub2 setup seems to be hardwired to set `root=(hd0)` and `prefix=(hd0)/boot/grub`. This setup needs you to run `update-grub` to refresh the files in `/boot/grub`, but `grub-install` is not necessary.
   
   The "Direct boot" option. If your disk image has a partition table and filesystems on those partitions (e.g. a separate /boot) -- as is commonly done by many distro installers. In this case, `grub-install` must be run to install grub into the MBR of the virtual disk device.
2. When running such a BYO kernel configuration, Linode are limited in terms of the support they are able to offer.

**Comment by alexfornuto** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;syL0pXUv&#x2F;50-distribution-kernel-notes"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Distribution kernel notes</a>

**Comment by cwlinode** [comment]
Thank you for bringing this up. We've given this guide a makeover and the GRUB 2 boot option now boots the distro-supplied kernel for all of our Recommended distributions. There's no need to reinstall the kernel or mess with Grub anymore. The guide updates will be published shortly. Closing.
