### ISSUE TITLE
Install and Configure NixOS on a Linode

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#3242]
Related issues:
- https://github.com/linode/docs/issues/3237
- https://github.com/linode/docs/issues/3236
                          

Update the guide based on suggestions in DisQus:

I had a bit of a hard time following this tutorial, it was very much a learning experience. Here's my challenges: 

1. I didn't have an active Linode and figured I had to activate one. I went with an Arch to start with, but should have started with an empty partition instead - basically had to run the install and config steps a second time after deleting the Arch partition.
2. I had to use wget instead of curl (I could not get curl to work at all) but on the positive side I was able to do the checksum after using wget to download the iso. Perhaps the tutorial should cover the checksum instead of piping to dd directly.
3. I had to look up the forceInstall option, and I'm still not sure it was the right thing to set to true, but I have sent a pull request to add my solution to the tutorial.
4. Still haven't fully worked out ssh and setting up my user yet. I'm reading/scanning the NixOS docs now for that. Would be nice if this was covered in the optional end parts, with care in selecting the "most secure" key generation and a little discussion around user groups and permissions.

Major things I appreciate about this tutorial: 

1. I now have a NixOS image from a fresh install.
2. I actually have NixOS on my Linode server!

**Comment by nop** [comment]
The issue with curl could be that the NixOS iso is behind a redirect. `curl -L` works for me.

**Comment by Rajakavitha1** [comment]
This issue has been addressed in https://github.com/linode/docs/pull/3249 and Yes, curl -L worked for me as well.
