### ISSUE TITLE
Mention SELinux Booleans: Save 3 Hours of My Life.

### ISSUE THREAD

**Issue by bdkjones** [linode/docs#3252]
Link: https://linode.com/docs/web-servers/lamp/how-to-install-a-lamp-stack-on-centos-8/

## Issue

Many people using this guide (me) will be coming from CentOS 7. If you're installing a LAMP stack, there's a 98% chance you plan to connect to outside APIs from PHP scripts on your website: PayPal, Stripe, etc.

If you follow the guide as published, all those calls will fail with "network error 7". The reason is that you forgot to do this in the section about dealing with SELinux:

    setsebool httpd_can_network_connect 1

Without that setting, the `httpd` process can't establish any outbound connections. Your users will waste three hours trying to figure out why. 

## Suggested Fix

You should modify the guide to add this to the "Dealing with SELinux" section because this requirement is new on CentOS 8.

**Comment by Rajakavitha1** [comment]
Thank you for posting the issue and the solution. We just updated the guide with a note about selinux boolean, here's the preview of the update made. https://deploy-preview-3240--nostalgic-ptolemy-b01ab8.netlify.com/web-servers/lamp/how-to-install-a-lamp-stack-on-centos-8/#configure-selinux-to-allow-http

The updated content will be available on the website as soon as the PR is merged.

Please feel free to reopen the issue. If any other changes need to be made.

**Comment by Rajakavitha1** [comment]
Related PR: https://github.com/linode/docs/pull/3240
