### ISSUE TITLE
Resize a Linode Disk

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#3253]
Update the guide based on the comments in DisQus:
In the note, this page says

"""

The Linode Cloud Manager will not allow you to resize your disk to an 
amount smaller than the space taken up by files on your filesystem. To 
confirm how much space you’re using, issue the df -h command on your Linode.
"""

Since it *doesn't* say what technology the control panel uses to resize the disk, if it's guaranteed to not break anything in the process, it probably ought to explicitly say so -- this is a function which, on a hardware PC, you'd probably do by rebooting into a tool you "understand" like Partition Magic... which you obviously can't do on a VM.  A bit more transparency would be nice here...

[ I caught a free upgrade a while back from 4 to 8G, and it appears it resized my disks automatically, making it harder to go back so I can split it into 2 4s for experimentation purposes... ]

Also: Settings no longer contains Disks; might be time to update this writeup.

**Comment by wildmanonline** [comment]
This guide has since been rewritten and I believe addresses the comments above. Closing this issue.
