### ISSUE TITLE
Issues in Installing and Configuring FastCGI and PHP-FPM on CentOS 7

### ISSUE THREAD

**Issue by AbdulRafay** [linode/docs#3324]
Link: https://linode.com/docs/web-servers/apache/how-to-install-and-configure-fastcgi-and-php-fpm-on-centos-8/
## Issue

I have tried it on CentOS 7, followed all steps in the guide but i was not able to configure php-fpm. 

My configs are as follow:

/etc/php-fpm.d/example.com

    user = apache
    group = apache
    listen = /var/run/php-fpm/example.sock

/etc/httpd/conf/httpd.conf

    AddHandler  fcgid-script .fcgi .php .fpl
    FcgidConnectTimeout 20
    FcgidMaxRequestLen 268435456
    FcgidMaxProcessesPerClass 10
    FcgidIOTimeout 300

/etc/httpd/conf.d/fcgid.conf

    AddHandler fcgid-script fcg fcgi fpl
    # Sane place to put sockets and shared memory file
    FcgidIPCDir /run/mod_fcgid
    FcgidProcessTableFile /run/mod_fcgid/fcgid_shm

/etc/httpd/conf.modules.d/10-fcgid.conf

    LoadModule fcgid_module modules/mod_fcgid.so
    <IfModule mod_fcgid.c>
      FcgidConnectTimeout 20
      AddType  application/x-httpd-php         .php
      AddHandler application/x-httpd-php .php
      Alias /php7-fcgi /usr/lib/cgi-bin/php7-fcgi
      <IfModule mod_mime.c>
        AddHandler fcgid-script .fcgi
      </IfModule>
    </IfModule>

/etc/httpd/sites-available/text.conf

    <Directory /var/www/html/www.example.com>
            Require all granted
    </Directory>
    <VirtualHost *:80>
        ServerName www.example.com
        ServerAlias example.com
        DocumentRoot /var/www/html/www.example.com
    #ProxyPassMatch ^/(.*\.php(/.*)?)$ unix://var/run/php-fpm/php-fpm.sock|fcgi://localhost/var/www/html/
    #ProxyPassMatch ^/index$ fcgi:///var/run/php-fpm/php-fpm.sock/var/www/html/index.php
        ErrorLog /var/www/html/www.example.com/log/error.log
        CustomLog /var/www/html/www.example.com/log/requests.log combined
    <IfModule mod_fcgid.c>
             Options +ExecCGI
             FcgidConnectTimeout 20
             AddType  application/x-httpd-php         .php
             AddHandler application/x-httpd-php .php
             Alias /php7-fcgi /usr/lib/cgi-bin/php7-fcgi
             ProxyPassMatch " ^/(.*\.php(/.*)?)$" "unix:listen = /var/run/php-fpm/example.com.sock|fcgi://localhost/var/www/html/www.example.com/"
         </IfModule>
    </VirtualHost>

when i access my web server at /info.php i get Apache 2.0 Handler as my Server API. 

![image](https://user-images.githubusercontent.com/614883/81182863-cbe0e980-8fc7-11ea-99da-f5a86d18d61f.png)

what did i miss?

**Comment by Rajakavitha1** [comment]
Hi @AbdulRafay !!! Thank you for the feedback. This document has been validated again CentOS8. Please feel free to log a ticket at [Linode support ](https://cloud.linode.com/support/tickets) if you need further assistance.

**Comment by Rajakavitha1** [comment]
Closing this issue for now because it is not related to the document on CentOS8
