### ISSUE TITLE
Are articles on hosting your website using static website generators welcome?

### ISSUE THREAD

**Issue by bendtherules** [linode/docs#336]
I would like to write an article for hosting your own website on Linode using a static website generator called Pelican. They are much easier to handle than traditional CMS like Wordpress.

One of the similar frameworks already there in the docs is called Mango, which is also Python based but I think Pelican might be of its own interest as it is more popular in the community and very much configurable,

So, given these things, will such an article be right fit for the community?

**Comment by cwlinode** [comment]
@bendtherules Thank you for your interest in writing for Linode. Please submit a PR against Lindoe/Docs so the community can review your guide. I look forward to reading it.

**Comment by alexfornuto** [comment]
@bendtherules to answer your question, yes we would be interested in a guide on Pelican.
