### ISSUE TITLE
Deploy Drupal with One-Click Apps Proposed Changes

### ISSUE THREAD

**Issue by bradallenfisher** [linode/docs#3381]
Link: https://linode.com/docs/platform/one-click/deploying-drupal-with-one-click-apps/
## Issue
The database server version 10.1.44-MariaDB-0+deb9u1 is less than the minimum required version 10.3.7. Can't install drupal 9 with the version that ships with this 1 click.
## Suggested Fix
Is there a fix in place. I started going down the rabbit hole then i remembered... this was supposed to be a 1 click. :)

**Comment by Rajakavitha1** [comment]
Thank for reporting the issue. We just passed on the issue to our one-click apps team.

**Comment by Rajakavitha1** [comment]
The One Click Apps team made the changes and the changes are now reflecting even in the guide: https://www.linode.com/docs/platform/one-click/how-to-deploy-drupal-with-one-click-apps/. Closing this issue for now. Please feel free to reopen if any other changes need to be made.
