### ISSUE TITLE
A Beginner's Guide to Terraform Proposed Changes

### ISSUE THREAD

**Issue by acaloiaro** [linode/docs#3383]
Link: https://linode.com/docs/applications/configuration-management/terraform/beginners-guide-to-terraform/
## Issue

Hi, I noticed there's no documentation about using Linode Object Storage as a Terraform state store. Since state storage is a big part of production-worthy Terraform setups, this seems worthy of first-class documentation on linode.com.

## Suggested Fix

I wrote up a note-to-self on my site for future reference, but it'd be great if something similar was in the official linode docs: https://adriano.fyi/2020-05-29-terraform-s3-backend-with-linode/

Cheers

**Comment by Rajakavitha1** [comment]
@acaloiaro there is 404 on the link to check the suggested fix. Closing this issue for now. please feel free to reopen the issue with suggested fix.

**Comment by acaloiaro** [comment]
Hi @Rajakavitha1 -- sorry about that. I migrated a bunch of content on my personal site. The content is here: https://adriano.fyi/post/2020-05-29-how-to-use-linode-object-storage-as-a-terraform-backend/
