### ISSUE TITLE
Copying a Disk to a Different Account Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#3384]
Link: https://linode.com/docs/platform/disk-images/copying-a-disk-image-to-a-different-account/
## Issue

Screen shots are from Classic Manager
## Suggested Fix

Updated screen shots.

**Comment by Rajakavitha1** [comment]
This has now been addressed in https://github.com/linode/docs/pull/3404. Please see the preview here: https://deploy-preview-3404--nostalgic-ptolemy-b01ab8.netlify.app/platform/disk-images/copying-a-disk-image-to-a-different-account/.

Please feel free to reopen the issue if any other changes need to be made.
