### ISSUE TITLE
Manage Billing in Cloud Manager Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#3413]
Link: https://linode.com/docs/platform/billing-and-support/manage-billing-in-cloud-manager/
## Issue

Instructions for cancelling your Linode account is outdated, as that option is now located in the Account Settings page, along with the Object Storage cancellation button.

https://cloud.linode.com/account/settings

## Suggested Fix

1: Log into [Cloud Manager](https://cloud.linode.com/).
2: Click the **Account** link in the sidebar, then go to **[Settings](https://cloud.linode.com/account/settings)** page
3: At the bottom of the page, click to expand the **Close Account** option, then click the **Close Account** button

Then, 4 & 5 can be the same.

**Comment by hzoppetti** [comment]
Hi Pat, this issue is addressed in the following PR ready to be published in our next release. Thank you! https://github.com/linode/docs/pull/3390
