### ISSUE TITLE
Email with Postfix, Dovecot, and MySQL Proposed Changes

### ISSUE THREAD

**Issue by chhotii-alex** [linode/docs#3414]
Link: https://linode.com/docs/email/postfix/email-with-postfix-dovecot-and-mysql/
## Issue

I believe this document is rather out of date. For example, I'm on the part where I edit /etc/postfix/main.cf. The file I have (as freshly installed by Postfix) contains this line, which is not in the main.cf in the document:

compatibility_level = 2

So, should this be there, even though that makes my file not match the document? Should it be commented out? What's the correct value for this to make the rest of the guide work?

I think there's additional discrepancies further along...

**Comment by Rajakavitha1** [comment]
Hi @chhotii-alex  the file is just a reference and no action needs to be performed on that line. This guide was just validated. Closing this issue for now. Please feel free to reopen if any other changes need to be made.
