### ISSUE TITLE
Number of Bits for the Key should be updated

### ISSUE THREAD

**Issue by morituri2** [linode/docs#342]
Similiar to https://www.linode.com/docs/security/securing-your-server the number of bits for the ssh key generation should be updated to 4096 bit using puttygen. (in https://github.com/linode/docs/blob/master/docs/security/use-public-key-authentication-with-ssh.md)

**Comment by alexfornuto** [comment]
@morituri2 sorry for the late reply! This was updated in the copy to say "You can choose at this point to increase the number of bits to 4096. "
