### ISSUE TITLE
Object Storage Pricing and Limitations Proposed Changes

### ISSUE THREAD

**Issue by mcivi** [linode/docs#3440]
Link: https://linode.com/docs/platform/object-storage/pricing-and-limitations/
## Issue
Available Locations is missing Singapore data center
## Suggested Fix
Add Data Center | Availability Date | Related Cluster URLs for Singapore to the Available Locations section
https://www.linode.com/docs/platform/object-storage/pricing-and-limitations/#available-locations

**Comment by Rajakavitha1** [comment]
The Singapore location is now updated in our guides: https://www.linode.com/docs/platform/object-storage/pricing-and-limitations/#available-locations. Closing this issue for now. Please feel free to reopen if any other changes need to be made.
