### ISSUE TITLE
 liode-cli to create raw disk fail

### ISSUE THREAD

**Issue by Cheng-Hung-Wang** [linode/docs#3448]
Link: https://linode.com/docs/platform/api/linode-cli/
## Suggested Fix

Hi, i use liode-cli to create raw disk. Command like list 
```
# linode-cli linodes disk-create --size 25088 --label test-disk --filesystem raw --root_pass testtest  linodeId
```
when it down, i saw the disk list
```
# linode-cli linodes disks-list 
```

the filesystem would be ext4 

Is it a command bug?

**Comment by hzoppetti** [comment]
Hi @Cheng-Hung-Wang 

What is happening with the CLI is that if you have configured a default image during your CLI configure, it's sending an `--image` flag along with this `disk-create` that's overriding your `--file-system raw`. You can see this in action by trying to set a disk size that's smaller than what the image would want, say 1024. The image would probably require something like at least 2700 and you will get an error when trying to create the disk.

To combat this, you can use the `--no-defaults` flag. This tells the CLI to ignore the defaults set during the configure setup and only use the settings you are sending during this command.

**Comment by hzoppetti** [comment]
I also created an update to that guide with an example and note about this issue: https://github.com/linode/docs/pull/3508

**Comment by Rajakavitha1** [comment]
Closing this issue for now. Please feel free to reopen if any other changes needs to be made.
