### ISSUE TITLE
How to Install MySQL on Debian 8 Proposed Changes

### ISSUE THREAD

**Issue by tienphan1096** [linode/docs#3454]
Link: https://linode.com/docs/databases/mysql/how-to-install-mysql-on-debian-8/
## Issue
On Debian 10, `sudo apt-get install mysql-server` returns:

> Package mysql-server is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'mysql-server' has no installation candidate

## Suggested Fix
`sudo apt-get install default-mysql-server`

**Comment by Rajakavitha1** [comment]
Closing this issue for now. The updated note will appear in the website after the PR 3571 is merged. Please feel free to reopen if any other changes need to be made.
