### ISSUE TITLE
The Linode Backup Service Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#3477]
Link: https://linode.com/docs/platform/disk-images/linode-backup-service/
## Issue

No Pricing for Dedicated Linode plans

## Suggested Fix
It looks like they're the same price as the Shared plans, but there's no mention of that in this guide.

**Comment by Rajakavitha1** [comment]
@Wat-Poods  the guide now has a link to the pricing page that has details for shared, dedicated, high memory and GPU.
Closing this issue for now. Please feel to reopen if any other changes need to be made.
