### ISSUE TITLE
Linode Kubernetes Docs

### ISSUE THREAD

**Issue by edeediong** [linode/docs#3491]
I know this isn't an issue but I'd love to contribute to Linode Docs, to be more precise, I want to write on *Using Terraform to Provision a Kubernetes Cluster on Linode*. Any ideas on my next steps? Should I make the draft submission or any other thing? @nmelehan

**Comment by Rajakavitha1** [comment]
Thank you @edeediong for expressing interest in writing for Linode Docs. Here's a link that provides information about applying for Writing for Linode: https://www.linode.com/lp/write-for-linode/#write-for-linode-form.

**Comment by edeediong** [comment]
I've applied!!! Thanks, @Rajakavitha1. I'd await the response from Linode's team.

**Comment by edeediong** [comment]
I will close this now. I haven't gotten any response yet from Linode. I submitted the article idea as my writing sample so I hope it gets accepted. I've been working with Linode's Kubernetes Engine for two months now so it'd  make a lot of sense to have a Terraform setup doc on the website
