### ISSUE TITLE
An Overview of IPv6 on Linode Proposed Changes

### ISSUE THREAD

**Issue by maddentim** [linode/docs#3509]
Link: https://linode.com/docs/networking/an-overview-of-ipv6-on-linode/
## Issue
There is a broken link in the https://www.linode.com/docs/networking/an-overview-of-ipv6-on-linode/#more-information section for the ipv6 chart. Not sure what it was supposed to link to, so not sure about a fix.

**Comment by wildmanonline** [comment]
Thanks for reporting this a while ago. We've just merged a fix for this and it should be visible in the next docs release.
