### ISSUE TITLE
How to Set Up a Minecraft Server on Ubuntu or Debian

### ISSUE THREAD

**Issue by Rajakavitha1** [linode/docs#3512]
Based on the comment in DisQus : "This guide needs to be updated". https://www.linode.com/docs/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian/#comment-4998302768
Verify the steps to check if any updates need to be made.

**Comment by wildmanonline** [comment]
This guide was validated and updated recently (after this issue was submitted). See #4424. Closing this issue.
