### ISSUE TITLE
How to Install and Configure Drupal on Debian 10 Proposed Changes

### ISSUE THREAD

**Issue by ifjtoledo** [linode/docs#3535]
Link: https://linode.com/docs/websites/cms/drupal/how-to-install-and-configure-drupal-on-debian-10/
## Issue
Hello, please <Directory /var/www/html/example.com/public_html> should be changed to <Directory /var/www/html/example.com/public_html/web> drupal 8.x to 9 have a peculiar folder structure now, or i am wrong? 
## Suggested Fix
<Directory /var/www/html/example.com/public_html/web>

**Comment by Rajakavitha1** [comment]
@ifjtoledo  The path in this guide is based on the path that you set in the LAMP stack https://www.linode.com/docs/guides/how-to-install-a-lamp-stack-on-debian-10/). 

If you installed and configured your Apache server using our LAMP stack on Debian 10 guide, your document root should be located in the /var/www/html/example.com/public_html/ directory. Replace example.com with your own document root path’s name."

Closing this issue for now. Please feel free to reopen if any updates need to be made.
