### ISSUE TITLE
How to Upgrade to Ubuntu 18.04 LTS (Bionic Beaver) Proposed Changes

### ISSUE THREAD

**Issue by rasca** [linode/docs#3538]
Link: https://linode.com/docs/security/upgrading/upgrade-to-ubuntu-18-04/
## Issue

Linked URL anchor from "Applying Kernel Updates " doesn't exist:

```https://www.linode.com/docs/uptime/monitoring-and-maintaining-your-server/#applying-kernel-updates```

## Suggested Fix

It should be:

```https://www.linode.com/docs/uptime/monitoring-and-maintaining-your-server/#apply-kernel-updates```

**Comment by Rajakavitha1** [comment]
This issue has been addressed in the guide. Closing this issue now, please feel free to reopen if any other changes need to be made.
