### ISSUE TITLE
How to Install Node.js and NGINX on Debian 10 Proposed Changes

### ISSUE THREAD

**Issue by hbere** [linode/docs#3540]
Link: https://linode.com/docs/development/nodejs/how-to-install-nodejs-and-nginx-on-debian-10/
## Issue
These lines cause deployed React apps (& other basic apps) to fail because the local subfolder's .js files are not recognized, which is complicated for the beginner user to diagnose.
```
    #These lines create a bypass for certain pathnames
    #www.example.com/test.js is now routed to port 3000
    #instead of port 80
    location ~* \.(js)$ {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
    }
```

## Suggested Fix
Comment out the last four lines.
```
    #These lines create a bypass for certain pathnames
    #www.example.com/test.js is now routed to port 3000
    #instead of port 80
    #location ~* \.(js)$ {
    #    proxy_pass http://localhost:3000;
    #    proxy_set_header Host $host;
    #}
```

**Comment by Rajakavitha1** [comment]
@hbere  This guide provides example instructions for beginners to _Create Your Node.js Web Server_ using the the _test.js_ files that is also created to validate the installation https://www.linode.com/docs/development/nodejs/how-to-install-nodejs-and-nginx-on-debian-10/#create-your-node-js-web-server. With these lines commented out we may not be able to help beginners to validate the installation. Closing this issue for now. Please feel free to reopen if any other changes need to be made
