### ISSUE TITLE
How to Install and Configure FastCGI and PHP-FPM on CentOS 8 Proposed Changes

### ISSUE THREAD

**Issue by b1tw0rker** [linode/docs#3543]
Link: https://linode.com/docs/web-servers/apache/how-to-install-and-configure-fastcgi-and-php-fpm-on-centos-8/
## Suggested Fix
You have at least three errors in your article. (Which is very goog btw)
Two smaller ones and one big failure.
In CentOS the correct and predefined paths are: /run/php-fpm/www.sock NOT /var/run/php-fpm/www.sock

Your wrote:
If the listen = 127.0.0.1:9000 is not already uncommented, do so now:
But it must be only: 127.0.0.1   (without 9000)

The big failure is the following:
In the httpd.conf /etc/httpd/sites-available/example.conf you wrote:

ProxyPassMatch " ^/(.*\.php(/.*)?)$" "unix:listen = /var/run/php-fpm/example.com.sock|fcgi://localhost/var/www/html/example.com/public_html/"

But ist must be:

ProxyPassMatch " ^/(.*\.php(/.*)?)$" "unix:/run/php-fpm/example.com.sock|fcgi://localhost/var/www/html/example.com/public_html/"

Without: listen =
And also without the leading: /var

Cheers Nick

**Comment by Rajakavitha1** [comment]
updated the guide in the PR
