### ISSUE TITLE
Copy a Disk Over SSH, Finnix ssh config changed

### ISSUE THREAD

**Issue by darxmac** [linode/docs#3545]
Hi,

The current Finnex used in rescue mode has non-password root ssh access disabled, so either the guide should note that or the Finnix image used should have these settings enabled again.

(the url to the guide: https://linode.com/docs/platform/disk-images/copying-a-disk-image-over-ssh/)

Also of note is that ssh may complain about changes in host identification:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

and a hint how to remove the old host key ie. `ssh-keygen -R hostname`

**Comment by Rajakavitha1** [comment]
<img width="637" alt="Screenshot 2022-06-07 at 12 38 28 PM" src="https://user-images.githubusercontent.com/37059749/172318262-ef7640b4-e33d-407a-9720-114901337e54.png">
rebooted a linode in rescue mode and checked that ```finnix login: root (automatic)```. Marking this as closed now.
