### ISSUE TITLE
Deploy MERN with One-Click Apps Proposed Changes

### ISSUE THREAD

**Issue by tim92109** [linode/docs#3565]
Link: https://linode.com/docs/platform/one-click/deploy-mern-with-one-click-apps/
## Suggested Fix

This whole package is deprecated and trash.  Please remove from 1 click installs so others aren't wasting time too.

**Comment by Rajakavitha1** [comment]
@tim92109  we just validated the installation instructions of MERN with one-click  and it was successful. Closing the doc issue for now. Please feel free to open the issue if any changes need to be made to the documentation.
