### ISSUE TITLE
Set Up WireGuard VPN on Debian/Ubuntu Proposed Changes

### ISSUE THREAD

**Issue by asdfjkluiop** [linode/docs#3580]
Link: https://linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-debian/
Link: https://www.linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/
## Issue
These tutorials suggest the use of NAT with IPv6 however this goes against the design goal of IPv6

## Suggested Fix
Use a globally routable IPv6 block since linode offers /56 and /64 blocks for free

**Comment by Rajakavitha1** [comment]
Closing this issue for now. Checked with the development team and the suggestion was as of now the existing method works best.
