### ISSUE TITLE
Lish gateway fingerprints listings should include SHA256

### ISSUE THREAD

**Issue by lastorset** [linode/docs#363]
In the [Linode shell guide](https://www.linode.com/docs/networking/using-the-linode-shell-lish#lish-gateway-fingerprints), fingerprints are only given in MD5. For example, the RSA fingerprint for London's Lish gateway is `71:27:30:cd:dc:69:7a:fe:58:4a:04:e6:6b:5f:b4:e2`

OpenSSH clients of version 6.8 or later request [fingerprints provided in SHA256 format](http://superuser.com/a/929567) by default, instead of MD5. This applies to the latest Ubuntu. For example:

```
$ ssh -t <user>@lish-london.linode.com linode<number>
The authenticity of host 'lish-london.linode.com (178.79.153.61)' can't be established.
RSA key fingerprint is SHA256:L7sQgnpnoBwRoyIYXAFBs8SdSnwtyYmhXs1p/mQDKQM.
Are you sure you want to continue connecting (yes/no)? 
```

It's not obvious what the user should do in this situation. I recommend listing the SHA256 fingerprint as well.

As a workaround, you can force your SSH client to use the MD5 fingerprint like this:

```
ssh -o FingerprintHash=md5  # …etc
```

**Comment by alexfornuto** [comment]
Good point! I'll look into an update shortly.

**Comment by jbclements** [comment]
+1

**Comment by alexfornuto** [comment]
https://github.com/linode/docs/commit/6b5727b9165623fb4d732429403745e20d37a935

Thanks guys!
