### ISSUE TITLE
How to Deploy NGINX Ingress on Linode Kubernetes Engine Proposed Changes

### ISSUE THREAD

**Issue by bjorm** [linode/docs#3683]
Link: https://linode.com/docs/kubernetes/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/
## Issue
The helm chart mentioned in the documentation is deprecated:
```
$ helm repo add stable https://kubernetes-charts.storage.googleapis.com/
"stable" has been added to your repositories
$ helm install nginx-ingress stable/nginx-ingress --set controller.publishService.enabled=true
WARNING: This chart is deprecated
^C
```

## Suggested Fix
Use the repo mentioned at https://kubernetes.github.io/ingress-nginx/deploy/#using-helm:
```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm install my-release ingress-nginx/ingress-nginx
```

**Comment by Rajakavitha1** [comment]
Thanks for reporting the issue @bjorm . We also validated the fix that you suggested and updated the guide.
Here's the PR:https://github.com/linode/docs/pull/3812

**Comment by Rajakavitha1** [comment]
Here's the preview of the updates made:https://deploy-preview-3812--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/
Closing this issue for now. Please feel free to reopen if any other changes need to be made.
