### ISSUE TITLE
Install MediaWiki on Ubuntu 18.04 Proposed Changes

### ISSUE THREAD

**Issue by ApopheniaPays** [linode/docs#3706]
Link: https://linode.com/docs/websites/wikis/install-mediawiki-on-ubuntu-1804/
## Issue
These instructions are false. 

## Suggested Fix
Either post working instructions that result in a working install of MediaWiki on an Ubuntu 18.04 linode, instead of producing a page that says "<?php // For broken web servers: ><pre> If you are reading this in your web browser, your server is probably not configured correctly to run PHP applications!", etc., with absolutely no solution available on your site or anywhere that I can find on the web. Or, alternatively, post no instructions at all. 

Lengthy, time-consuming instructions that don't actually work are the worst of both worlds, and 100% unacceptable to me as a user.

**Comment by Rajakavitha1** [comment]
@ApopheniaPays We are sorry that the instructions provided in the guide was not working for you. Could you confirm if that you already have a working LAMP stack running on Ubuntu. Your web accessible DocumentRoot is located in /var/www/html/example.com/public_html/. You should be connected to your server via SSH and logged in as root. This will help us investigate the issue and update the document accordingly.

**Comment by Rajakavitha1** [comment]
Closing this issue for now. There is an updated guide for Ubuntu 20.04:https://github.com/linode/docs/pull/3879.

Please feel free to reopen if any other changes need to be made.
