### ISSUE TITLE
Secure HTTP Traffic with Certbot Proposed Changes

### ISSUE THREAD

**Issue by tcveatch** [linode/docs#3748]
Link: https://www.linode.com/docs/guides/secure-http-traffic-certbot/
## Issue
The following commands:

  % add-apt-repository ppa:certbot/certbot
  % apt update

produce errors for Ubuntu after 16.04 which is the latest for which that ppa is working, according to 

https://www.reddit.com/r/linux4noobs/comments/ducn4k/how_to_fix_404_not_found_ip_911899583_80/

## Suggested Fix

Annotate the above quoted commands with: SKIP THESE TWO STEPS FOR UBUNTU VERSIONS AFTER 16.04

**Comment by Rajakavitha1** [comment]
This is a deprecated guide and no longer maintained. You may want to check out latest guide:https://www.linode.com/docs/guides/how-to-install-certbot-on-ubuntu-18-04/

We did validate these steps on Ubuntu 18.04 and Ubuntu 16.04. Here are the screenshots for your reference.
![Screenshot 2020-11-24 at 7 28 17 PM](https://user-images.githubusercontent.com/37059749/100103966-93352e80-2e8b-11eb-9494-be48734947f3.png)
![Screenshot 2020-11-24 at 7 28 17 PM](https://user-images.githubusercontent.com/37059749/100103996-9a5c3c80-2e8b-11eb-882f-f9affeedec39.png)

We did not notice and errors. Closing this issue for now. Please feel free to reopen if any other changes need to be made.
