### ISSUE TITLE
Rescue and Rebuild Proposed Changes

### ISSUE THREAD

**Issue by robsheldon** [linode/docs#3789]
Link: https://www.linode.com/docs/guides/rescue-and-rebuild/
## Issue
In the "Mounting Disks" section, rescue mode / Finnix no longer appears to be adding entries for a Linode's disk partitions in Finnix's fstab, and the /media directory is empty. I double-checked that the disks were shown correctly in the Rescue tab for the Linode in the Cloud Manager.

Creating a mount point and specifying it in `mount` did the trick just fine.

## Suggested Fix

Either fix the rescue mode startup to correctly add disks to Finnix's /etc/fstab, or update this section of the documentation to describe creating and specifying mount points.

**Comment by Rajakavitha1** [comment]
@robsheldon 
Thank you for raising the issue. We just added a note in the documentation that reads: {{< note >}}
  Before you mount the disk check the location of the root partition in the `/etc/fstab` file and update it accordingly. In the following example `/dev/sda` is the location of the disk. For more information, see [Update your fstab] (/docs/guides/install-a-custom-distribution-on-a-linode/#update-your-fstab).{{< /note >}} 

You may want to check the PR: https://github.com/linode/docs/pull/3760 for more information. The changes would reflect in the website when the PR is merged.

Closing this PR for now. Please feel free to reopen if any other changes need to be made.
