### ISSUE TITLE
Pydio for Ubuntu 14.04?

### ISSUE THREAD

**Issue by seanthewebber** [linode/docs#379]
@cwlinode Interested in a [Pydio file explorer](https://pydio.com/) installation guide for Ubuntu 14.04?

**Comment by alexfornuto** [comment]
@seanthewebber We emailed you back when you first asked us this over email:

```
Hi Sean,

A comprehensive Pydio guide with MySQL at the backend would be great. Were you thinking of using Apache or a different web server?
```

Are you talking about the same guide or something different?

**Comment by seanthewebber** [comment]
@alexfornuto I never received that email... strange. Oh well. I was thinking of LAMP on Ubuntu 14.04, my usual stack.

**Comment by cwlinode** [comment]
@seanthewebber Sounds good. I look forward to reviewing it.
