### ISSUE TITLE
Outdated CentOS 8 End-of-Life

### ISSUE THREAD

**Issue by Kr4ken-9** [linode/docs#3846]
Link: https://www.linode.com/distributions/

# Issue

Recently, CentOS has updated the EOL for CentOS 8 from 2029 to December 31st, 2021
https://blog.centos.org/2020/12/future-is-centos-stream/

# Suggested Fix

Change the EOL date from 2029 to December 31st, 2021.

**Comment by Rajakavitha1** [comment]
Thanks for raising the issue @Kr4ken-9 . We just updated the page with the EOL date. 
https://www.linode.com/distributions/

Closing the issue for now, please feel free to reopen if any other changes need to be made.
