### ISSUE TITLE
portainer image update

### ISSUE THREAD

**Issue by balasu** [linode/docs#3886]
Hi

Portainer Image used on below link is old, kindly update to portainer/portainer-ce. that will run portainer 2.0. also pl include for further documentation to refer https://documentation.portainer.io/

https://www.linode.com/docs/guides/use-a-linode-for-web-development-on-remote-devices/
![image](https://user-images.githubusercontent.com/39425180/103997795-8497a200-51c1-11eb-8328-d34033d426dd.png)

**Comment by Rajakavitha1** [comment]
Hi @balasu , The changes that you suggested are now addressed in https://github.com/linode/docs/pull/3917.

Closing this issue for now, please feel free to reopen if any other changes need to be made.

**Comment by balasu** [comment]
Thanks @Rajakavitha1
