### ISSUE TITLE
How to Enable Third Party Authentication on Your Linode Account Proposed Changes

### ISSUE THREAD

**Issue by martinnoyer** [linode/docs#3894]
Link: https://www.linode.com/docs/guides/third-party-authentication/

**Comment by Rajakavitha1** [comment]
Hi @martinnoyer ,

Please provide information about the issue that you faced and the fix if any any.

**Comment by Rajakavitha1** [comment]
Closing this issue for now. Please feel free to reopen the issue with the details of the issue that you faced.
