### ISSUE TITLE
Configure Postfix to Send Email Using External SMTP Servers Proposed Changes

### ISSUE THREAD

**Issue by bitwombat** [linode/docs#3915]
Link: https://www.linode.com/docs/guides/postfix-smtp-debian7/
## Issue
Bad quotes and typo in example command

## Suggested Fix
```
echo  "body of your email" | mail -s "This is a subject" -a "From:you@example.com" recipient@elsewhere.com
```

**Comment by Rajakavitha1** [comment]
Thank you @bitwombat for raining the issue. We just updated the guide and here's the preview of the changes that were made:https://deploy-preview-3941--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/postfix-smtp-debian7/. The updated changes will appear in the website after the PR is merged.
