### ISSUE TITLE
Get Started CLI "Install the CLI" section does not contain installing CLI information

### ISSUE THREAD

**Issue by bdha** [linode/docs#3928]
Link: https://www.linode.com/docs/products/tools/cli/get-started/

## Issue

The `Install the CLI` section does not explain how to install the CLI, but jumps right to listing support tickets.

**Comment by Rajakavitha1** [comment]
Thank you for raising the issue. We just updated the document and here's the preview:https://deploy-preview-3934--nostalgic-ptolemy-b01ab8.netlify.app/docs/products/tools/cli/get-started/
The updated changes will reflect in the website after the PR is merged.
