### ISSUE TITLE
How to Secure Your Server Proposed Changes

### ISSUE THREAD

**Issue by rmcaninch** [linode/docs#3951]
Link: https://www.linode.com/docs/guides/securing-your-server/
## Issue
Add the user to the sudo group so you’ll have administrative privileges:
adduser example_user sudo

This doesn't work to add the user to sudo group.

## Suggested Fix

usermod -aG sudo  example_user

**Comment by Rajakavitha1** [comment]
Hi @rmcaninch , If you are trying this on CentOS or Fedora we have the step documented in the "CentOS / Fedora " section.
Closing this issue for now. Please feel free to reopen if any other changes need to be made.
