### ISSUE TITLE
How to Install Certbot for TLS on Ubuntu 18.04 Proposed Changes

### ISSUE THREAD

**Issue by 3ricG** [linode/docs#3952]
Link: https://www.linode.com/docs/guides/how-to-install-certbot-on-ubuntu-18-04/
## Issue
When attempting to add the PPA in step 1, the following message is presented:

>  The PPA has been DEPRECATED.
> 
> To get up to date instructions on how to get certbot for your systems, please see https://certbot.eff.org/docs/install.html.
>  More info: https://launchpad.net/~certbot/+archive/ubuntu/certbot
> Press [ENTER] to continue or ctrl-c to cancel adding it

## Suggested Fix
Link to the official certbot install docs, then provide additional notes based on Linode suggestions.

**Comment by Rajakavitha1** [comment]
Closing this issue because this has now been addressed in https://github.com/linode/docs/pull/4339
