### ISSUE TITLE
Update Notes - "Run a Custom Distro on a KVM Linode"

### ISSUE THREAD

**Issue by felicianotech** [linode/docs#396]
Hey guys, these are just some notes of my most recent run through for this guide. Take what you like otherwise just close.
- Create the Virtual Machine: Step 4: This step doesn't need to be as long as it is. On first run, VirtualBox is smart enough to know that you don't have an install ISO mounted and will prompt you to choose one. I find going that route to be much faster than doing it manually as this step suggest. Also, doing it this way means VirtualBox will automatically remove the ISO after install as well.
- Disk image size: The latest release of the current LTS, Ubuntu 14.04.4 required more than 2GB for the disk size. Obviously this varies by distro but I predict the next LTS to be bigger than this one, so maybe the screenshot of a 2GB disk leads people on?
- upload command: I changed this out for something that will make the upload a bit fast (gzip and block size): `dd if=/dev/sda1 bs=64K | gzip -c | pv | ssh root@12.34.56.78 "gunzip -c | dd of=/dev/sda"`
- There are no instructions here on how the user can have their distro use the Linode Repository Mirrors if they want to.
- I also took this opportunity to pre-load the distro with my SSH key so I can freeze the image and deploy from it whenever I want w/ access already.

I hope something here is useful.

**Comment by brewn** [comment]
Thanks @felicianotech, I've been wanting to get a new version of this guide out for a while, and this once has finally been replaced:

https://www.linode.com/docs/tools-reference/custom-kernels-distros/install-a-custom-distribution-on-a-linode/

The mirrors suggestion could be useful, so I'll see about adding this in somewhere.
