### ISSUE TITLE
Configure Your Linode for Reverse DNS (rDNS) Proposed Changes

### ISSUE THREAD

**Issue by nmelehan** [linode/docs#4015]
Link: http://localhost:1313/docs/guides/configure-your-linode-for-reverse-dns/
## Issue

Broken image links on these lines:
https://github.com/linode/docs/blame/develop/docs/guides/networking/dns/configure-your-linode-for-reverse-dns/index.md#L68
https://github.com/linode/docs/blame/develop/docs/guides/networking/dns/configure-your-linode-for-reverse-dns/index.md#L72

## Suggested Fix
Fix the markdown image syntax

**Comment by wildmanonline** [comment]
Address in PR #4341
