### ISSUE TITLE
Using the Linode CLI Proposed Changes

### ISSUE THREAD

**Issue by alexfornuto** [linode/docs#4091]
Link: https://www.linode.com/docs/guides/linode-cli/

## Issue
The image and description for setting up a new install of Linode CLI with a token does not match the current behavior. Currently, the cli prompts you to authenticate through the web browser, and requires the arguments `configure --token` to authenticate with a token.

And while it's not directly related, it's worth pointing out that the CLI asks you to set a default Linode type using machine names that I could not find analogues for in the pricing pages on the main site.

## Suggested Fix
Update the `#install-the-cli` section to match the current behavior of the software.

**Comment by Rajakavitha1** [comment]
This has now been addressed in the PR 4294. Marking the issue as closed. Please feel to reopen if any other changes need to be made.

**Comment by alexfornuto** [comment]
You're welcome.
