### ISSUE TITLE
No instructions to install the Linode CLI in Getting Started

### ISSUE THREAD

**Issue by codematix** [linode/docs#4121]
Link: https://www.linode.com/docs/products/tools/cli/get-started/
## Issue

There is a title in Getting started section called "Install the CLI" but there is no actual instructions on how to install the `linode-cli`.

## Suggested Fix

Please update the instructions to clarify how to actually install the `linode-cli` on a Linux/macOS/Windows machine.

**Comment by Rajakavitha1** [comment]
This has now been addressed in the PR 4294. Marking the issue as closed. Please feel to reopen if any other changes need to be made.
