### ISSUE TITLE
How Linode Billing Works Proposed Changes

### ISSUE THREAD

**Issue by gusax54** [linode/docs#4231]
Link: https://www.linode.com/docs/guides/how-linode-billing-works/
## Issue
Every month 1st of the month 7.70 US dollars Linode 8554546633 PA US card xx5263 gets charged to my work credit card and I have no record of what this is????

## Suggested Fix
Can someone contact me on my email jchambers@abe.edu.au tell me what this transaction Linode 8554546633 is so I can get is taken off my work credit card.

**Comment by Rajakavitha1** [comment]
@gusax54  you may want to contact the Linode support team and report the issue. Check https://www.linode.com/support/

**Comment by Rajakavitha1** [comment]
@gusax54 marking this issue as closed now.  Please feel free to reopen if there are any documentation related issues.
