### ISSUE TITLE
Installing Nginx in Ubuntu 12.04 workstation. Is it Possible to Install, Because i'm newbiee, Thanks in advance for the answer.

### ISSUE THREAD

**Issue by mohanrajsambath** [linode/docs#424]
next@NEXT-IN-WS010:~$ wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
[sudo] password for next: 
Sorry, try again.
[sudo] password for next: 
gpg: no valid OpenPGP data found.
next@NEXT-IN-WS010:~$ wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
gpg: no valid OpenPGP data found.
next@NEXT-IN-WS010:~$ ^C
next@NEXT-IN-WS010:~$ clear

next@NEXT-IN-WS010:~$ wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
[sudo] password for next: 
gpg: no valid OpenPGP data found.
next@NEXT-IN-WS010:~$ ^C
next@NEXT-IN-WS010:~$ gpg bind-9.9.4.tar.gz.sha1.asc.
gpg: can't open `bind-9.9.4.tar.gz.sha1.asc.'
next@NEXT-IN-WS010:~$ $ cd /tmp
$: command not found
next@NEXT-IN-WS010:~$ cd /tmp
next@NEXT-IN-WS010:/tmp$ wget http://nginx.org/download/nginx-0.8.35.tar.gz
--2016-03-29 16:51:17--  http://nginx.org/download/nginx-0.8.35.tar.gz
Connecting to 192.168.10.1:3128... connected.
Proxy request sent, awaiting response... 407 Proxy Authentication Required
2016-03-29 16:51:17 ERROR 407: Proxy Authentication Required.

next@NEXT-IN-WS010:/tmp$ cd
next@NEXT-IN-WS010:~$ cleat
No command 'cleat' found, did you mean:
 Command 'clear' from package 'ncurses-bin' (main)
cleat: command not found
next@NEXT-IN-WS010:~$ clear

next@NEXT-IN-WS010:~$ sudo apt-get install nginx
[sudo] password for next: 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following extra packages will be installed:
  nginx-common nginx-full
The following NEW packages will be installed:
  nginx nginx-common nginx-full
0 upgraded, 3 newly installed, 0 to remove and 239 not upgraded.
Need to get 402 kB of archives.
After this operation, 1,229 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
WARNING: The following packages cannot be authenticated!
  nginx-common nginx-full nginx
Install these packages without verification [y/N]? y
Err http://in.archive.ubuntu.com/ubuntu/ precise-updates/universe nginx-common all 1.1.19-1ubuntu0.8
  407  Proxy Authentication Required
Err http://in.archive.ubuntu.com/ubuntu/ precise-updates/universe nginx-full amd64 1.1.19-1ubuntu0.8
  407  Proxy Authentication Required
Err http://in.archive.ubuntu.com/ubuntu/ precise-updates/universe nginx all 1.1.19-1ubuntu0.8
  407  Proxy Authentication Required
Failed to fetch http://in.archive.ubuntu.com/ubuntu/pool/universe/n/nginx/nginx-common_1.1.19-1ubuntu0.8_all.deb  407  Proxy Authentication Required
Failed to fetch http://in.archive.ubuntu.com/ubuntu/pool/universe/n/nginx/nginx-full_1.1.19-1ubuntu0.8_amd64.deb  407  Proxy Authentication Required
Failed to fetch http://in.archive.ubuntu.com/ubuntu/pool/universe/n/nginx/nginx_1.1.19-1ubuntu0.8_all.deb  407  Proxy Authentication Required
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
next@NEXT-IN-WS010:~$

**Comment by omps** [comment]
Check here. 
https://www.linode.com/docs/websites/nginx/

**Comment by pbzona** [comment]
Hi @mohanrajsambath, please see our guide on this topic: 

https://www.linode.com/docs/websites/nginx/installing-nginx-on-ubuntu-12-04-lts-precise-pangolin

I'll be closing the issue, hope this is helpful!
