### ISSUE TITLE
Documentation update - not a bug

### ISSUE THREAD

**Issue by drfish** [linode/docs#430]
Ok so I'm relatively knew to actually having a github account, so creating an issue may be the wrong way to do this.
However there's an additional troubleshooting step you need for the upgrade to debian 8 guide (docs/docs/security/upgrading/upgrade-to-debian-8-jessie.md) that I felt was worth passing on (especially for people who use something like virtualmin)

If you use quotas and come from wheezy at least, the quota package will still be installed but it'll throw all manner of fun errors about not being able to stat /dev/root/ 
After some digging, you have to create a symlink for it and recreate the quota file (someone may know how to back it up prior to the upgrade but it's too late for me _sigh_
`ln -s /dev/sda /dev/root/`

After that you can recreate the quota index & re-enable quotas:
`quotacheck -cum /`
`quotaon /`

**Comment by cwlinode** [comment]
Thank you for bringing this up.

We will add a note that there is always a small risk to consider when performing upgrades, but troubleshooting packages more in depth is beyond the scope of the guide.
