### ISSUE TITLE
How to Configure Automated Security Updates on Debian Proposed Changes

### ISSUE THREAD

**Issue by tcv-git** [linode/docs#4311]
Link: https://www.linode.com/docs/guides/how-to-configure-automated-security-updates-debian/
## Issue

The page incorrectly says:

Update-Package-Lists: 1 enables auto-update, 0 disables.
Unattended-Upgrade: 1 enables auto-upgrade, 0 disables.

## Suggested Fix

These are both integer numbers of days after which to run the respective command.

The documentation for these variables and other related ones is in the script `/usr/lib/apt/apt.systemd.daily`

**Comment by Rajakavitha1** [comment]
Hello@tcv-git!!!
Thank you for the suggestion and we just validated it against the offcicial Debian documentation:https://wiki.debian.org/UnattendedUpgrades?action=fullsearch&context=180&value=update-package-lists&titlesearch=Titles#Automatic_call_via_.2Fetc.2Fapt.2Fapt.conf.d.2F20auto-upgrades. The integer '1' enables the option and '0' disables the option. Marking this issue as closed now. Please feel free to reopen if any other changes need to be made to the Linode documentation.

**Comment by tcv-git** [comment]
The debian wiki is not the official documentation. It is a wiki, which means any idiot can edit it.

It is a very antisocial and irresponsible thing to do to copy and paste something that you found on a random website with no authorship information without reading the source of the software it is for.

This is a very simple shell script.  You could read the source code of it quicker than you can search on google for random misinformation.

**Comment by tcv-git** [comment]
Even the page you linked to says you are wrong.  Try reading it again, but this time with your eyes open.

    "Do apt-get update" automatically every n-days (0=disable)"
