### ISSUE TITLE
NVIDIA Driver CUDA Installation Proposed Changes

### ISSUE THREAD

**Issue by eliasvc** [linode/docs#4344]
Link: https://www.linode.com/docs/products/compute/gpu/guides/install-nvidia-drivers-with-cuda/
## Issue
Driver fails to install due to lack of gcc, make, and possibly the kernel version. I tested this on fresh Ubuntu 20.04, and 18.04 Linodes.

## Suggested Fix

Installing gcc and make will resolve it:

`apt update && apt install gcc make` 

In terms of the kernel, fresh Linode Ubuntu 18.04 and 20.04 Images come with kernels 4.15 and 5.4, respectively. According to the CUDA's requirements, Ubuntu 18.04 needs kernel 5.4+ and Ubuntu 20.04 needs 5.10+. In both cases, following the instructions failed for me when I didn't meet that requirement.  I think the guide should probably direct the user to NVIDIA CUDA's doc page so they can check if they meet the kernel requirement:

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

Also, users could benefit from instructions on how to install another kernel (or a link to a resource that contains those instructions).

**Comment by Rajakavitha1** [comment]
Thanks @eliasvc . We update the changes that you suggested in https://github.com/linode/docs/pull/4502. The changes will appear in the website after the PR is merged.

**Comment by Rajakavitha1** [comment]
Closing this issue for now. Feel free to reopen if any other issue needs to be addressed.
