### ISSUE TITLE
How to Deploy NGINX Ingress on Linode Kubernetes Engine Proposed Changes

### ISSUE THREAD

**Issue by lnguyen** [linode/docs#4366]
Link: https://www.linode.com/docs/guides/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/
## Issue
```
helm repo add stable https://charts.helm.sh/stable
```
isn't correct to install nginx with helm
## Suggested Fix
```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
```
 should be correct repo

**Comment by Rajakavitha1** [comment]
Hi @lnguyen  I just checked our latest guide:https://www.linode.com/docs/guides/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/ and it does seem to have the updated repo information.
<img width="886" alt="Screenshot 2021-07-09 at 5 21 32 PM" src="https://user-images.githubusercontent.com/37059749/125073907-43ce0680-e0da-11eb-82ba-0ad48bdf9d29.png">
Closing this issue for now. Please feel free to reopen if any other updates need to be made.
