### ISSUE TITLE
Secrets Management page missing

### ISSUE THREAD

**Issue by radosslav** [linode/docs#4372]
Hello.

I just want to note that the Secrets Management page listed on the Security section is missing:

[https://www.linode.com/docs/guides/security/](https://www.linode.com/docs/guides/security/)

The section is the last on the list, right next to System Recovery.

**Comment by Rajakavitha1** [comment]
Thank you @radosslav !! Closing the issue for now. Please feel free to reopen if any other changes need to be made.
PS: We still need to add the image on the card.
