### ISSUE TITLE
Manage Billing in Cloud Manager Proposed Changes

### ISSUE THREAD

**Issue by zrishti** [linode/docs#4410]
Link: https://www.linode.com/docs/guides/manage-billing-in-cloud-manager/
## Suggested Fix

I am trying to delete my credit card information from linode account. I am not able to figure this out. I do not have any outstanding payments, i do not have any nodes. I did not want to close the account without being able to delete my card details.
Not able to find that out.

**Comment by Rajakavitha1** [comment]
Hi @zrishti, 
At any point in time your account has to be associated with a credit card to remain active. 
As mentioned in the "Cancelling your account" section of https://www.linode.com/docs/guides/manage-billing-in-cloud-manager/ "Any past due balance and uninvoiced balance will now be charged to the credit card on file for your account. After that, you will receive no further charges from Linode regarding this account.
Your account will be cancelled and all of your services will be deactivated." Closing this issue for now. Please feel free to reopen if any other changes need to be made to the guide.
