### ISSUE TITLE
How to Set up tinc, a Peer-to-Peer VPN Proposed Changes

### ISSUE THREAD

**Issue by ronandalton** [linode/docs#4503]
Link: https://www.linode.com/docs/guides/how-to-set-up-tinc-peer-to-peer-vpn/
## Issue
Potentially incorrect VPN IP address in `02. Basic Setup: Two Node tinc VPN` - `E. Create VPN Control Scripts`: database server tinc-down script. The `ip addr del` command in this script references the IP of the application server instead of the database server.

## Suggested Fix
Change `192.168.100.209` to `192.168.100.130` in https://www.linode.com/docs/guides/how-to-set-up-tinc-peer-to-peer-vpn/#create-vpn-control-scripts step 2 - shutdown script.

**Comment by Rajakavitha1** [comment]
Closing this issue for now. The [PR ](https://github.com/linode/docs/pull/4982) addresses the issue.
