### ISSUE TITLE
How to Self-Host the bitwarden_rs Password Manager Proposed Changes

### ISSUE THREAD

**Issue by francislavoie** [linode/docs#4573]
Link: https://www.linode.com/docs/guides/how-to-self-host-the-bitwarden-rs-password-manager/

## Issue
This guide suggests pulling a Caddy Docker image by using `sudo docker pull caddy/caddy:alpine`. `caddy/caddy` is not the official Docker image for Caddy, and is not maintained. 

## Suggested Fix
This should be changed to `sudo docker pull caddy:2`, or even better, explain that the version should be pinned.

See https://hub.docker.com/_/caddy for the official Docker image for Caddy. Please review the documentation there for how to correctly set up docker volumes.

---

As an aside, that guide is outdated, because `bitwarden_rs` no longer exists, it's now called "vaultwarden". See https://github.com/dani-garcia/vaultwarden

This guide needs to either be completely rewritten, or deleted altogether.

**Comment by andystevensname** [comment]
We have this guide queued up to be edited to include the official version of Caddy.
