### ISSUE TITLE
An Overview of IPv6 on Linode Proposed Changes

### ISSUE THREAD

**Issue by stvnjacobs** [linode/docs#4583]
Link: https://www.linode.com/docs/guides/an-overview-of-ipv6-on-linode/

## Issue

The external link to the IPv6 chart in the [More Information](https://www.linode.com/docs/guides/an-overview-of-ipv6-on-linode/#more-information) section is broken.

## Suggested Fix

Fix the link to the IPv6 chart.

It may also be nice to find similar material that is not a PDF. If it remains a PDF, some users may like to know they are about to download a PDF before clicking the link. This can be done with as little as adding a '[PDF]` in the link text. I have also seen a badge to signify a link is a PDF document or other file type that will trigger a download.

**Comment by wildmanonline** [comment]
Thanks for reporting this @stvnjacobs! A fix for this has been merged and should be on the live site shortly.
