### ISSUE TITLE
The "How to Set Up a Docker Registry with LKE and Object Storage" results in deprecation warnings has broken links

### ISSUE THREAD

**Issue by dkam** [linode/docs#4668]
Hi guys, 
    Thanks for writing the LKE / Kubernetes guides.  I'm just getting started with k8s and they've been super helpful.

It seems one of the first steps in migrating an application to K8s is to setup ( or buy! ) a docker registry, so I'm currently working my way through setting up a [private docker registry](https://www.linode.com/docs/guides/how-to-setup-a-private-docker-registry-with-lke-and-object-storage/) guide.

It's concerning to see deprecation warnings like this while installing nginx-ingress:

**DEPRECATED, please use https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx**

In the section ** Configure your Docker Registry**, there's a [link](https://artifacthub.io/packages/helm/stable/docker-registry) to the official documentation which is now a 404. 

Searching the `artifacthub.io` for (docker-registry)[https://artifacthub.io/packages/search?ts_query_web=docker-registry&sort=relevance&page=1] lists several "docker-registry"with security ratings of "F".

When installing with `helm install docker-registry stable/docker-registry -f docker-configs.yaml`

**WARNING: This chart is deprecated**

It's a useful guide, but it looks like it might be a bit out of date and I wouldn't feel confident using this specific guide in production. 

Thanks again for the guides,
Dan

**Comment by Rajakavitha1** [comment]
Thanks @dkam  for raising the issue. This has got to do with the Deprecation Notice for docker-registry [](https://github.com/helm/charts/tree/master/stable/docker-registry). The migration to new repo for docker-registry is still in progress:[ ] (https://github.com/helm/charts/issues/21103). We will update the documents with the official link after the chart finds a new repo officially.

**Comment by Rajakavitha1** [comment]
Closing this issue for now. Please feel free to reopen if any other updates need to be made.
