### ISSUE TITLE
API docs for /object-storage/transfer says GB but seems to be bytes

### ISSUE THREAD

**Issue by mherrmann** [linode/docs#4687]
The [sample response](https://www.linode.com/docs/api/object-storage/#object-storage-transfer-view__responses) for the `/object-storage/transfer` currently says the following about the returned `use` value:

> The amount of outbound data transfer used by your account’s Object Storage buckets, **in GB**

Looking at the values returned by the API, I think the endpoint actually returns bytes, not GB. I think the above text should be updated by replacing "in GB" by "in bytes".

**Comment by bbiggerr** [comment]
Thanks for the report -- API docs have been updated.
