### ISSUE TITLE
sph_ prefix on link ids

### ISSUE THREAD

**Issue by amayer5125** [linode/docs#478]
There are 308 links on 227 pages that have an id with the prefix `sph_`. Ive tried a couple of them at random and none of them seem to point to the correct section. If I remove the `sph_` the page jumps to the correct header. Im not sure if this is something left over? or if it serves a special purpose?
I can go through and replace them, but I want to make sure Im not removing something that is there for a reason.

**Comment by alexfornuto** [comment]
Hi @amayer5125. What you're seeing is a relic from the previous incarnation of the Linode docs, when they lived in a different CMS at `library.linode.com`. That's something we try to correct whenever we see it, but have not had the time to do a mass find and replace.

Each `sph_` link pointed to another section in the same article. They can be replaced with the appropriate section's header, substituting `-` for spaces. Here's an example from our Securing Your Server guide:

```
For example, let's say we want to insert a rule to [the ruleset above](#basic-iptables-rulesets-for-ipv4-and-ipv6)
```

**Comment by amayer5125** [comment]
I might have some time to go through and find these. Ill let you know what I find.
