### ISSUE TITLE
How to Set Up Rook NFS for Persistent Storage on LKE Proposed Changes

### ISSUE THREAD

**Issue by Nader-Alabed** [linode/docs#4974]
Link: https://www.linode.com/docs/guides/how-to-install-rooknfs-on-lke/
## Suggested Fix
**I followed this guide but return this error:**
---------------------
error: unable to recognize "common.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
------------------------
**I'm trying to create a PVC to install mariadb which return this error with the pod description:**
----------------------------
kubectl describe pods mariadb-0 -n mariadb
Name: mariadb-0
Namespace: mariadb
Priority: 0
Node: lke46013-73844-61b341c20012/192.168.178.79
Start Time: Sat, 11 Dec 2021 06:44:48 +0300
Labels: app.kubernetes.io/component=primary
app.kubernetes.io/instance=mariadb
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=mariadb
controller-revision-hash=mariadb-864f9648c
helm.sh/chart=mariadb-10.1.0
statefulset.kubernetes.io/pod-name=mariadb-0
Annotations: checksum/configuration: 781a0a6f53555a0b763d33c5beb29f18910843d50c19be23d8912d068b98236d
Status: Pending
IP:
IPs:
Controlled By: StatefulSet/mariadb
Containers:
mariadb:
Container ID:
Image: docker.io/bitnami/mariadb:10.5.13-debian-10-r18
Image ID:
Port: 3306/TCP
Host Port: 0/TCP
State: Waiting
Reason: ContainerCreating
Ready: False
Restart Count: 0
Liveness: exec [/bin/bash -ec password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [[ -f “${MARIADB_ROOT_PASSWORD_FILE:-}” ]]; then
password_aux=$(cat “$MARIADB_ROOT_PASSWORD_FILE”)
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=120s timeout=1s period=10s #success=1 #failure=3
Readiness: exec [/bin/bash -ec password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [[ -f “${MARIADB_ROOT_PASSWORD_FILE:-}” ]]; then
password_aux=$(cat “$MARIADB_ROOT_PASSWORD_FILE”)
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=30s timeout=1s period=10s #success=1 #failure=3
Environment:
BITNAMI_DEBUG: false
MARIADB_ROOT_PASSWORD: <set to the key ‘mariadb-root-password’ in secret ‘mariadb’> Optional: false
MARIADB_USER: nader
MARIADB_PASSWORD: <set to the key ‘mariadb-password’ in secret ‘mariadb’> Optional: false
MARIADB_DATABASE: alfalehtech
Mounts:
/bitnami/mariadb from data (rw)
/opt/bitnami/mariadb/conf/my.cnf from config (rw,path=“my.cnf”)
Conditions:
Type Status
Initialized True
Ready False
ContainersReady False
PodScheduled True
Volumes:
data:
Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName: data-mariadb-0
ReadOnly: false
config:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: mariadb
Optional: false
QoS Class: BestEffort
Node-Selectors:
Tolerations: node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
Type Reason Age From Message

Normal Scheduled 21m default-scheduler Successfully assigned mariadb/mariadb-0 to lke46013-73844-61b341c20012
Warning FailedMount 5m39s (x5 over 19m) kubelet Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data config]: timed out waiting for the condition
Warning FailedMount 66s (x4 over 17m) kubelet Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[config data]: timed out waiting for the condition
Warning FailedAttachVolume 47s (x18 over 21m) attachdetach-controller AttachVolume.Attach failed for volume “pvc-5d39474d69b64f80” : rpc error: code = NotFound desc = Volume with id 225565 not found

-------------------------------------------------------
**I appreciate your contribution in this regards,**

**Comment by Rajakavitha1** [comment]
Hi @Nader-Alabed Thank you for raising the issue. This guide provides instruction to Deploy the PVC, busybox, and web-rc server. You may want to post this question on [ Linode Q/A](https://www.linode.com/community/questions/). On Linode community, you have access to a much larger audience who can answer and give advice regarding your specific use case. Please do not hesitate to log a ticket on https://cloud.linode.com/support/tickets if you need further assistance. Closing this issue for now. Please feel free to reopen if there are any other issues in the guide.
