### ISSUE TITLE
How to install docker registry with helm

### ISSUE THREAD

**Issue by Nahasean94** [linode/docs#5153]
I am following the documentation in [this page](https://www.linode.com/docs/guides/how-to-setup-a-private-docker-registry-with-lke-and-object-storage/#configure-your-docker-registry) and towards the bottom there is this code

`helm install docker-registry stable/docker-registry -f docker-configs.yaml`

When i run it, i get this error

`WARNING: This chart is deprecated Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"`

Is there an update to this guide or is there something that am missing?

**Comment by Rajakavitha1** [comment]
Thanks for the update @Nahasean94 !!! I will mark this issue as closed for now. Please feel free to reopen if any other changes need to be made.
