### ISSUE TITLE
not recommended recommendations in using-fail2ban-for-security.md

### ISSUE THREAD

**Issue by yarikoptic** [linode/docs#518]
in fail2ban we do not recommend to just 'cp jail.conf jail.local' and do modifications.  .local files should provide only customizations, overriding settings in jail.conf.  Please adjust the page accordingly.

**Comment by cgsmith** [comment]
@yarikoptic This https://github.com/linode/docs/blob/master/docs/security/using-fail2ban-for-security.md#configuring-fail2ban

Shows the following note:

> Fail2ban reads its configuration files so that all .conf files are read first and .local files override any settings. Because of this, all changes to the configuration are generally done in .local files, leaving the .conf files untouched.

**Comment by alexfornuto** [comment]
@yarikoptic thanks for bringing this to our attention! Would you mind taking a look at https://github.com/linode/docs/pull/557 to see if it satisfies your concerns properly?

**Comment by alexfornuto** [comment]
@yarikoptic since https://github.com/fail2ban/fail2ban/issues/1396 is closed for further commenting so I can't ask there, please feel free to check off the Linode todo at your leisure.
