### ISSUE TITLE
Deploying Webuzo through the Linode Marketplace Proposed Changes

### ISSUE THREAD

**Issue by psyfi** [linode/docs#5199]
Link: https://www.linode.com/docs/guides/webuzo-marketplace-app/
## Issue
This does not appear to work. I tried deploying using different Linode sizes. None appears to work. 

I don't know if this is related. I see this in syslog: "[pa-reader] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/elasticsearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/batch_metrics_enabled.conf"

Has anyone actually succeeded in deploying Webuzo through the Linode Marketplace

**Comment by wildmanonline** [comment]
Thanks for reporting this @psyfi. Our team just updated the Webuzo App so that the proper firewall rules are applied and so the Compute Instance is rebooted to complete the installation. Details for this change are queued up for the corresponding doc as well.

I've tested this out and it appears to be working fine now. Can you try deploying it again?

**Comment by Rajakavitha1** [comment]
Informed the development team and the fix is being pushed. Closing this PR because it is not related to the document.

**Comment by psyfi** [comment]
Thank you, guys, for attending to this. But so far, not working. Tried different browsers. Having these errors seen via syslog: "performance-analyzer-agent-cli[697]: 23:46:26.203 [pa-reader] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/elasticsearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/batch_metrics_enabled.conf" 

"No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse"

Just letting you know that your Linode Marketplace is very useful to lazy people like me. :-)

Thank you for your help!
