### ISSUE TITLE
How to Use Block Storage with Your Linode Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#5284]
Link: https://www.linode.com/docs/guides/how-to-use-block-storage-with-your-linode/
## Issue

In this section:

#### Where to Go From Here?

There's a link to:

[Install GitLab on Ubuntu 14.04](https://www.linode.com/docs/development/version-control/install-gitlab-on-ubuntu-14-04-trusty-tahr/)

## Suggested Fix

Ubuntu 14 was EOL'd on April 30th 2019. That's BC - before covid. Maybe there's considerations that I'm not considering here, though I don't think promoting work that can be done on a distro that was EOL'd so long ago is wise.

**Comment by Rajakavitha1** [comment]
Updated the link.
