### ISSUE TITLE
How to Self-Host the vaultwarden Password Manager Proposed Changes

### ISSUE THREAD

**Issue by maetthew** [linode/docs#5309]
Link: https://www.linode.com/docs/guides/how-to-self-host-the-vaultwarden-password-manager/
## Issue
On the step `sudo docker run -d -p 8080:80 -p 443:443 --name caddy -v /etc/Caddyfile:/etc/caddy/Caddyfile -v /etc/caddy:/root/.local/share/caddy --restart on-failure caddy:2` it gives an error that the port is already in use by the `vaultwarden` container.
## Suggested Fix
Change port numbers so they don't conflict.

**Comment by Rajakavitha1** [comment]
Hi @maetthew closing this issue for now. Please feel free to reopen if any other changes need to be made.
