### ISSUE TITLE
Install a Custom Distribution on a Linode Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#5346]
Link: https://www.linode.com/docs/guides/install-a-custom-distribution-on-a-linode/
## Issue
In the [Prepare your Linode](https://www.linode.com/docs/guides/install-a-custom-distribution-on-a-linode/#prepare-your-linode) section, it instructs the user to create a Linode and then remove the disks. There's an easier way to prepare a Linode by creating one without disks. 

## Suggested Fix
This Community Questions post, it shows how you can create a Linode without disks in the Cloud Manager: [How can I create a Linode without a distribution?](https://www.linode.com/community/questions/19132/how-can-i-create-a-linode-without-a-distribution). Another reason I thought this could be included is because I couldn't find these instructions on any other doc and feel like it would be a helpful set of instructions for customers.

**Comment by Rajakavitha1** [comment]
Hi @Wat-Poods  updated the instructions and validated the steps in the guide.

**Comment by Rajakavitha1** [comment]
HI @Wat-Poods, closing this issue for now. Please feel free to reopen if any other changes need to be made.
