### ISSUE TITLE
How to Deploy Prometheus Operator and Grafana on LKE Proposed Changes

### ISSUE THREAD

**Issue by joseadanof** [linode/docs#5436]
Link: https://www.linode.com/docs/guides/deploy-prometheus-operator-with-grafana-on-linode-kubernetes-engine/
## Suggested Fix

According to [this](https://github.com/helm/charts/tree/master/stable/prometheus-operator), Prometheus Operator used in this guide is deprecated and it's generating a Warning when deploying into an LKE cluster.

Maybe you want to consider to use the *prometheus-community/kube-prometheus-stack chart*

**Comment by Rajakavitha1** [comment]
This has now been addressed in the PR: https://github.com/linode/docs/pull/5481.
Please feel free to reopen if any other changes need to be made.

**Comment by joseadanof** [comment]
Fantastic @Rajakavitha1, thanks!
