### ISSUE TITLE
Configure Email with Postfix and Dovecot on Debian and Ubuntu Proposed Changes

### ISSUE THREAD

**Issue by elplatt** [linode/docs#5528]
Link: https://www.linode.com/docs/guides/email-with-postfix-dovecot-and-mysql/
## Issue

Following the directions for the **Setting Up MySQL to Send Email with Postfix and Dovecot** section prints the following message (tested on a new Ubuntu 22.04 linode):

    Securing the MySQL server deployment.

    Connecting to MySQL using a blank password.
    The 'validate_password' component is installed on the server.
    The subsequent steps will run with the existing configuration
    of the component.
    Please set the password for root here.

After entering a password the following error is produced:

     ... Failed! Error: SET PASSWORD has no significance for user 'root'@'localhost' as the authentication method used doesn't store authentication data in the MySQL server. Please consider using ALTER USER instead if you want to change authentication parameters.

    New password: 

And the user is prompted to enter the password again.

**Comment by Rajakavitha1** [comment]
Hi @elplatt !!! Thank you for raising the issue. We just updated the docs to not skip setting the root password. Closing this issue for now. Please feel free to reopen if any other changes need to be made.
