### ISSUE TITLE
Getting Started on the Linode Platform Proposed Changes

### ISSUE THREAD

**Issue by linerlum** [linode/docs#5559]
hello im trying to creat an account. but it sent me an email that it is being reviewed. i  am in need of the account asap for class.

**Comment by linerlum** [comment]
oh wow i am realizing that  I HAVE CREATED ANOTHER ACCOUNT PREVIOUSLY. CAN I HAVE THE NEW ACCOUNT THAT WAS CREATED TODAY DELETED. THANKS

**Comment by wildmanonline** [comment]
Hi there. This repository is for the Linode documentation. For help with your account (and deleting an existing account), you'll want to reach out directly to the Linode support team if you haven't done so already. Here's a web page with their contact information: https://www.linode.com/support/. Going to close this issue out.
