### ISSUE TITLE
Securing your server - SSH firewall rule is IPv4 only?

### ISSUE THREAD

**Issue by wturrell** [linode/docs#559]
https://www.linode.com/docs/security/securing-your-server#basic-iptables-rulesets-for-ipv4-and-ipv6

The suggested firewall rules open port 22 (for SSH) on IPv4, but not IPv6 – is this deliberate or accidental?

**Comment by cwlinode** [comment]
That is deliberate. Those rulesets are mainly intended as an example so anything beyond that would need further tweaking.

If you would prefer SSH over IPv6, move that single rule from /tmp/v4 to /tmp/v6, after the ICMP rule. Also make sure to have _AddressFamily_ set accordingly from the [SSH Daemon Options](https://www.linode.com/docs/security/securing-your-server#ssh-daemon-options) section of the guide.
