### ISSUE TITLE
How To Build Database Clusters with MongoDB Proposed Changes

### ISSUE THREAD

**Issue by bentwheel** [linode/docs#5603]
Link: https://www.linode.com/docs/guides/build-database-clusters-with-mongodb/
## Issue
Under "Set Up MongoDB Authentication" heading, within the "Generate a Key file" heading, on step 5 the document says to update `/etc/mongod.conf` as such:

    security:
    keyFile: /opt/mongo/mongodb-keyfile

## Suggested Fix

It should be:

    security:
    keyFile: /opt/mongo/mongo-keyfile

**Comment by Rajakavitha1** [comment]
@bentwheel thank you for raising the issue. It has now been fixed in https://github.com/linode/docs/pull/5604
