### ISSUE TITLE
Understanding Billing and Payments on the Linode Platform Proposed Changes

### ISSUE THREAD

**Issue by Gfazo** [linode/docs#5637]
Link: https://www.linode.com/docs/guides/understanding-billing-and-payments/
## Suggested Fix
Won’t let me pay!
And also keeps sending me cancellation emails

**Comment by Rajakavitha1** [comment]
We are sorry about the issue that you are facing. You can contact Linode [support ](https://www.linode.com/support/) or log a [support ticket](https://cloud.linode.com/support/tickets). Closing this issue for now. Please feel free to log any issue related to the documentation.
