### ISSUE TITLE
Creating a Compute Instance on the Linode Platform Proposed Changes

### ISSUE THREAD

**Issue by Dickson-24** [linode/docs#5653]
Link: https://www.linode.com/docs/guides/creating-a-compute-instance/

**Comment by Rajakavitha1** [comment]
Hi @Dickson-24  could you please provide some context about the issue that you find so that we can address the issue.

**Comment by Rajakavitha1** [comment]
Hi @Dickson-24  we are closing this issue for now. Please feel to reopen with more context and the issue that you are facing.
