### ISSUE TITLE
Security on Postfix SMTP

### ISSUE THREAD

**Issue by rvillablanca** [linode/docs#572]
Hi, I'm following the https://www.linode.com/docs/email/postfix/email-with-postfix-dovecot-and-mysql doc, and the all was configured correctly. My concern is in the 'Test Email' section, says the following:

> You should use Port 993 for secure IMAP, Port 995 for secure POP3, and Port 25 with SSL for SMTP

Is correct use port 25 to send an email ? Is possible use the port 25 with SSL ? I'am testing with swaks tool, but the server never request an user authentication.

**Comment by alexfornuto** [comment]
@rvillablanca  Please take a look at the referenced commit, does it satisfy your concerns?

**Comment by rvillablanca** [comment]
Sure @alexfornuto ;)
