### ISSUE TITLE
How to Deploy Jenkins X in Linode Kubernetes Engine Proposed Changes

### ISSUE THREAD

**Issue by JLA4444** [linode/docs#5756]
Link: https://www.linode.com/docs/guides/how-to-deploy-jenkins-x-in-linode-kubernetes-engine/

According to:
ankitm123 at the thread https://github.com/jenkins-x/jx/issues/8133#issuecomment-1143757689

We should we use jx v3 now as per comment:
"""jx boot is v2 (unmaintained), please use v3."""

## Suggested Fix
State in the guide that the instructions are for JX v2 or update the guide

**Comment by Rajakavitha1** [comment]
Added a deprecation notice and a note about v3 in the [PR ](https://github.com/linode/docs/pull/5828).  Closing this issue for now. Please feel free to reopen if any other changes need to be made.
