### ISSUE TITLE
Passenger Installation guide (for rails on Debian 8) are outdated

### ISSUE THREAD

**Issue by dathinaios** [linode/docs#576]
Regarding [this guide](https://www.linode.com/docs/websites/ror/ruby-on-rails-nginx-debian-8).

I am very new to all this so I kind of blindly follow the instructions but after trying I found [an article](https://www.phusionpassenger.com/library/install/nginx/install/oss/jessie/) that contains a much more straightforward (and more up to date?) method.

Just in case it is relevant.

**Comment by alexfornuto** [comment]
Hi @dathinaios, thanks for your comment. Can you tell us what, specifically, you feel should be updated? I took a cursory glance at the guide you referenced, and it seems to use the same installation method as our guide.

**Comment by dathinaios** [comment]
Hello Alex,

I had a look at my links but I'm afraid I have completely forgotten what it was. The instructions have some differences and when I tried it I couldn't get it to work with yours. I was successful following the instructions from the Linode site though.

Sorry I should have been more specific when the memory was fresh.

Feel free to close.

**Comment by alexfornuto** [comment]
No worries, thanks for contributing!
