### ISSUE TITLE
Incorrect Archlinux installation instruction for mtr

### ISSUE THREAD

**Issue by lhark** [linode/docs#580]
In the following article about mtr
https://github.com/linode/docs/blob/master/docs/networking/diagnostics/diagnosing-network-issues-with-mtr.md
the installation procedure for archlinux tells the reader to use the following commands:

```
    pacman -Sy
    pacman -S mtr
```

Whereas the archlinux wiki clearly states this should be avoided at all costs:
https://wiki.archlinux.org/index.php/Pacman#Installing_packages

**Comment by alexfornuto** [comment]
@lhark Please take a look at the referenced commit, does it satisfy your concerns?

**Comment by lhark** [comment]
Yes it does. Thank you for fix that :)
