### ISSUE TITLE
Install Apache Subversion on Ubuntu 20.04 Proposed Changes

### ISSUE THREAD

**Issue by MidsummerNight** [linode/docs#5829]
Link: https://www.linode.com/docs/guides/install-apache-subversion-ubuntu/
## Issue

1. Step 6 of [this section](https://www.linode.com/docs/guides/install-apache-subversion-ubuntu/#install-the-apache-web-server)  (`sudo install apache2 apache2-utils -y`) returns:
`install: invalid option -- 'y'`
`Try 'install --help' for more information.`

2. In the [create-a-subversion-administrator-user](https://www.linode.com/docs/guides/install-apache-subversion-ubuntu/#create-a-subversion-administrator-user) section the given input `htpasswd -CM /etc/apache2/dav_svn.passwd <<admin_name>>` returns but according to `man htpasswd`, `-C` is the wrong option here while `-M` is an invalid option.

## Suggested Fix

1. Change `sudo install apache2 apache2-utils -y` to `sudo apt install apache2 apache2-utils -y`.
2. Change `htpasswd -CM /etc/apache2/dav_svn.passwd <<admin_name>>` to `htpasswd -cm /etc/apache2/dav_svn.passwd <<admin_name>>`

**Comment by Rajakavitha1** [comment]
Closing this issue for now. Please feel free to reopen if any other changes need to be made.
