### ISSUE TITLE
How to Set Up and Secure a Linode Compute Instance Proposed Changes

### ISSUE THREAD

**Issue by viroshdemel** [linode/docs#5856]
Link: https://www.linode.com/docs/guides/set-up-and-secure/
## Issue
- First Para, Last Sentence Typo.
"After you have successfully created a Compute Instance, there are a few initial configuration steps you should perform within your new Linux system. This includes updating your system, setting the timezone, configuring a custom hostname, adding a limited user, hardening SSH to prevent unauthorized access, and configuring a firewall. These steps ensure your instance is update to date, secure, and ready for use."
## Suggested Fix
"After you have successfully created a Compute Instance, there are a few initial configuration steps you should perform within your new Linux system. This includes updating your system, setting the timezone, configuring a custom hostname, adding a limited user, hardening SSH to prevent unauthorized access, and configuring a firewall. These steps ensure your instance is updated to date, secure, and ready for use."
or 
"After you have successfully created a Compute Instance, there are a few initial configuration steps you should perform within your new Linux system. This includes updating your system, setting the timezone, configuring a custom hostname, adding a limited user, hardening SSH to prevent unauthorized access, and configuring a firewall. These steps ensure your instance is up to date, secure, and ready for use."

**Comment by Rajakavitha1** [comment]
Thank you for spotting the typo we just created a PR to fix the typo. Please feel free to reopen if any other updates need to be made.
