### ISSUE TITLE
Incorrect command for automating renewal of letsencrypt cert from cron

### ISSUE THREAD

**Issue by Soulriser** [linode/docs#588]
There's a problem in your support documentation for automating the renewal of letsencrypt certificates here:

https://www.linode.com/docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates

To add the cron tab you suggest:

`echo '@monthly root /opt/letsencrypt/letsencrypt-auto certonly --standalone --renew-by-default -d example.com -d www.example.com >> /var/log/letsencrypt/letsencrypt-auto-update.log' | sudo tee --append /etc/crontab`

But you need to include the `--quiet` option in order to prevent Python UI errors. Under a normal terminal you would see an interactive dialog that can't be handled under automated execution.

Corrected command:

`echo '@monthly root /opt/letsencrypt/letsencrypt-auto certonly --quiet --standalone --renew-by-default -d example.com -d www.example.com >> /var/log/letsencrypt/letsencrypt-auto-update.log' | sudo tee --append /etc/crontab`

**Comment by alexfornuto** [comment]
@Soulriser same as your other issue: Please take a look at the referenced commit, does it satisfy your concerns?

**Comment by Soulriser** [comment]
@alexfornuto Yes indeed, looks good, thanks again.
