### ISSUE TITLE
Automating renewal of letsencrypt cert when apache (or nginx) is bound to port 443

### ISSUE THREAD

**Issue by Soulriser** [linode/docs#589]
Referencing:
https://www.linode.com/docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates

You might want to mention that running apache on port 443 will result in failure to automatically renew the certificate due to the certbot requiring binding to port 443. This is worked around by invoking the webroot plugin, for example:

`/opt/letsencrypt/letsencrypt-auto certonly --webroot -w /var/www/example/ -d www.example.com -d example.com -w /var/www/other -d other.example.net -d another.other.example.net`

More here:

https://letsencrypt.readthedocs.io/en/latest/using.html#apache

Instructions there for nginx as well.

**Comment by alexfornuto** [comment]
@Soulriser Please take a look at the referenced commit, does it satisfy your concerns?

**Comment by Soulriser** [comment]
@alexfornuto Thanks for handling this. Looks good to me.
