### ISSUE TITLE
Site To Site VPN between linode and Azure

### ISSUE THREAD

**Issue by vkamlesh** [linode/docs#5895]
I am planning to migrate some workloads from Azure to Linode. I want to setup site to site VPN using libreswan or any other VPN. I have tried to setup libreswan using [link](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/site-to-site_vpn_using_libreswan) at linode side and setup Virtual gateway + local gateway at Azure side but it didn't work. Is it possible to setup Site2Site VPN in Linode 
I have found [Link1](https://medium.com/thoughts-from-a-moose/aws-vpc-vpn-connection-to-linode-with-gre-tunnels-a8afb2710e0e) which demonstrated how to setup AWS - Linode site2site VPN.

**Comment by Rajakavitha1** [comment]
Hi @vkamlesh !!! Thank you for the link. You might want to post this question in https://www.linode.com/community/questions/  or raise a ticket on https://cloud.linode.com/support/tickets for further assistance in migrating the workloads from Azure to Linode.

**Comment by Rajakavitha1** [comment]
Closing this for for now because it is not related to the issues in the existing documentation.
