### ISSUE TITLE
Deploying a MEAN Stack through the Linode Marketplace guide proposed changes

### ISSUE THREAD

**Issue by JonMorales22** [linode/docs#5906]
link: https://www.linode.com/docs/products/tools/marketplace/guides/mean-stack/

### Issue
This guide makes no mention that pm2 is also installed as a part of the deploy and that it is utilized to run the server.js file. This results in changes to the server.js file not being propagated to the user's browser until restarting the process through pm2. This was confusing for me as a new user of Linode and the MEAN stack marketplace application.

### Proposed Fix

1. add pm2 to the "Software Included" section of guide: [link](https://www.linode.com/docs/products/tools/marketplace/guides/mean-stack/#software-included)
2. add a whole new section with brief overview of pm2 and how to view changes to server.js

**Comment by Rajakavitha1** [comment]
Thank you for the suggestions @JonMorales22 !!! Our documentation will review the suggestions that you made and incorporate the changes after validating.
