### ISSUE TITLE
php5 no longer available on Ubuntu 16.04

### ISSUE THREAD

**Issue by iamorme** [linode/docs#599]
Referencing:
[https://www.linode.com/docs/websites/hosting-a-website](url)

Under PHP, Install PHP: 
`sudo apt-get install php5`
but php5 is no longer available on the standard linode repositories

**Comment by alexfornuto** [comment]
@iamorme We address that in the guide:

```
Debian 8 and Ubuntu 14.04 LTS are the Linux distributions we’re using as the starting point for the packages and configurations mentioned in this guide. If you’d like to use Ubuntu 16.04 LTS, refer to the distribution-specific guide on how to set up a LAMP Stack, and then return here to continue from the upload files section.
```

relevant link from that note: https://www.linode.com/docs/websites/lamp/install-lamp-on-ubuntu-16-04
