### ISSUE TITLE
PLEASE MEREG ALL MY ACCOUNTS INTO ONE ACCOUNT TO AVOID CONFUSION

### ISSUE THREAD

**Issue by sh471** [linode/docs#5998]
Link: https://www.linode.com/docs/products/platform/billing/

**Comment by Rajakavitha1** [comment]
Hi @sh471  !!! you might want to try out this guyed to manage multiple accounts https://www.linode.com/docs/products/tools/cli/guides/manage-multiple-accounts/. You may also want to contact the Linode support team or raise a ticket https://cloud.linode.com/support/tickets for further assistance.
