### ISSUE TITLE
Deploy Mastodon through the Linode Marketplace Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#6065]
Link: https://www.linode.com/docs/products/tools/marketplace/guides/mastodon/
## Issue

The guide states:

> Recommended minimum plan: All plan types and sizes can be used.

But the script uses Docker Compose and a Nanode does not have enough compute power to run that. In my experience testing deploys, both manually and through the OCA, I needed more than 1GB of RAM. 

## Suggested Fix

Suggest plans at least 2GB or higher, though I have only tested between a Nanode and a 4GB plan.

**Comment by Rajakavitha1** [comment]
Hi @Wat-Poods!! closing this issue because it has been addressed in a PR that is merged now.

**Comment by Rajakavitha1** [comment]
Hi @Wat-Poods!! closing this issue because it has been addressed in a PR that is merged now.
