### ISSUE TITLE
Install PyTorch on Ubuntu 20.04 Proposed Changes

### ISSUE THREAD

**Issue by Learath** [linode/docs#6265]
Link: https://www.linode.com/docs/guides/pytorch-installation-ubuntu-2004/
## Issue
When running the steps in 02 D Test your PyTorch Installation on ubuntu 2010 the provided examples don't function as expected when installed via pip:
>>> print (torch.cuda.is_available)
<function is_available at 0x7f49cd9ef6d0>
>>> print (torch.cuda.device_count)
<functools._lru_cache_wrapper object at 0x7f49bf2bd430>

Python3 expects () to actually execute the functions:
>>> print (torch.cuda.is_available())
True
>>> print (torch.cuda.device_count())
1

## Suggested Fix
Update the docs to include the ().

**Comment by Rajakavitha1** [comment]
Thank you @Learath for raising the issue. This has now been fixed in https://github.com/linode/docs/pull/6738.
