### ISSUE TITLE
Getting Started Guide for Linode, Gentoo Update Section

### ISSUE THREAD

**Issue by PinkAppleFlower** [linode/docs#628]
Hello, my comment is with respect to this document: https://www.linode.com/docs/getting-started .

I did not issue a pull request because I think there is room for discretion in how this content is integrated, but if you want me to do a pull request please just let me know and I will do so.

It is now the case that the command emaint is now the primary control of all sync operations [1].  But much of the Gentoo documentation still includes references to, or instructions using, the emerge command and both commands are included in documentation like [2].  I suggest that a reference to the emaint man page should be included as a note under the emerge command.  It is important that people be made aware of this change in the gentoo system as package management and repo management are important and subsequent configuration steps can change. See [3] for the emaint man-page.  Also, when one reads the suggestions after the at update world command, they see a suggestion to run the  "eselect news read" command, which mentions the transition to emaint.  I think it is to your advantage to start making the transition as it is consistent with most up to date Gentoo documentation and, in my opinion increases the credibility of your documentation.

References
[1] https://wiki.gentoo.org/wiki/Project:Portage/Sync#Operation
[2] https://dev.gentoo.org/~zmedico/portage/doc/man/portage.5.html
[3] https://dev.gentoo.org/~zmedico/portage/doc/man/emaint.1.html

**Comment by pbzona** [comment]
Hi @PinkAppleFlower,

Thank you for this suggestion. I'm regrettably not familiar enough with Gentoo to write an (accurate) updated set of instructions for using `emaint`, but I've included a note to address the shift:

https://github.com/linode/docs/pull/636

I'd appreciate any feedback you may have and if you're interested in contributing a more comprehensive set of instructions, please feel free to make a pull request. Thanks again!

**Comment by cwlinode** [comment]
Thank you for bringing this up. PR 636 uses emaint and references some more info for people who want to look further into its commands and options. Closing.
