### ISSUE TITLE
"Bucket Names" section link goes nowhere.

### ISSUE THREAD

**Issue by akessner** [linode/docs#6285]
On the page for Object Storage : Get Started

the link to bucket naming policies goes nowhere.
Link:
https://www.linode.com/docs/products/storage/object-storage/get-started/#bucket-names

The link is in the sentence:
"Add a label for your bucket. See the [Bucket Name](https://github.com/linode/docs/blob/4e1a0276b9e5a41102c8d72a57c70b3045b736f9/docs/products/storage/object-storage/get-started/index.md#bucket-names) section for rules on naming your bucket."

**Comment by Rajakavitha1** [comment]
Fixed in https://github.com/linode/docs/pull/6295
