### ISSUE TITLE
Billing Proposed Changes

### ISSUE THREAD

**Issue by BehindTheElephants** [linode/docs#6302]
Link: https://www.linode.com/docs/products/platform/billing/

**Comment by BehindTheElephants** [comment]
My company is Amneal Pharmaceuticals.  We have a record pointing to your address, 97.107.133.142 in our public DNS.  It was flagged by a security report for having vulnerabilites.  We are not sure if we are an active customer, or what business group is using any of your services.  Can you confirm if we are an active customer, and any contact info you have for us so i can talk to that department on my side.  Thank you.

Josh Glantz, Josh.glantz@amneal.com, 908-409-6746

**Comment by Rajakavitha1** [comment]
Hi @BehindTheElephants !!! you may want to contact support at  https://www.linode.com/support/ for any assistance or quires related to your account. Closing this issue for now because it is not related to the documentation.
