### ISSUE TITLE
Roundcube, PHP, and localhost.

### ISSUE THREAD

**Issue by alexfornuto** [linode/docs#633]
Because PHP 5.6 checks for SSL - Domain matching, you can't connect to `ssl://localhost:993` or `587` as instructed in the roundcube guide. Adjust to point to the email domain.

**Comment by alexfornuto** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10216499-243506170_5-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by h4ckninja** [comment]
Sorry, I don't mean to hijack this, but on the topic of PHP 5.6, [it is approaching EoL very soon](https://php.net/supported-versions.php). It's only receiving security fixes now.

**Comment by alexfornuto** [comment]
@cwlinode are you gonna let this wither on the vine? For shame!
