### ISSUE TITLE
Longview docs - explain firewall settings for UFW

### ISSUE THREAD

**Issue by sebnozzi** [linode/docs#648]
When securing the server, the docs suggest (among others) using UFW.

But in the Longview docs, only iptables examples are given.

It is not clear (to a non-expert like me) if I can combine iptables with UFW. In case it's a bad idea (I guess it is) the user should be warned against it, and the equivalent UFW commands offered.

**Comment by Darkstar90** [comment]
Hey sebnozzi, 

UFW stands for "uncomplicated firewall" and is a tool to manage iptables. So, changes you make in either one will reflect in both. In this specific case, the standard UFW settings should work for you, unless you have services which require other ports to be open than the standard ones. Here's a couple commands you can use to familiarize yourself with UFW.

## View all UFW arguments
ufw --help

## View the current firewall rules
sudo ufw status

## Add new firewall rule
sudo ufw allow <port# or service.initd name if supported>

## Enable firewall
sudo ufw enable

## Disable firewall
sudo ufw disable
