### ISSUE TITLE
Deploy WordPress through the Linode Marketplace Proposed Changes

### ISSUE THREAD

**Issue by AshCarmine** [linode/docs#6609]
Link: https://www.linode.com/docs/products/tools/marketplace/guides/wordpress/
## Issue
Directory for updating admin password and email address is incorrect in the current documentation.

## Suggested Fix
Update lines 119 and 122 with the corrections from the following file.

[index.md](https://github.com/linode/docs/files/12598286/index.md)

**Comment by timzl** [comment]
I submitted a PR for this: https://github.com/linode/docs/pull/6771

**Comment by Rajakavitha1** [comment]
Marking this issue as closed.
