### ISSUE TITLE
Deploying a 7 Days to Die Server on Linux Proposed Changes

### ISSUE THREAD

**Issue by Azuroth2013** [linode/docs#6613]
Link: https://www.linode.com/docs/guides/deploy-7-days-to-die-linux-game-server/
## Issue

netcat is deprecated.

## Suggested Fix

Changing it to netcat-traditional should fix the issues.

**Comment by Rajakavitha1** [comment]
Thank you for raising the issue @Azuroth2013. This has now been addressed in https://github.com/linode/docs/pull/6746.
