### ISSUE TITLE
'knife linode' link is broken

### ISSUE THREAD

**Issue by BGmot** [linode/docs#662]
https://github.com/linode/docs/blob/master/docs/platform/automating-server-builds.md
Clicking on the 'knife linode' link in 'Third-Party Tools' section results in 404 code.

**Comment by EdwardAngert** [comment]
Hi @BGmot!
Thanks for catching that broken link.
I updated that guide to reflect Knife Linode's [new home on GitHub](https://github.com/chef/knife-linode): https://github.com/linode/docs/pull/664

Let me know if that helps and if you know of any other links that might be helpful to include in that guide.

Thanks again,
Edward

**Comment by BGmot** [comment]
Hi @EdwardAngert ! commit looks good. Thanks!
