### ISSUE TITLE
Images Proposed Changes

### ISSUE THREAD

**Issue by Wat-Poods** [linode/docs#6637]
Link: https://www.linode.com/docs/products/tools/images/#technical-specifications
## Issue

The first bullet point in this section reads:
> **Maximum image size:** A Custom Image can be up to 6 GB* in size.

But then later in the section, there's another bullet point:
> **Upload image format and size limits:** The [.img](https://en.wikipedia.org/wiki/IMG_%28file_format%29) file format is supported when uploading an image file. This file should be compressed using [gzip](https://en.wikipedia.org/wiki/Gzip) (.img.gz). It can be up to **5GB** when compressed and, when uncompressed, up to the **maximum image size** as stated above.

## Suggested Fix

I'm not sure how to best accomplish this, though I think it would be helpful to clarify in that the first bullet point the difference between compressed and uncompressed size restraints.

**Comment by Rajakavitha1** [comment]
Hi @Wat-Poods !  this has now been addressed in https://github.com/linode/docs/pull/6739.
