### ISSUE TITLE
"Deploy Linode Using Ansible" Guide (or the new one) needs better SEO

### ISSUE THREAD

**Issue by jamesbiederbeck** [linode/docs#6647]
Link: https://www.linode.com/docs/guides/deploy-linodes-using-ansible/
## Issue
Googling Linode Ansible collection should take me to current docs

## Suggested Fix
Improve your SEO? I'm so sorry if that's not actionable for your team. I'm sure you can't do much about that, but I hope you find value in knowing that older docs have better SEO.

**Comment by jamesbiederbeck** [comment]
In particular, I'm opening this issue because of this message at the top of the page referenced. 

> ### Deprecated
> This guide has been deprecated and is no longer being maintained. Please refer to the [updated version of this guide.](https://www.linode.com/docs/guides/deploy-linodes-using-linode-ansible-collection/)

Feel free to close the issue with no reply if not's not relevant to your team. _really, I get it._

**Comment by Rajakavitha1** [comment]
Thank you for reporting the issue @jamesbiederbeck . It is indeed good to know that the older docs have better SEO. Noted the issue and passed it on to the relevant team.
