### ISSUE TITLE
Use the Linode Ansible Collection to Deploy a Linode Proposed Changes

### ISSUE THREAD

**Issue by sirvictory444** [linode/docs#6674]
Link: https://www.linode.com/docs/guides/deploy-linodes-using-linode-ansible-collection/
## Suggested Fix

In your guide, the vault password file is created as a hidden file, beginning with a period.
The correct line in ansible.cfg should then read:
`VAULT_PASSWORD_FILE = ./.vault-pass`
It currently reads:  (as of 1140 GMT-4 10-13-2023)
`VAULT_PASSWORD_FILE = ./vault-pass`

**Comment by Rajakavitha1** [comment]
Thank you @sirvictory444  for raising the issue. This has now been fixed in https://github.com/linode/docs/pull/6745
