### ISSUE TITLE
Deploy Nextcloud through the Linode Marketplace Proposed Changes

### ISSUE THREAD

**Issue by Figrol** [linode/docs#6706]
Link: https://www.linode.com/docs/products/tools/marketplace/guides/nextcloud/
## Issue
In the "Configure and start your nextcloud instance" section of the guide. You suggest people go to ttps://[domain]:8443/ however, when logging into the nextcloud instance via SSH, it suggests to use port 8080. When using 8080, the installer works. 8443 doesn't seem to resolve.
## Suggested Fix
update guide to use port 8080 rather than 8443

**Comment by Rajakavitha1** [comment]
Hi @Figrol !!! Thank. you for raising the issue. Deploying Nextcloud using the LInode Marketplace is for beginners for advanced users we do have a detailed guide here that provides details about using the port 8080. https://www.linode.com/docs/guides/how-to-install-nextcloud-on-ubuntu-22-04/. This guide for beginners is based on the details listed here. https://github.com/nextcloud/all-in-one#which-ports-are-mandatory-to-be-open-in-your-firewallrouter. Marking this issue as closed. Please feel free to reopen if any other. issue needs to be addressed.
