### ISSUE TITLE
Deploy Nextcloud through the Linode Marketplace Proposed Changes

### ISSUE THREAD

**Issue by Figrol** [linode/docs#6707]
Link: https://www.linode.com/docs/products/tools/marketplace/guides/nextcloud/
## Issue
In the Configuration Options section, the Recommended Minimum plan type says all plans supported. However, nextcloud recommend all container based installations as this one is have minimum of 2GB ram.

Here is an extract from the installation page: Minimal system requirements: When any optional container is enabled, at least 2GB RAM, a dual-core CPU and 40GB system storage are required. When enabling ClamAV, Nextcloud Talk Recording-server or Fulltextsearch, at least 3GB RAM are required. For Talk Recording-server additional 2 vCPUs are required. When enabling everything, at least 5GB RAM and a quad-core CPU are required. Recommended are at least 1GB more RAM than the minimal requirement. For further advices and recommendations see [this documentation](https://github.com/nextcloud/all-in-one/discussions/1335)
## Suggested Fix
upgrade guide to recommend Linodes that have minimum 2GB ram.

**Comment by Rajakavitha1** [comment]
Hi @Figrol !! Thank you for raising the issue. The install instructions work as documented and it is based on the system requirements documented here https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html. For advanced users we have the https://www.linode.com/docs/guides/how-to-install-nextcloud-on-ubuntu-22-04/ with references to the official documentation website for Nextcloud that provides accurate and upto date information. `You may wish to consult the following resources for additional information on this topic. While these are provided in the hope that they will be useful, please note that we cannot vouch for the accuracy or timeliness of externally hosted materials.`
