### ISSUE TITLE
Inspecting Network Information with netstat Proposed Changes

### ISSUE THREAD

**Issue by bunny-thief** [linode/docs#6712]
Link: https://www.linode.com/docs/guides/inspecting-network-information-with-netstat/
## Issue
The note in the [Show IPv6 Connections Only](https://www.linode.com/docs/guides/inspecting-network-information-with-netstat/#show-ipv6-connections-only) sub-section refers to IPv4 instead of IPv6.

> If you want to display IPv4 connections that are in both listening and non-listening state, add the -a command line option:

## Suggested Fix
It should be changed to 

> If you want to display IPv6 connections that are in both listening and non-listening state, add the -a command line option:

**Comment by Rajakavitha1** [comment]
Thank you for raising the issue @bunny-thief . This has now been fixed in https://github.com/linode/docs/pull/6737.
