### ISSUE TITLE
Securing Nginx With ModSecurity Proposed Changes

### ISSUE THREAD

**Issue by hcql** [linode/docs#6803]
Link: https://www.linode.com/docs/guides/securing-nginx-with-modsecurity/
## Suggested Fix

[configuring-modsecurity](https://www.linode.com/docs/guides/securing-nginx-with-modsecurity/#configuring-modsecurity) 

` sudo cp /etc/modsecurity/modsecurity.conf-recommended /etc/modsecurity/modsecurity.conf
`
Where did /etc/modsecurity/modsecurity.conf-recommended come from?

**Comment by Rajakavitha1** [comment]
Marking this issue as closed because it is addressed in the PR: https://github.com/linode/docs/pull/7167
