### ISSUE TITLE
clustercheck script missing

### ISSUE THREAD

**Issue by timwhitlock** [linode/docs#682]
Hi 
Regarding this guide to a HA setup on CentOS 7:  
https://www.linode.com/docs/websites/host-a-website-with-high-availability#configure-keepalived

The `/usr/bin/clustercheck` script given in the keepalived config does not exist on my system after installing keepalived. Is there a step missing?

**Comment by Guaris** [comment]
Hey Tim, I spent the morning trying to replicate your issue and this is what I've come up with: 

I was not able to replicate your error. The `clustercheck` script is added after installing Galera. 
After installing Galera and keepalived, I have the `clustercheck` script in my /usr/bin directory. You can try installing Galera from this updated link:  https://www.percona.com/redir/downloads/percona-release/redhat/latest/percona-release-0.1-4.noarch.rpm 
Then run a `ls | grep cluster` to see if it was installed.

**Comment by timwhitlock** [comment]
Sorry for wasting your morning. I neglected to mention that I am using Galera libraries bundled in with MariaDB. I had assumed the same utilities would be present. I should  have thought to mention it.

**Comment by Guaris** [comment]
Not a problem at all! We take all PR's seriously on our team; so we can continue to write clear and effective documentation.
