### ISSUE TITLE
Installing MariaDB on Debian 10 Proposed Changes

### ISSUE THREAD

**Issue by GTAXL** [linode/docs#6830]
Link: https://www.linode.com/docs/guides/how-to-install-mariadb-on-debian-10/
 The following command
`UPDATE user SET plugin='mysql_native_password' WHERE user='root';`
no longer works. This guide needs updated for Debian 12 Bookworm. It should use
```
ALTER USER root@localhost IDENTIFIED VIA mysql_native_password;
SET PASSWORD = PASSWORD('foo');
```
instead. Also mysql_secure_installation should really be changed to mariadb-secure-installation, even though they are symlinked.

**Comment by Rajakavitha1** [comment]
closing this now based on the comments in the PR 6830
