### ISSUE TITLE
Not able to see on localhost or with container ip

### ISSUE THREAD

**Issue by vinodnerella** [linode/docs#685]
sudo docker run -p 9090:80 -t -i linode/lamp /bin/bash

and then service apache2 start.

But still not able to see anything for localhost:9090 or containerip:80

Host OS: Windows

Container: linode/lamp

**Comment by Guaris** [comment]
Hello, can you please clarify the issue your having and the guide you are referencing?

**Comment by Guaris** [comment]
@vinodnerella Hey, I haven't heard from you in a while. I am going to close this issue, and invite you to submit another one with clarification.
