### ISSUE TITLE
Missing permission for xtrabackup

### ISSUE THREAD

**Issue by timwhitlock** [linode/docs#691]
Regarding [this HA guide](https://www.linode.com/docs/websites/host-a-website-with-high-availability): 

It took me some hours of head-scratching to work out that the `sstuser` permissions given in step 3 of "Configure Your Galera Cluster" are missing the PROCESS permission. (required in xtrabackup 2.4)

May be worth mentioning to check the version and [link to their docs](https://www.percona.com/doc/percona-xtrabackup/2.4/using_xtrabackup/privileges.html#permissions-and-privileges-needed).

**Comment by Guaris** [comment]
Hey, thanks for pointing this out. I'll be investigating the issue shortly.

**Comment by Guaris** [comment]
Awesome. Thanks so much for the help! The doc will be updated today. One question: How did you figure out that you were missing that permission?

**Comment by timwhitlock** [comment]
Eventually I realised that the donor node had more useful errors logged. i.e. the recipient of the transfer doesn't know what went wrong and so you get worthless error messages. 

The xtrabackup error log is found in the donor machine's mysql data directory. It's named something quite obvious, but I don't recall off the top of my head.

**Comment by Guaris** [comment]
Awesome! Thank you.
