### ISSUE TITLE
minecraft-on-debian-and-ubuntu - Minecraft version 1.12 now requires openjdk 8

### ISSUE THREAD

**Issue by jcgallaher** [linode/docs#694]
Good evening,

Minecraft was updated to version 1.12 on June 7th and the developers compiled the server jar for Java 8. So, if you're running Debian 8 Jessie, you will have to back port to get Openjdk 8 because Debian Jessie only has version 7 and it only works with Minecraft 1.11.2 or <.

I had learned this yesterday after trying to find out the update wouldn't run. I back ported to get openjdk 8 and then removed openjdk 7 so it wouldn't default to it.

Debian 9 Stretch is coming out soon and Openjdk 8 will be included in the stable repo.

**Comment by jcgallaher** [comment]
You're welcome and that's correct, which I learned several hours later on the forum... I was a little angry that they didn't tell us this fact... But anyway.

If you download the server jar file from https://s3.amazonaws.com/Minecraft.Download/versions/1.12/minecraft_server.1.12.jar and you run the following command to run the file as an executable `java -jar minecraft_server.1.12.jar` in Debian 8 Jessie (I tried running java xf <file name> to extract the class info so I could see what build it was complied for, but I got a couldn't find class error)
It'll throw an error saying:

`Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/server/MinecraftServer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)`

The error "unsupported minor/major version 52" means you need Java 8 from my research. Also, in this video from one of the Minecraft employees he mentions this is the first version to require Java 8: https://youtu.be/M6HsqQMHuSs?t=22m40s I fast forwarded the link to the end where he talks about it, about 20 seconds in.

**Comment by jcgallaher** [comment]
But the good news is, if I'm correct, the back port Openjdk 8 version is the same version that will be on Debian 9 Stretch that's getting released on June 17.

**Comment by Guaris** [comment]
Awesome! I'll throw some of these fixes in by Monday afternoon at the latest! Thanks so much for the help !

**Comment by jcgallaher** [comment]
You're welcome. :-)

**Comment by Guaris** [comment]
@jcgallaher I know I planned on having these fixes in by today at the latest. It's proving to be a bit more involved then I had though ( a lot of changing 1.11.2 to 1.12) so this will be pushed back to tomorrow. Just letting you know incase you check today and think I forgot about 'ya. 
Thanks again!

**Comment by jcgallaher** [comment]
No worries. :-) That's why I made an issue rather than do a pull request, because it's a little more involving to explain the best way to update java on Debian. I did a backport, since I figured that was the best way. But there's a few steps to doing that.
