### ISSUE TITLE
Manage Personal Access Tokens Proposed Changes

### ISSUE THREAD

**Issue by nicholasdillon** [linode/docs#6975]
Link: https://www.linode.com/docs/products/tools/api/guides/manage-api-tokens/
## Suggested Fix

Published January 1, 0001 seems a bit wrong

**Comment by Rajakavitha1** [comment]
updated doc slink is here: https://techdocs.akamai.com/cloud-computing/docs/manage-personal-access-tokens . Closing this issue for now. Please feel free to reopen if there are any other issues.
