### ISSUE TITLE
Capture NGINX Metrics with Longview Proposed Changes

### ISSUE THREAD

**Issue by archon810** [linode/docs#7010]
Link: https://www.linode.com/docs/products/tools/longview/guides/nginx/
## Issue
In one place, it says

Restart Longview:
```
sudo systemctl restart nginx
```

## Suggested Fix
It should say `restart longview`

**Comment by Rajakavitha1** [comment]
@archon810 Thank you for raising the issue. It has now been fixed in the PR: https://github.com/linode/docs/pull/7109

**Comment by Rajakavitha1** [comment]
Fixed in https://github.com/linode/docs/pull/7109
