### ISSUE TITLE
Use Terraform to Provision Infrastructure on Linode Proposed Changes

### ISSUE THREAD

**Issue by aweingarten** [linode/docs#7014]
Link: https://www.linode.com/docs/guides/how-to-build-your-infrastructure-using-terraform-and-linode/
## Issue
We are telling customers to put their tokens in code which they should never, EVER do.  

provider "linode" {
  token = "YOUR_LINODE_API_TOKEN"
}

## Suggested Fix
We should recommend setting an ENV variable instead.

**Comment by Rajakavitha1** [comment]
Hi @aweingarten  we have provided instruction in the guide here to use https://www.linode.com/docs/guides/how-to-build-your-infrastructure-using-terraform-and-linode/#provision-multiple-servers-using-variables in the `terraform.tfvars` file.

closing this issue for now. Please feel free to reopen if any other details need to be fixed.
