### ISSUE TITLE
Cobrança indevida no meu cartão de crédito 

### ISSUE THREAD

**Issue by Hozana2604** [linode/docs#7021]
Link: https://www.linode.com/docs/products/platform/billing/
## Issue

Boa noite . 

Tive 2 cobrança no meu cartão de crédito e não adquiri nenhum produto linode . Com quem posso falar a respeito . 

Preciso do estorno desse valor . 

Pode me dá um retorno ?

**Comment by Rajakavitha1** [comment]
You may want reach out to our support team using one of the contact options listed here: https://www.linode.com/support/
