### ISSUE TITLE
Understanding iptables Proposed Changes

### ISSUE THREAD

**Issue by mjkim610** [linode/docs#7131]
Link: https://www.linode.com/docs/guides/what-is-iptables/
## Issue
In the image in the [Tables section](https://www.linode.com/docs/guides/what-is-iptables/#tables), the NAT table only contains the output, prerouting, and postrouting chain. It should also include the input chain.

## Suggested Fix
The NAT table should also include the input chain.

**Comment by mjkim610** [comment]
Image location: [docs/guides/security/firewalls/what-is-iptables/iptables-table-of-tables.png](https://github.com/linode/docs/blob/develop/docs/guides/security/firewalls/what-is-iptables/iptables-table-of-tables.png)

**Comment by Rajakavitha1** [comment]
Hi @mjkim610 
Just checked the linux man pages and the built in chains for a NAT table does not include input chain.

https://linux.die.net/man/8/iptables

Closing this issue for now. Pleas feel free to reopen if any other issues needs to be addressed.

**Comment by mjkim610** [comment]
Hi @Rajakavitha1 

I think the die.net documentation is incorrect, and the NAT table does include the input chain.
- https://en.wikipedia.org/wiki/Netfilter#/media/File:Netfilter-packet-flow.svg shows the input chain for NAT
- https://stuffphilwrites.com/fw-ids-iptables-flowchart-v2024-05-22/ shows the input chain for NAT
- `iptables -t nat -L` shows the input chain
```
mj@pc:[~]: sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```

Please check the info above and let me know, thank you! (I don't think I have the privileges for reopening the issue)
