### ISSUE TITLE
Was not asked to set root password during mysql-server installation

### ISSUE THREAD

**Issue by nicolajbky** [linode/docs#724]
Installing mysql through `apt-get install mysql` installed the server, but did not ask to set the initial root password as described in the guides.
Once you run `mysql-secure_installation` and confirm, that the root password is empty, you can (and should) set one.

**Comment by GuessWhoSamFoo** [comment]
See #1117

**Comment by kcraig34** [comment]
@GuessWhoSamFoo -- Thanks for attacking these outstanding bugs. If you want, put the entire list on a card, label red or purple, powerpoint it a .5 or 1, and move into Done Sam column.
Thanks.
