### ISSUE TITLE
Why isn't changing the default port included in the Securing Your Server guide?

### ISSUE THREAD

**Issue by nickreiner** [linode/docs#726]
Is this left out intentionally? 

https://www.linode.com/docs/security/securing-your-server

It's recommended that you change the default 22 ssh port to something else. It's simple to do. Why isn't it included in the guide?

**Comment by blagoeres** [comment]
That doesn't add much IMO. That's more obscurity than security. Nonetheless it can be added.

**Comment by brewn** [comment]
^ +1 what @blagoeres said - changing the port does nothing for security. also, tons of people still use SSH by just typing `ssh me@123.45.67.8` into a terminal, and they would have to specify the port with `-p` or use an ssh config file, which lots of beginners just aren't going to do.

**Comment by rmcintosh** [comment]
Changing the default SSH port does little more than squelch log spam. It's fine to do, but I don't think it needs to be (or should be) in this guide.

**Comment by Guaris** [comment]
Issue closed !
