### ISSUE TITLE
HAProxy instead of KeepAliveD in host-a-website-with-high-availability.md

### ISSUE THREAD

**Issue by ivanbaldo** [linode/docs#748]
https://github.com/linode/docs/blob/master/docs/websites/host-a-website-with-high-availability.md
I think that configuring HAProxy in each app server doing round-robin to the Galera masters is better because:
- it distributes workload between the database nodes instead of always going to one master, hence, more scalable.
- its easier to configure because you don't need the floating IP, contact support, use "strange" (VRRP) network protocols, etc.
Thanks for the guide!!!

**Comment by leslitagordita** [comment]
@ivanbaldo Thank you for your suggestion.  We have queued this guide to be updated with your suggestion considered.

**Comment by Guaris** [comment]
We've added this!
