### ISSUE TITLE
profile directories on Windows

### ISSUE THREAD

**Issue by R-Chandra** [linode/docs#828]
In at least one place, docs/development/version-control/how-to-configure-git.md , there is mention of a user's profile directory, e.g. 

> The full path is C:\Document and Settings\\$USER or C:\Users\\$USER

How about instead just referencing %USERPROFILE% ?  As far as I know, this works across all Windows versions, or whether the profile has been administered to be stored somewhere else.

**Comment by GuessWhoSamFoo** [comment]
Yup, I agree. There is little to none Windows support (for justified reasons) on almost the entire Linode library. PR's are certainly welcome.
