### ISSUE TITLE
Typo in Apache Storm graphic

### ISSUE THREAD

**Issue by pbzona** [linode/docs#859]
In the Apache Storm guide (https://www.linode.com/docs/applications/big-data/big-data-in-the-linode-cloud-streaming-data-processing-with-apache-storm), I noticed an error in one of the graphics.

In the application view within the diagram titled "Storm Topology and Deployment" the first layer of topology is labelled "Sprouts." The correct term is "Spouts" (without the R).

**Comment by GuessWhoSamFoo** [comment]
Thanks for catching it!
