### ISSUE TITLE
use of reboot command in SELinux on Ubuntu

### ISSUE THREAD

**Issue by brewn** [linode/docs#863]
https://linode.com/docs/quick-answers/linux/install-selinux-on-ubuntu

Not a good idea to use the `reboot` command, as the Linode is only going to reboot if Lassie is enabled (which isn't safe to assume), and even then it isn't the command doing the rebooting. Linodes can't tell the hypervisor to reboot them.

**Comment by Guaris** [comment]
@brewn Wow-- It took me a long time to get back to you. I was finally able to look into this issue. The changes will be made. Thanks for contributing.
