### ISSUE TITLE
2GB Image Limit

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#884]
Per issue on Jira, the numbers don't add up: "with a limit of 2GB per Image, with a total of 10GB total Image storage and 3 Images per account.”

Additionally, the example picture exceeds this limit.

https://github.com/linode/docs/blob/master/docs/assets/edit-disk-image.png
https://github.com/linode/docs/blob/master/docs/platform/linode-images.md

**Comment by GuessWhoSamFoo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Converting Jira tickets to Github issues (3PP)](https://trello.com/c/eUF6hRfF/399-converting-jira-tickets-to-github-issues-3pp)

**Comment by Jskobos** [comment]
https://github.com/linode/docs/pull/931
