### ISSUE TITLE
Installation of MySQL on Centos 7 - Include wget

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [linode/docs#907]
https://github.com/linode/docs/blob/master/docs/databases/mysql/how-to-install-mysql-on-centos-7.md

Moved over from Jira, `wget` does not come with default installation of Centos 7. Add `yum install wget` for completeness.

**Comment by GuessWhoSamFoo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Converting Jira tickets to Github issues (3PP)](https://trello.com/c/eUF6hRfF/399-converting-jira-tickets-to-github-issues-3pp)

**Comment by Jskobos** [comment]
Issue resolved, #920
